### PR TITLE
Prevent hoisting of non-hoistable instructions in non-function values with    code

### LINKED ISSUE #4244: Incorrect inlining of generic initializers
```
RWStructuredBuffer<uint> outputBuffer;

struct C<T>
{
    [ForceInline]
    __init<U>(U value)
    {
        for (int i = 0; i < 1; ++i)
        {}
    }
}

static C<int> c = C<int>(1);

int use<T>(T x)
{
    return 1;
}

[numthreads(1, 1, 1)]
void computeMain(uint i : SV_GroupIndex)
{
    outputBuffer[0] = use(c);
}
```

```
(0): error 99999: Slang compilation aborted due to an exception of N5Slang13InternalErrorE: assert failure: condVal.flavor != LatticeVal::Flavor::None
```

It seems like the inlining of the initializer is incorrect, leading to a misleading assert in sccp because of branching on an uninitialized value, invalid IR.

Specifically, bringing up the comparison with `%i` before the `$i` parameter

```
[nameHint("c")]
[export("_SVR34generic_2Dxinitializer_2Dxinlining1c")]
global_var %c   : Ptr(%C)
{
block %21:
        let  %22        : Bool  = cmpLT(%i, 1 : Int)
        [nameHint("i")]
        let  %i1        : Int   = add(%i, 1 : Int)
        loop(%23, %24, %23)

block %23:
        let  %25        : %C    = undefined
        [loopMaxIters(1 : Int)]
        loop(%26, %27, %28, 0 : Int)

block %26(
                [nameHint("i")]
                [nameHint("i")]
                [nameHint("i")]
                [nameHint("i")]
                param %i        : Int):
        ifElse(%22, %29, %27, %29)

block %29:
        unconditionalBranch(%28)

block %28:
        unconditionalBranch(%26, %i1)

block %27:
        unconditionalBranch(%24, %25)

block %24(
                param %30       : %C):
        return_val(%30)
}

```

### PR DESCRIPTION
**Pull request by expipiplus1**
Fixes #4244

### CODE REVIEW

File: source/slang/slang-ir.h [hunk 1]
```diff
@@ -2538,6 +2538,9 @@ bool isBuiltin(IRInst* inst);
     // Get the enclosuing function of an instruction.
 IRFunc* getParentFunc(IRInst* inst);
 
+    // Is child a descendent of inst
+bool hasDescendent(IRInst* inst, IRInst* child);
```
Comment (jkwak-work) [inline source/slang/slang-ir.h:2542]: Nitpick.
Would it be better to rename to `isDescendent`?

**Review by jkwak-work — APPROVED** [review]
Looks good to me.

**Review by csyonghe — APPROVED** [review]
