### PR TITLE
Properly compile `gl_WorkgroupSize`.

### LINKED ISSUE #3910: gl_WorkGroupSize must be a constant
(Thanks for [glsl.meta.slang](https://github.com/shader-slang/slang/blob/master/source/slang/glsl.meta.slang) it's quite helpful to port over GLSL code.)

This shader:
```hlsl
import "glsl";

[shader("compute")] [numthreads(256, 1, 1)] void compute() {
  const uint x = gl_WorkGroupSize.x;
}
```

When compiled like this (v2024.1.6) and passed through `spirv-val` will complain that gl_WorkGroupSize isn't decorated as it should:
```
slangc compute.slang -target spirv -o compute.spv -emit-spirv-directly -fvk-use-entrypoint-name
spirv-val compute.spv 
error: line 7: BuiltIn decoration on target <id> '9[%gl_WorkGroupSize]' must be a constant for WorkgroupSize
  OpDecorate %gl_WorkGroupSize BuiltIn WorkgroupSize
```

### PR DESCRIPTION
**Pull request by csyonghe**
Instead of relying on the WorkgroupSize SPIRV built-in, which has been deprecated and superseded with a dedicated execution mode in spirv 1.6 (which we are not targeting), we simply resolve the workgroup size from the `[numthreads]` decoration and substitute it into the user code.

Fixes #3910.

### CODE REVIEW

File: source/slang/slang-ir-translate-glsl-global-var.cpp [hunk 1]
```diff
@@ -223,6 +228,83 @@ namespace Slang
...
+        //
+        void materializeGetWorkGroupSize(IRModule* module, Dictionary<IRInst*, HashSet<IRFunc*>>& referenceGraph, IRInst* workgroupSizeInst)
+        {
+            IRBuilder builder(workgroupSizeInst);
+            traverseUses(workgroupSizeInst, [&](IRUse* use)
+                {
+                    if (auto parentFunc = getParentFunc(use->getUser()))
+                    {
+                        auto referenceSet = referenceGraph.tryGetValue(parentFunc);
+                        if (!referenceSet) return;
```
Comment (ArielG-NV) [inline source/slang/slang-ir-translate-glsl-global-var.cpp:247]:
```suggestion
                        if (!referenceSet) 
                        	return;
```
To allow code stepping

**Review by ArielG-NV — DISMISSED** [review]
just the 1 comment, code looks good 👍.

**Review by ArielG-NV — APPROVED** [review]

File: tests/spirv/subgroup-size.slang [hunk 2]
```diff
@@ -0,0 +1,16 @@
+import "glsl";
```
Comment (jkwak-work) [inline tests/spirv/subgroup-size.slang:1]: Is this necessary?
