### PR TITLE
Fix the missing derivative member check

### LINKED ISSUE #8568: Crash when checking a struct indirect inheriting from IDifferentiable has DerivativeMember decorated member.
# Issue Description
When define a struct that has a field decorated with `[DerivativeMember()]`, and this strut is indirectly inherited from `IDifferentiable`, compiler will crash.

# Reproducer Code
```
interface IFoo : IDifferentiable
{
    float myFunc();
}

struct Bar: IDifferentiable
{
    float y;
}

struct Foo :  IFoo
{
    typealias Differential = Bar;

    [DerivativeMember(Differential.y)]
    float x;

    [BackwardDifferentiable]
    float myFunc()
    {
        return x * x;
    };
}

```

# Expected Behavior
Code should compile

# Actual Behavior
Crashes.

# Environment
 - Slang Version: master

### PR DESCRIPTION
**Pull request by kaizhangNV**
Close #8568.

The root cause of this issue is that when the struct is indirectly inherited from IDifferentiable type, we will not check the reference of the DerivativeMember attribute. This PR fixes this issue by checking the DerivativeMember attribute right before synthesize the requirement methods of IDifferentiable interface.

### CODE REVIEW

File: source/slang/slang-check-decl.cpp [hunk 1]
```diff
@@ -8141,20 +8164,21 @@ void SemanticsVisitor::checkAggTypeConformance(AggTypeDecl* decl)
         // just with `abstract` methods that replicate things?
         // (That's what C# does).
 
+        // Special handling for when we check for conformance against `IDifferentiable`
```
Comment (csyonghe) [inline source/slang/slang-check-decl.cpp]: What if the `IDifferentiable` conformance is introduced with an `extension` instead of directly from the type itself? Will we still crash?
