### PR TITLE
Fix SER capability hierarchy: make NV derive from EXT (#9756, #9936)

### LINKED ISSUE #9756: EXT_shader_invocation_reorder cannot be used without Slang producing a warning
# Issue Description
In Slang 2026.1.1 `-capability spvShaderInvocationReorderEXT+spvShaderInvocationReorderNV` makes Slang emit `OpHitObjectTraceRayNV` instructions, instead of `OpHitObjectTraceRayEXT` instructions. This is surprising because [Slang should prefer the EXT type](https://github.com/shader-slang/slang/blob/557e45c83c42f3de9228e8446250888d732f3ca6/source/slang/slang-emit-spirv.cpp#L2442).

At the same time, using `HitObject` with only `-capability spvShaderInvocationReorderEXT` makes Slang emit `OpHitObjectTraceRayEXT` instructions, but with a warning that the other capability is required:

```
warning 41012: entry point 'main' uses additional capabilities that are not part of the specified profile 'unknown'. The profile setting is automatically updated to include these capabilities: 'spvShaderInvocationReorderNV'
```

Therefore, it is not possible to have Slang have `HitObject` emit `OpHitObjectTraceRayEXT` without a warning.

Similarly, specifying only `-capability spvShaderInvocationReorderNV` emits a warning about the EXT capability missing.

# Reproducer Code
Save the following code to a file named `capabilities.slang`:

```slang
RaytracingAccelerationStructure tlas;
RWTexture2D<float> outImage;

struct Payload{
	uint foo;
};

[shader("raygeneration")]
void main()
{
	RayDesc ray;
	ray.Origin    = float3(0.);
	ray.Direction = float3(1.);
	ray.TMin      = 0.;
	ray.TMax      = 1e30;
	
	Payload payload;
	HitObject hitObj = HitObject::TraceRay(tlas, 0, 0xFF, 0, 0, 0, ray, payload);
	if(hitObj.IsHit())
	{
		outImage[DispatchRaysIndex().xy] = 1.0f;
	}
}
```

To observe each of the 3 issues:

1. Run `path/to/Slang-windows-x86_64-2026.1.1/bin/slangc.exe" -target spirv -capability spvShaderInvocationReorderEXT+spvShaderInvocationReorderNV -emit-spirv-directly capabilities.slang`. Observe that the SPIR-V output uses `OpHitObjectTraceRayNV` instead of `OpHitObjectTraceRayEXT`:

```
OpHitObjectTraceRayNV %hitObj %41 %uint_0 %uint_255 %uint_0 %uint_0 %uint_0 %73 %74 %75 %76 %p
%52 = OpHitObjectIsHitNV %bool %hitObj
```

2. Run `path/to/Slang-windows-x86_64-2026.1.1/bin/slangc.exe" -target spirv -capability spvShaderInvocationReorderEXT -emit-spirv-directly capabilities.slang`. Now `OpHitObjectTraceRayEXT` appears in the disassembly, but you'll get this warning:

```
capabilities.slang(9): warning 41012: entry point 'main' uses additional capabilities that are not part of the specified profile 'unknown'. The profile setting is automatically updated to include these capabilities: 'spvShaderInvocationReorderNV'
```

3. Run `path/to/Slang-windows-x86_64-2026.1.1/bin/slangc.exe" -target spirv -capability spvShaderInvocationReorderNV -emit-spirv-directly capabilities.slang`. Observe this warning:

```
OpHitObjectTraceRayNV %hitObj %41 %uint_0 %uint_255 %uint_0 %uint_0 %uint_0 %19 %float_0 %24 %float_1_00000002e_30 %p
%52 = OpHitObjectIsHitNV %bool %hitObj
```

# Expected Behavior
`-capability spvShaderInvocationReorderEXT+spvShaderInvocationReorderNV` should emit EXT instructions, and cases (2) and (3) should not emit warnings.

# Environment
 - Slang Version (release version number or commit hash): v2026.1.1
 - OS: Windows 11 23H2

# Additional context
I have the feeling that the issue might be because the standard library's `target_switch` statements prefer matching against the NV extension before matching against `glsl`, if `target_switch` works that way; e.g. https://github.com/shader-slang/slang/blob/557e45c83c42f3de9228e8446250888d732f3ca6/source/slang/hlsl.meta.slang#L21644 .

Thanks!

### PR DESCRIPTION
**Pull request by szihs**
## Summary
Fixes the capability hierarchy for SER (Shader Execution Reorder) so that NV capabilities derive from EXT, eliminating spurious warning 41012.

## Problem
When compiling with `-capability spvShaderInvocationReorderEXT`, Slang would warn about `spvShaderInvocationReorderNV` being added. This happened because NV and EXT SER capabilities were modeled as independent peers, and `__target_switch` cases for both would pull in unrelated atoms.

## Solution
- Model `spvShaderInvocationReorderNV` as deriving from `spvShaderInvocationReorderEXT` in the capdef hierarchy
- Fix SER emit ordering in SPIR-V and GLSL backends to handle the new hierarchy
- Filter alternative vendor atoms from capability warning when a parent capability is already present

Fixes #9756, #9936

## Test plan
- `tests/bugs/gh-9756.slang` - EXT variant, no spurious NV warning
- `tests/bugs/gh-9756-nv.slang` - NV variant works correctly
- `tests/language-feature/capability/alternative-vendor-capability-warning.slang` - vendor capability warning validation

### CODE REVIEW

**Review by expipiplus1 — DISMISSED** [review]
I'm not so sure about this, like the wildcard checking, because sometimes there are important differences between NV and EXT versions for example. I think if we maintained a list of extensions which we have confirmed are equivalent then we'd be giving better error messages

**Comment by szihs** [comment]
> I'm not so sure about this, like the wildcard checking, because sometimes there are important differences between NV and EXT versions for example.

Can you share some examples. 

The capability system has known limitations: error 36120: if two cases belong to the same target, then one capability set has to be a subset of the other.

Having a list adds maintenance costs.

**Comment by expipiplus1** [comment]
I think that VK_NV_mesh_shader VK_EXT_mesh_shader have different interfaces for example.

File: source/slang/slang-check-shader.cpp [hunk 1]
```diff
@@ -674,16 +674,67 @@ void validateEntryPoint(EntryPoint* entryPoint, DiagnosticSink* sink)
...
                 }
+
+                // Filter out alternative vendor atoms when user specified the alternative.
+                // Only filter known-equivalent pairs to avoid hiding important differences.
+                struct VendorAlternativePair
+                {
+                    CapabilityName first;
+                    CapabilityName second;
+                };
+                static const VendorAlternativePair kVendorAlternatives[] = {
```
Comment (csyonghe) [inline source/slang/slang-check-shader.cpp]: Ideally this should go into the capdef file. Just extend its format to carry vendor alternative info, and parse +handle this systematically. We should not have more than one place where we define this kind of metadata about capabilities.

**Comment by csyonghe** [comment]
As commented inline, I want to see us consolidate all meta info about capabilities in the capdef file, and extend that system to handle this kind of features, instead of inventing new logic directly in the compiler code, this increases the maintainence complexity.

File: tools/slang-capability-generator/capability-generator-main.cpp [hunk 2]
```diff
@@ -478,6 +488,30 @@ struct CapabilityDefParser
             {
                 def->flavor = CapabilityFlavor::Normal;
             }
+            else if (nextToken.getContent() == "alternative")
+            {
```
[the remark this answers is not in the document]
Comment (szihs) [reply tools/slang-capability-generator/capability-generator-main.cpp]: https://github.com/shader-slang/slang/pull/9777/changes#diff-e66dba6b868acdc9af7e4d841a141142a750845a23b0dd403aaf68b31dc398bfR41

there is sufficient documentation in the capdef file.

File: source/slang/slang-check-shader.cpp [hunk 3]
```diff
@@ -674,16 +674,35 @@ void validateEntryPoint(EntryPoint* entryPoint, DiagnosticSink* sink)
...
+                // to avoid hiding important differences.
+                CapabilityAtomSet filteredAddedAtoms{};
+                for (auto atom : addedAtoms.getElements<CapabilityAtom>())
+                {
+                    bool hasAlternativeInTarget =
+                        maybeTargetCapSet &&
+                        hasAlternativeCapabilityInSet(atom, *maybeTargetCapSet);
+
+                    if (!hasAlternativeInTarget)
+                        filteredAddedAtoms.add(UInt(atom));
```
[the remark this answers is not in the document]
Comment (szihs) [reply source/slang/slang-check-shader.cpp]: enum class needs explicit cast.

File: source/slang/slang-check-shader.cpp (hunk 1 above)
Comment (szihs) [reply source/slang/slang-check-shader.cpp]: Updated. can you review.

**Review by csyonghe — COMMENTED** [review]
I am not sure what problem this PR is trying to solve.

If we are actually generating code that uses the NV extension but the user specifies EXT extension, then there *should* be a warning, no?

**Comment by csyonghe** [comment]
If a target_switch contains both NV and EXT branches, it is not a valid construct unless the NV capability implies the EXT capability (or the other way around).  Let's assume that in this case, we defined the NV capbility to "inherit" from the EXT capability.

in this case, the `__target_switch` that contains branches for both NV and EXT will evaluate to require just `EXT` (the lesser requirement). If the user specified EXT -- there should be no problems because the target switch only requires EXT. If the user specified NV, there is also no problem because NV implies EXT, and the target switch requires just EXT.

So why are there warnings at all? This can't happen unless the NV or EXT extension isn't defined to have one inherit from another, which is an ill-formed scenario for the target switch that we should have diagnosed an error on the target switch.

**Comment by szihs** [comment]
> If a target_switch contains both NV and EXT branches, it is not a valid construct unless the NV capability implies the EXT capability (or the other way around).

NV and EXT are sibling capabilities representing alternative vendor implementations of the same feature - not a subset/superset relationship. Why should one inherit from the other?

The current capdef correctly models them as parallel definitions with a shared base (`_spirv_1_5 + SPV_KHR_ray_tracing`). Having `spvShaderInvocationReorderNV : spvShaderInvocationReorderEXT` would incorrectly imply that NV functionality is a superset of EXT, which is not the case - they are functionally equivalent alternatives.

The `__target_switch` pattern with both NV and EXT branches is valid for providing vendor-specific codepaths while maintaining a cross-vendor fallback.

**Comment by csyonghe** [comment]
We have to model it as one inheriting from another because there is a strict limit of what __target_switch can do in our language.

All cases in __target_swtich that belongs to the same target (e.g. spirv) must be union-able in to a single capability -- which means if you have two cases for `spirv`, one must strictly imply the other. If this assumption is broken, there is no valid way to represent the overall capabiltiy requirement by that __target_switch, since it would introduce a true disjunction that can't be represented and reasoned about efficiently without falling into an exponential complexity algorithm.

We don't have explicit check on this -- and we should add it to the language to make this an error, because there is no correct way to compile such code. Making NV inherit from EXT (so we only pick NV if the user explicitly specify it via commandline) is the best thing we can do for now.

**Comment by szihs** [comment]
Reworked based on review feedback - NV capabilities now derive from EXT in capdef hierarchy. Force-pushing as a single squashed commit.

File: source/slang/slang-check-shader.cpp [hunk 4]
```diff
@@ -1051,16 +1051,49 @@ void validateEntryPoint(EntryPoint* entryPoint, DiagnosticSink* sink)
...
                     {
                         CapabilityAtomSet::calcSubtract(
                             addedAtoms,
                             (*combinedSet),
-                            (*targetCapSet));
+                            (*maybeTargetCapSet));
                     }
                 }
+
+                // Filter out atoms that derive from SPV_ extension atoms
```
Comment (csyonghe) [inline source/slang/slang-check-shader.cpp]: why is this still needed?

Comment (szihs) [reply source/slang/slang-check-shader.cpp]: @csyonghe  - If we don't we still get warning for EXT case.

PS C:\Users\local-haaggarwal\slang> $env:SLANG_RUN_SPIRV_VALIDATION = "1";.\build\Debug\bin\slangc.exe -target spirv -capability spvShaderInvocationReorderEXT -emit-spirv-directly .\test.slang
.\test.slang(9): warning 41012: entry point 'main' uses additional capabilities that are not part of the specified profile 'unknown'. The profile setting is automatically updated to include these capabilities: 'spvShaderInvocationReorderNV'
void main()
...

Note : -capability `spvShaderInvocationReorderEXT+spvShaderInvocationReorderNV` for EXT case works, but this seems not the correct thing to do.

Hence the filtering logic

**Comment by szihs** [comment]
@csyonghe  let me know if it is okay for user to provide. -capability EXT+NV even though it only needs EXT.
Honestly that is fragile check and I am not sure we should just be okay with upgrading capability warning

File: source/slang/slang-check-shader.cpp (hunk 4 above)
Comment (szihs) [reply source/slang/slang-check-shader.cpp]: Updated change to remove the flaky check which even though does work may skip some genuine warnings.

**Review by expipiplus1 — APPROVED** [review]
lgtm! thanks
