### PR TITLE
bit_cast & reinterpret warning if src->dst type not equally sized.

### LINKED ISSUE #3331: `reinterpret` miscompiles.
I have this shader:
```
import quaternion;

struct vertex_t {
    float3 position : POSITION;
    float4 color    : COLOR;
    float2 uv       : TEXCOORD0;
    float3 normal   : NORMAL;
};

struct vertex_output_t {
    float4 position : SV_Position;
    float4 color    : COLOR;
    float2 uv       : UV;
    float3 normal   : NORMAL;
}

struct camera_consts {
    float4x4 view;
    float4x4 projection;
};

[vk::push_constant]
camera_consts camera;

// Align to 32 bytes.
struct entity_t {
    float3 world_transform;
    quaternion rotation;
};


[vk::binding(0, 0)]
ByteAddressBuffer buffer;

static constexpr float4x4 identity = {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1};

[shader("vertex")]
vertex_output_t vertex_main(vertex_t vertex) {
    float3 local_position = vertex.position;
    float3 normal = vertex.normal;
    float2 uv = vertex.uv;
    float4 color = vertex.color;
    float3 world_transform = buffer.Load<entity_t>(0).world_transform;

    float4x4 view_proj = mul(camera.projection, camera.view);
    float4x4 translation = {
        {1,0,0,world_transform.x},
        {0,1,0,world_transform.y},
        {0,0,1,world_transform.z},
        {0,0,0,1}
    };

    vertex_output_t output;
    output.normal = normal;
    output.uv = uv;
    output.color = color;
    output.position = mul(view_proj, mul(translation, float4(local_position, 1)));

    return output;
}
```

When I compile it, I get this correct code generation:
```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 11
; Bound: 225
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %_S8 %_S7 %_S6 %_S5 %_ %_S2 %_S3 %_S4
               OpSource GLSL 450
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpName %main "main"
               OpName %StructuredBuffer_float_t_0 "StructuredBuffer_float_t_0"
               OpMemberName %StructuredBuffer_float_t_0 0 "_data"
               OpName %buffer_0 "buffer_0"
               OpName %_S1 "_S1"
               OpMemberName %_S1 0 "view_0"
               OpMemberName %_S1 1 "projection_0"
               OpName %camera_0 "camera_0"
               OpName %_S8 "_S8"
               OpName %_S7 "_S7"
               OpName %_S6 "_S6"
               OpName %_S5 "_S5"
               OpName %gl_PerVertex "gl_PerVertex"
               OpMemberName %gl_PerVertex 0 "gl_Position"
               OpMemberName %gl_PerVertex 1 "gl_PointSize"
               OpMemberName %gl_PerVertex 2 "gl_ClipDistance"
               OpMemberName %gl_PerVertex 3 "gl_CullDistance"
               OpName %_ ""
               OpName %_S2 "_S2"
               OpName %_S3 "_S3"
               OpName %_S4 "_S4"
               OpDecorate %_runtimearr_float ArrayStride 4
               OpMemberDecorate %StructuredBuffer_float_t_0 0 NonWritable
               OpMemberDecorate %StructuredBuffer_float_t_0 0 Offset 0
               OpDecorate %StructuredBuffer_float_t_0 BufferBlock
               OpDecorate %buffer_0 DescriptorSet 0
               OpDecorate %buffer_0 Binding 0
               OpMemberDecorate %_S1 0 RowMajor
               OpMemberDecorate %_S1 0 Offset 0
               OpMemberDecorate %_S1 0 MatrixStride 16
               OpMemberDecorate %_S1 1 RowMajor
               OpMemberDecorate %_S1 1 Offset 64
               OpMemberDecorate %_S1 1 MatrixStride 16
               OpDecorate %_S1 Block
               OpDecorate %_S8 Location 3
               OpDecorate %_S7 Location 2
               OpDecorate %_S6 Location 1
               OpDecorate %_S5 Location 0
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
               OpDecorate %gl_PerVertex Block
               OpDecorate %_S2 Location 0
               OpDecorate %_S3 Location 1
               OpDecorate %_S4 Location 2
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
      %float = OpTypeFloat 32
    %v3float = OpTypeVector %float 3
    %v4float = OpTypeVector %float 4
%_runtimearr_float = OpTypeRuntimeArray %float
%StructuredBuffer_float_t_0 = OpTypeStruct %_runtimearr_float
%_ptr_Uniform_StructuredBuffer_float_t_0 = OpTypePointer Uniform %StructuredBuffer_float_t_0
   %buffer_0 = OpVariable %_ptr_Uniform_StructuredBuffer_float_t_0 Uniform
      %int_0 = OpConstant %int 0
      %int_4 = OpConstant %int 4
%_ptr_Uniform_float = OpTypePointer Uniform %float
      %int_8 = OpConstant %int 8
%mat4v4float = OpTypeMatrix %v4float 4
        %_S1 = OpTypeStruct %mat4v4float %mat4v4float
%_ptr_PushConstant__S1 = OpTypePointer PushConstant %_S1
   %camera_0 = OpVariable %_ptr_PushConstant__S1 PushConstant
%_ptr_PushConstant_mat4v4float = OpTypePointer PushConstant %mat4v4float
      %int_1 = OpConstant %int 1
    %float_1 = OpConstant %float 1
    %float_0 = OpConstant %float 0
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
        %108 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_1
    %v2float = OpTypeVector %float 2
%_ptr_Input_v3float = OpTypePointer Input %v3float
        %_S8 = OpVariable %_ptr_Input_v3float Input
%_ptr_Input_v2float = OpTypePointer Input %v2float
        %_S7 = OpVariable %_ptr_Input_v2float Input
%_ptr_Input_v4float = OpTypePointer Input %v4float
        %_S6 = OpVariable %_ptr_Input_v4float Input
        %_S5 = OpVariable %_ptr_Input_v3float Input
%_arr_float_uint_1 = OpTypeArray %float %uint_1
%gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
          %_ = OpVariable %_ptr_Output_gl_PerVertex Output
%_ptr_Output_v4float = OpTypePointer Output %v4float
        %_S2 = OpVariable %_ptr_Output_v4float Output
%_ptr_Output_v2float = OpTypePointer Output %v2float
        %_S3 = OpVariable %_ptr_Output_v2float Output
%_ptr_Output_v3float = OpTypePointer Output %v3float
        %_S4 = OpVariable %_ptr_Output_v3float Output
       %main = OpFunction %void None %3
          %5 = OpLabel
        %211 = OpSDiv %int %int_0 %int_4
        %212 = OpAccessChain %_ptr_Uniform_float %buffer_0 %int_0 %211
        %213 = OpLoad %float %212
        %215 = OpIAdd %int %int_0 %int_4
        %216 = OpSDiv %int %215 %int_4
        %217 = OpAccessChain %_ptr_Uniform_float %buffer_0 %int_0 %216
        %218 = OpLoad %float %217
        %220 = OpIAdd %int %int_0 %int_8
        %221 = OpSDiv %int %220 %int_4
        %222 = OpAccessChain %_ptr_Uniform_float %buffer_0 %int_0 %221
        %223 = OpLoad %float %222
        %224 = OpCompositeConstruct %v3float %213 %218 %223
         %85 = OpAccessChain %_ptr_PushConstant_mat4v4float %camera_0 %int_0
         %86 = OpLoad %mat4v4float %85
         %88 = OpAccessChain %_ptr_PushConstant_mat4v4float %camera_0 %int_1
         %89 = OpLoad %mat4v4float %88
         %90 = OpMatrixTimesMatrix %mat4v4float %86 %89
         %98 = OpCompositeExtract %float %224 0
        %102 = OpCompositeExtract %float %224 1
        %106 = OpCompositeExtract %float %224 2
        %125 = OpCompositeConstruct %v4float %float_1 %float_0 %float_0 %98
        %126 = OpCompositeConstruct %v4float %float_0 %float_1 %float_0 %102
        %127 = OpCompositeConstruct %v4float %float_0 %float_0 %float_1 %106
        %129 = OpCompositeConstruct %mat4v4float %125 %126 %127 %108
        %137 = OpLoad %v3float %_S8
        %143 = OpLoad %v2float %_S7
        %148 = OpLoad %v4float %_S6
        %152 = OpLoad %v3float %_S5
        %153 = OpCompositeExtract %float %152 0
        %154 = OpCompositeExtract %float %152 1
        %155 = OpCompositeExtract %float %152 2
        %156 = OpCompositeConstruct %v4float %153 %154 %155 %float_1
        %158 = OpVectorTimesMatrix %v4float %156 %129
        %160 = OpVectorTimesMatrix %v4float %158 %90
        %171 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %171 %160
               OpStore %_S2 %148
               OpStore %_S3 %143
               OpStore %_S4 %137
               OpReturn
               OpFunctionEnd
```
If, rather than `Load`ing an `entity_t` from `buffer`, I `reinterpret` it like:

`float3 world_transform = reinterpret<entity_t>(buffer.Load(0)).world_transform;`

Then with no diagnostic, I get this codegen instead:
```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 11
; Bound: 347
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %_S12 %_S11 %_S10 %_S9 %_ %_S6 %_S7 %_S8
               OpSource GLSL 450
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpName %main "main"
               OpName %StructuredBuffer_uint_t_0 "StructuredBuffer_uint_t_0"
               OpMemberName %StructuredBuffer_uint_t_0 0 "_data"
               OpName %buffer_0 "buffer_0"
               OpName %_S1 "_S1"
               OpMemberName %_S1 0 "view_0"
               OpMemberName %_S1 1 "projection_0"
               OpName %camera_0 "camera_0"
               OpName %_S12 "_S12"
               OpName %_S11 "_S11"
               OpName %_S10 "_S10"
               OpName %_S9 "_S9"
               OpName %gl_PerVertex "gl_PerVertex"
               OpMemberName %gl_PerVertex 0 "gl_Position"
               OpMemberName %gl_PerVertex 1 "gl_PointSize"
               OpMemberName %gl_PerVertex 2 "gl_ClipDistance"
               OpMemberName %gl_PerVertex 3 "gl_CullDistance"
               OpName %_ ""
               OpName %_S6 "_S6"
               OpName %_S7 "_S7"
               OpName %_S8 "_S8"
               OpDecorate %_runtimearr_uint ArrayStride 4
               OpMemberDecorate %StructuredBuffer_uint_t_0 0 NonWritable
               OpMemberDecorate %StructuredBuffer_uint_t_0 0 Offset 0
               OpDecorate %StructuredBuffer_uint_t_0 BufferBlock
               OpDecorate %buffer_0 DescriptorSet 0
               OpDecorate %buffer_0 Binding 0
               OpMemberDecorate %_S1 0 RowMajor
               OpMemberDecorate %_S1 0 Offset 0
               OpMemberDecorate %_S1 0 MatrixStride 16
               OpMemberDecorate %_S1 1 RowMajor
               OpMemberDecorate %_S1 1 Offset 64
               OpMemberDecorate %_S1 1 MatrixStride 16
               OpDecorate %_S1 Block
               OpDecorate %_S12 Location 3
               OpDecorate %_S11 Location 2
               OpDecorate %_S10 Location 1
               OpDecorate %_S9 Location 0
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
               OpDecorate %gl_PerVertex Block
               OpDecorate %_S6 Location 0
               OpDecorate %_S7 Location 1
               OpDecorate %_S8 Location 2
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
      %float = OpTypeFloat 32
    %v3float = OpTypeVector %float 3
    %v4float = OpTypeVector %float 4
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
     %uint_0 = OpConstant %uint 0
      %int_1 = OpConstant %int 1
     %uint_1 = OpConstant %uint 1
%_runtimearr_uint = OpTypeRuntimeArray %uint
%StructuredBuffer_uint_t_0 = OpTypeStruct %_runtimearr_uint
%_ptr_Uniform_StructuredBuffer_uint_t_0 = OpTypePointer Uniform %StructuredBuffer_uint_t_0
   %buffer_0 = OpVariable %_ptr_Uniform_StructuredBuffer_uint_t_0 Uniform
%_ptr_Uniform_uint = OpTypePointer Uniform %uint
%mat4v4float = OpTypeMatrix %v4float 4
        %_S1 = OpTypeStruct %mat4v4float %mat4v4float
%_ptr_PushConstant__S1 = OpTypePointer PushConstant %_S1
   %camera_0 = OpVariable %_ptr_PushConstant__S1 PushConstant
%_ptr_PushConstant_mat4v4float = OpTypePointer PushConstant %mat4v4float
    %float_1 = OpConstant %float 1
    %float_0 = OpConstant %float 0
        %118 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_1
    %v2float = OpTypeVector %float 2
%_ptr_Input_v3float = OpTypePointer Input %v3float
       %_S12 = OpVariable %_ptr_Input_v3float Input
%_ptr_Function_v3float = OpTypePointer Function %v3float
%_ptr_Input_v2float = OpTypePointer Input %v2float
       %_S11 = OpVariable %_ptr_Input_v2float Input
%_ptr_Input_v4float = OpTypePointer Input %v4float
       %_S10 = OpVariable %_ptr_Input_v4float Input
        %_S9 = OpVariable %_ptr_Input_v3float Input
%_arr_float_uint_1 = OpTypeArray %float %uint_1
%gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
          %_ = OpVariable %_ptr_Output_gl_PerVertex Output
%_ptr_Output_v4float = OpTypePointer Output %v4float
        %_S6 = OpVariable %_ptr_Output_v4float Output
%_ptr_Output_v2float = OpTypePointer Output %v2float
        %_S7 = OpVariable %_ptr_Output_v2float Output
%_ptr_Output_v3float = OpTypePointer Output %v3float
        %_S8 = OpVariable %_ptr_Output_v3float Output
       %main = OpFunction %void None %3
          %5 = OpLabel
        %237 = OpVariable %_ptr_Function_v3float Function
         %89 = OpAccessChain %_ptr_Uniform_uint %buffer_0 %int_0 %int_0
         %90 = OpLoad %uint %89
        %210 = OpBitcast %float %90
        %341 = OpLoad %v3float %237
        %342 = OpCompositeInsert %v3float %210 %341 0
        %214 = OpBitcast %float %uint_0
        %344 = OpCompositeInsert %v3float %214 %342 1
        %218 = OpBitcast %float %uint_0
        %346 = OpCompositeInsert %v3float %218 %344 2
               OpStore %237 %346
        %101 = OpAccessChain %_ptr_PushConstant_mat4v4float %camera_0 %int_0
        %102 = OpLoad %mat4v4float %101
        %103 = OpAccessChain %_ptr_PushConstant_mat4v4float %camera_0 %int_1
        %104 = OpLoad %mat4v4float %103
        %105 = OpMatrixTimesMatrix %mat4v4float %102 %104
        %110 = OpCompositeExtract %float %346 0
        %113 = OpCompositeExtract %float %346 1
        %116 = OpCompositeExtract %float %346 2
        %135 = OpCompositeConstruct %v4float %float_1 %float_0 %float_0 %110
        %136 = OpCompositeConstruct %v4float %float_0 %float_1 %float_0 %113
        %137 = OpCompositeConstruct %v4float %float_0 %float_0 %float_1 %116
        %139 = OpCompositeConstruct %mat4v4float %135 %136 %137 %118
        %146 = OpLoad %v3float %_S12
        %151 = OpLoad %v2float %_S11
        %156 = OpLoad %v4float %_S10
        %160 = OpLoad %v3float %_S9
        %161 = OpCompositeExtract %float %160 0
        %162 = OpCompositeExtract %float %160 1
        %163 = OpCompositeExtract %float %160 2
        %164 = OpCompositeConstruct %v4float %161 %162 %163 %float_1
        %166 = OpVectorTimesMatrix %v4float %164 %139
        %168 = OpVectorTimesMatrix %v4float %166 %105
        %179 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %179 %168
               OpStore %_S6 %156
               OpStore %_S7 %151
               OpStore %_S8 %146
               OpReturn
               OpFunctionEnd
```
This only loads the x component of my entities' `position`, not the z. The diff of these shaders seems pretty huge, too.

### LINKED ISSUE #3983: Narrowing bit_cast fails vulkan validation
Hi,

the following program fails vulkan validation when compiled using slang 2024.1.7 with the command `slangc.exe -entry computeMain -stage compute -target spirv -O0 -emit-spirv-directly -o shader.spv && spirv-val.exe shader.spv`:
```c++
uniform StructuredBuffer<uint64_t> in;
uniform RWStructuredBuffer<uint32_t> out;

[numthreads(4, 1, 1)]
[shader("compute")]
void computeMain() {
    out[0] = bit_cast<uint32_t>(in[0]);
}
```

Gives me the following SPIRV validation error (using spirv-val from the 1.3.280.0 Vulkan SDK):
```
error: line 50: Expected input to have the same total bit width as Result Type: Bitcast
  %23 = OpBitcast %uint %22
```

I'd rather have the warning already in slang's frontend instead of only during SPIRV validation.

Thanks for having a look!

### PR DESCRIPTION
**Pull request by ArielG-NV**
bit_cast & reinterpret warning if src->dst type not equally sized.
Fixes #3331
Fixes #3983

### CODE REVIEW

File: source/slang/slang-diagnostic-defs.h [hunk 1]
```diff
@@ -358,6 +358,9 @@ DIAGNOSTIC(30099, Error, sizeOfArgumentIsInvalid, "argument to sizeof is invalid
 
 DIAGNOSTIC(30101, Error, readingFromWriteOnly, "cannot read from writeonly, check modifiers.")
 
+DIAGNOSTIC(30102, Warning, notEqualBitCastSize, "trying to bit_cast not equally sized type '$0' with size '$1' into type '$2' with size '$3'")
```
Comment (csyonghe) [inline source/slang/slang-diagnostic-defs.h:361]: Since this is a code-gen time error, it needs to start with a 4xxxx number.

**Review by csyonghe — DISMISSED** [review]

**Comment by csyonghe** [comment]
Thank you for fixing this issue quickly!

File: source/slang/slang-diagnostic-defs.h [hunk 2]
```diff
@@ -744,6 +744,10 @@ DIAGNOSTIC(45001, Error, unresolvedSymbol, "unresolved external symbol '$0'.")
 DIAGNOSTIC(41201, Warning, expectDynamicUniformArgument, "argument for '$0' might not be a dynamic uniform, use `asDynamicUniform()` to silence this warning.")
 DIAGNOSTIC(41201, Warning, expectDynamicUniformValue, "value stored at this location must be dynamic uniform, use `asDynamicUniform()` to silence this warning.")
 
+
+DIAGNOSTIC(41202, Warning, notEqualBitCastSize, "trying to bit_cast not equally sized type '$0' with size '$1' into type '$2' with size '$3'")
```
Comment (csyonghe) [inline source/slang/slang-diagnostic-defs.h:748]: This should be made an error.

File: source/slang/slang-diagnostic-defs.h [hunk 3]
```diff
@@ -744,6 +744,10 @@ DIAGNOSTIC(45001, Error, unresolvedSymbol, "unresolved external symbol '$0'.")
 DIAGNOSTIC(41201, Warning, expectDynamicUniformArgument, "argument for '$0' might not be a dynamic uniform, use `asDynamicUniform()` to silence this warning.")
 DIAGNOSTIC(41201, Warning, expectDynamicUniformValue, "value stored at this location must be dynamic uniform, use `asDynamicUniform()` to silence this warning.")
 
+
+DIAGNOSTIC(41202, Error, notEqualBitCastSize, "trying to bit_cast not equally sized type '$0' with size '$1' into type '$2' with size '$3'")
+DIAGNOSTIC(41203, Warning, notEqualReinterpretCastSize, "trying to reinterpret not equally sized type '$0' with size '$1' into type '$2' with size '$3'")
```
Comment (jkwak-work) [inline source/slang/slang-diagnostic-defs.h:749]: Feel free to ignore this but I would prefer message more like,
```
Invalid reinterpret_cast when the sizes of given types are different
```

File: source/slang/slang-ir-lower-bit-cast.cpp [hunk 4]
```diff
@@ -238,6 +247,10 @@ struct BitCastLoweringContext
         {
             return;
         }
+
+        if (fromTypeSize.size != toTypeSize.size)
```
Comment (jkwak-work) [inline source/slang/slang-ir-lower-bit-cast.cpp:251]: Shouldn't we also check the alignment?
For the primitive types, the alignments are same as their sizes but for structs, the alignments are the biggest alignment value among the members. That case give us a case where the alignments are different when their sizes are same.

File: source/slang/slang-diagnostic-defs.h (hunk 3 above)
Comment (ArielG-NV) [reply source/slang/slang-diagnostic-defs.h:749]: I will adjust the wording to be clearer. 
I think I will still include the type+size_of part of the warning. This is an easy to make (but hard to find) mistake. 
I will use `reinterpret<>` instead of reinterpret_cast since Slang code uses `reinterpret<>` syntax.

**Review by csyonghe — APPROVED** [review]
