### PR TITLE
Fix Optional none lowering for DifferentialPair

### LINKED ISSUE #9526: compiler crash around assigning none value to Optional<T> where T is a DifferentialPair.
# Issue Description
The issue is described as title.

# Reproducer Code
```
struct myStruct: IDifferentiable
{
    int a;
    int b;
}

int func(Optional<DifferentialPair<myStruct>> s)
{
    if (s.hasValue)
    {
        int x = s.value.p.a + s.value.p.b;
        return x;
    }
    return 0;
}

RWStructuredBuffer<int> outbuffer;

[shader("compute")]
void computeMain()
{
    outbuffer[0] = func(none);
}
```

# Expected Behavior
This code should compile.

# Actual Behavior
It crashes during specialization.

# Environment
 - Slang Version (release version number or commit hash)
 - OS
 - GPU/Driver version, if the bug is a runtime result error.
 - Any related environment variables.

# Additional context
The reason of the crash is because of our lowering logic will lower the `none` assignment as
```
	let  %39	: %DiffPairx5FmyStruct	= makeStruct
	let  %40	: Optional(%DiffPairx5FmyStruct)	= makeOptionalNone(%39)
```
This requires user code to call the constructor of `Optional<T>()` instead of just assign a `none`, for example:
```
outbuffer[0] = func(Optional<DifferentialPair<myStruct>>());
```
will just work.

This might not really be a bug, but it will make the user code more convenient if we can remove the argument from `makeOptionalNone` inst. So `%39` is not necessary anymore.

### PR DESCRIPTION
**Pull request by NV-xiaoyongs**
Fixes #9526 

fix Optional none lowering for DifferentialPair
add regression test

### CODE REVIEW

**Comment by ncelikNV** [comment]
The PR description should say "Fixes #9526" instead of just "#9526" for GitHub to automatically close the issue once the PR is merged.

**Comment by ncelikNV** [comment]
FYI the Slang team prefers we sync PRs with `master` using merge commits instead of rebasing and force-pushing: https://github.com/shader-slang/slang/blob/master/CONTRIBUTING.md#addressing-code-reviews.

File: source/slang/slang-lower-to-ir.cpp [hunk 1]
```diff
@@ -5794,8 +5794,19 @@ struct ExprLoweringVisitorBase : public ExprVisitor<Derived, LoweredValInfo>
...
+            // The payload is semantically irrelevant when `hasValue == false`, and attempting to
+            // synthesize a default value here can produce malformed IR for compiler-synthesized
+            // aggregate types (e.g. `DifferentialPair<T>`), leading to crashes during
+            // specialization.
+            //
+            // Use a default-constructed placeholder of type `T` so that later passes don't treat
+            // the payload as an uninitialized value (core module compilation treats warnings as
+            // fatal during bootstrapping).
+            auto valueType = lowerType(context, as<OptionalType>(expr->type)->getValueType());
+            auto defaultVal = context->irBuilder->emitDefaultConstruct(valueType);
```
Comment (kaizhangNV) [inline source/slang/slang-lower-to-ir.cpp]: What if the type is not default construct-able?
Not all type is default construct-able.

I'm thinking that maybe we can kIROp_MakeOptionalNone to make the second parameter optional, so we don't have to construct the defaultVal.

Comment (kaizhangNV) [reply source/slang/slang-lower-to-ir.cpp]: Or you can use this call:
let defaulVal = getDefaultVal(valueType);

Comment (NV-xiaoyongs) [reply source/slang/slang-lower-to-ir.cpp]: updated

File: source/slang/slang-ir-insts.h [hunk 2]
```diff
@@ -3681,7 +3681,7 @@ struct IRBuilder
     IRInst* emitOptionalHasValue(IRInst* optValue);
     IRInst* emitGetOptionalValue(IRInst* optValue);
     IRInst* emitMakeOptionalValue(IRInst* optType, IRInst* value);
-    IRInst* emitMakeOptionalNone(IRInst* optType, IRInst* defaultValue);
+    IRInst* emitMakeOptionalNone(IRInst* optType);
```
Comment (kaizhangNV) [inline source/slang/slang-ir-insts.h:3684]: @tangent-vector can you please also review it to see if it's fine to change the IR like this?

Comment (tangent-vector) [reply source/slang/slang-ir-insts.h:3684]: I’m not familiar with why the default value operand was there in the first place. @csyonghe is probably the one who would know best.

My guess is that operand is impotent, though, because for many types an `Optional<T>` is stored as a specific bit-pattern in the shape of a `T`, and that operand probably tells the later codegen steps what to store. I wouldn’t go removing it unless I could confirm exactly how/where it gets used and if it is probably always possible to reconstruct an identical value downstream if we remove the operand.

Comment (csyonghe) [reply source/slang/slang-ir-insts.h:3684]: I forgot the detailed reasons, but the idea was that the frontend should know better than the backend what a default value of a type should be, so we always use the most canonical value to fill in the value part.

This may not be necessary for now, since the value part can / should be allowed to be undefined/any value if the optional is none. The default construct synthesized in the backend can be sufficient for now, until we want to properly model a dedicated `IHasNoneValue` trait in the type system.

File: tests/bugs/gh-9526-optional-diffpair-none.slang [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+
+RWStructuredBuffer<int> outBuffer;
+
+[shader("compute")]
+void computeMain()
+{
+    // "Has value" case (idiomatic): assign a `T` into `Optional<T>` to construct an optional-with-value.
+    // Here `T` is `DifferentialPair<MyStruct>`.
+    DifferentialPair<MyStruct> dp = diffPair(MyStruct(1, 2));
+    Optional<DifferentialPair<MyStruct>> some = dp;
```
Comment (csyonghe) [inline tests/bugs/gh-9526-optional-diffpair-none.slang]: we should avoid using reserved keywords like `some` and `func` as identifier names in our test shaders, which are often used as examples of how to write slang code.

Comment (NV-xiaoyongs) [reply tests/bugs/gh-9526-optional-diffpair-none.slang]: Thanks! changed.
