### PR TITLE
Fix atomics error diagnostics

### LINKED ISSUE #8116: Slang incorrectly complains about floating point atomic add/sub on metal
```slang
RWStructuredBuffer<float> input;
RWStructuredBuffer<float> output;

[shader("compute")]
void computeMain(uint3 tid : SV_DispatchThreadID)
{
    uint dst = int(sin(tid.x) * 1000) % 16;
    InterlockedAdd(output[dst], input[tid.x]);
}
```

Targetting metal, this gives:

```
05.slang(8): error 55204: intrinsic operation 'floating point atomic operation' is not supported for the current target.
    InterlockedAdd(output[dst], input[tid.x]);
                  ^
#include <metal_stdlib>
#include <metal_math>
#include <metal_texture>
using namespace metal;

// ...
```

This is inconsistent with the Metal specification (section 6.15.4.5), which says that atomic addition and subtraction are supported.

### PR DESCRIPTION
**Pull request by venkataram-nv**
Fixes #8116

### CODE REVIEW

**Comment by csyonghe** [comment]
should include a test case. perhaps extend one of the existing atomic tests to cover metal.

File: source/slang/slang-emit-metal.cpp [hunk 1]
```diff
@@ -400,7 +400,7 @@ bool MetalSourceEmitter::tryEmitInstStmtImpl(IRInst* inst)
         else
             m_writer->emit(");\n");
     };
-    auto diagnoseFloatAtommic = [&]()
+    auto diagnoseFloatAtomic = [&]()
     {
         getSink()->diagnose(
             inst,
```
Comment (jkwak-work) [inline source/slang/slang-emit-metal.cpp:406]: It looks like the current error message is copied from HLSL implementation.
The situation on Metal is a little different from HLSL in a way that some atomic operations with float is supported and the rest are not.

I think the error message should change to be more like,
```
Unsupported floating point atomic operation
```
It is better because the current error message sounds like floating point is not supported at all for atomic operation.

File: tests/metal/atomic-float-intrinsics.slang [hunk 2]
```diff
@@ -0,0 +1,39 @@
+//TEST:SIMPLE(filecheck=MTL):-target metal -entry computeMain -stage compute -DMETAL
```
Comment (ArielG-NV) [inline tests/metal/atomic-float-intrinsics.slang]: Since we now support float atomic addition, please see if we can add metal support to some already existing float atomic tests.

`tests\bugs\byte-address-buffer-interlocked-add-f32.slang`
`tests\hlsl-intrinsic\texture\float-atomics.slang`
`tests\slang-extension\atomic-float-byte-address-buffer.slang`

**Review by ArielG-NV — COMMENTED** [review]
1 suggestion

File: tests/metal/atomic-float-intrinsics.slang (hunk 2 above)
Comment (jkwak-work) [reply tests/metal/atomic-float-intrinsics.slang]: These functions aren't new ones.
I think we should reused the existing tests like what Ariel said here.

**Review by jkwak-work — APPROVED** [review]
Looks good to me
