### PR TITLE
 Fix type substitution for associatedtype

### LINKED ISSUE #341: Bug: associatedtype as generic function parameter not working
Test case to trigger the bug:
```
//TEST(compute):COMPARE_COMPUTE:-xslang -use-ir
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out

// Test type checking of associatedtype and typedef

RWStructuredBuffer<float> outputBuffer;

interface IBase
{
    associatedtype SubTypeT;
    associatedtype RetT;
    RetT getVal(SubTypeT t);
    SubTypeT setVal(RetT v);
}

struct SubType<T>
{
    T x;
};

struct GenStruct<T> : IBase
{
    typedef T RetT;
    typedef SubType<RetT> SubTypeT;
    SubTypeT setVal(T val)
    {
        SubTypeT rs;
        rs.x = val;
        return rs;
    }
    T getVal(SubTypeT v)
    {
        return v.x;
    }
};

U.RetT test<U:IBase>(U.RetT val)
{
    U obj;
    U.SubTypeT sb = obj.setVal(val);
    return obj.getVal(sb);
}


[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    uint tid = dispatchThreadID.x;
    float inVal = float(tid);
    /* wrong error message for the following line */
    float outVal = test<GenStruct<float> >(inVal);
    outputBuffer[tid] = outVal.x;
}
```

The compiler mistakenly reports following error message:

```
D:\git_repo\slang\tests/compute/typedef-member.slang(50): error 30019: expected an expression of type 'T', got 'float'
D:\git_repo\slang\tests/compute/typedef-member.slang(50): error 30019: expected an expression of type 'float', got 'T'
```

### PR DESCRIPTION
**Pull request by csyonghe**
fixes #341

When a typedef definition is used to satisfy an associated type, we must also substitute the resulting typedef type using parent substitution, in the case that the typedef is a generic application.

### CODE REVIEW

File: source/slang/syntax.cpp [hunk 1]
```diff
@@ -505,7 +505,7 @@ void Type::accept(IValVisitor* visitor, void* extra)
                         if (aggTypeDeclRef.getDecl()->memberDictionary.TryGetValue(assocTypeDecl->getName(), targetType))
                         {
                             if (auto typeDefDecl = dynamic_cast<TypeDefDecl*>(targetType))
-                                return typeDefDecl->type.type;
+                                return typeDefDecl->type.type->Substitute(aggTypeDeclRef.substitutions);
                             else
```
Comment (tfoleyNV) [inline source/slang/syntax.cpp]: It seems like this could also be handled by forming a `DeclRef` to `targetType` and then doing the dispatch on that, so you can do `GetType(typeDefDeclRef)` on a `DeclRef<TypeDefDecl>`.

I’m not sure that is a net improvement, but it might help if there are many cases to always start with a `DeclRef`.
