### PR TITLE
Fix infinite loop in SPIRVLegalizationContext::processWorkList

### LINKED ISSUE #8669: slangc hang when compiling infinite loop with -g option
# Issue Description
When trivial shader contains static infinite loop, slangc.exe hangs when compiling with `-g`, `-g1` etc, but not `-g0`.
```
layout(location = 0) out float4 output_color;
[shader("fragment")]
void main()
{
    while (true) { int i = 0; }
    output_color = float4(1, 2, 3, 4);
}
```

The hang seems to be `SPIRVLegalizationContext::processWorkList` loop on removing kIROp_UnconditionalBranch then adding its target, and user which is the same kIROp_UnconditionalBranch itself.

IR snippet is:
```
func %main	: Func(Void)
{
block %8:
	DebugLine(%7, 8 : UInt, 8 : UInt, 5 : UInt, 6 : UInt)
	DebugLine(%7, 8 : UInt, 8 : UInt, 5 : UInt, 6 : UInt)
	DebugLine(%7, 8 : UInt, 8 : UInt, 5 : UInt, 6 : UInt)
	loop(%9, %10, %9)

block %9:
	DebugLine(%7, 8 : UInt, 8 : UInt, 12 : UInt, 13 : UInt)
	unconditionalBranch(%11)

block %11:
	DebugLine(%7, 8 : UInt, 8 : UInt, 20 : UInt, 21 : UInt)
	DebugLine(%7, 8 : UInt, 8 : UInt, 20 : UInt, 21 : UInt)
	[DebugLocation(%7, 8 : UInt, 24 : UInt)]
	[nameHint("i")]
	let  %i	: Ptr(Int)	= DebugVar(%7, 8 : UInt, 24 : UInt)
	DebugValue(%i, 0 : Int)
	unconditionalBranch(%9)

block %10:
	unreachable
}
```

### PR DESCRIPTION
**Pull request by davli-nv**
When slangc is invoked with -g, a source shader that has static infinite loop can generate IR that have branch to a block that contains a branch to the first block that contains the first branch, resulting in infinite loop.

Change SPIRVLegalizationContext::processWorkList to only add branch target to work list via its parent, this avoids the infinite loop above.

Also change addToWorkList to stop addUsersToWorkList, users should be added explicitly by logic for specific insts.

Add regression test as tests/spirv/infinite-loop.slang

Fixes #8669

### CODE REVIEW

**Review by csyonghe — CHANGES_REQUESTED** [review]
Can you please include a regression test that reproduces the issue you are trying to fix?

**Comment by davli-nv** [comment]
Good call about regression test, it caught that I had change to `processBranch` that actually fixed the infinite loop problem. The change for `addToWorkList` to stop `addUsersToWorkList` doesn't help with the infinite loop, it just reduces amount of duplicates added into work list.

Also I'm seeing debug assert about main func missing entry point decoration after rebase today which should be unrelated since it repro with clean tree.

**Review by csyonghe — APPROVED** [review]
This is much more principled and looks like the right fix.

File: source/slang/slang-ir-spirv-legalize.cpp [hunk 1]
```diff
@@ -1844,9 +1836,11 @@ struct SPIRVLegalizationContext : public SourceEmitterBase
             case kIROp_PtrLit:
                 processPtrLit(inst);
                 break;
-            case kIROp_UnconditionalBranch:
-                processBranch(inst);
-                break;
+            // kIROp_UnconditionalBranch is handled in default case that only
```
Comment (jkwak-work) [inline source/slang/slang-ir-spirv-legalize.cpp:1839]: The location of this comment doesn't make sense after the unconditional IR case is removed. Probably better to have it around 'default' case.
