### PR TITLE
Fix default implement method in generic interface

### LINKED ISSUE #9202: Compiler crashes with signficant use of default implementations of generic functions
The exact cause of the crash is unclear, however in 1 attempt at Tensor implementations that made fairly extensive use of default function implementations, the compiler and language server both crash consistently.

repro is in slangpy repo: dev/ccummings/tensor-refactor-crash
run test_tensor.py:test_simple_copy

### PR DESCRIPTION
**Pull request by kaizhangNV**
Close #9202.

The root cause of this failure is that there is a specialize inst, where we provide a generic type to a witness type. generic 
```
%3 : %6
{
    witness_table_entry(%IWOTensorx5Fx5Fx5Fslangpyx5Fstore,
      specialize(specialize(%25, %T9, %D9), specialize(%4, %T9, %D9), %3))
}
```

%3 here in the specialize inst is to provide the subtypewitness, so it should not be a generic, otherwise this specialize is just invalid.

The reason for this problem is that in frontend, when we check the conformance of a struct, we will check all the inherianceDecl of a struct, and for each inherianceDecl we will form a subtypewitness. However, for the declRef field of the subtypewitness, we shouldn't use directDeclRef, because there won't be any substitution happens when the struct is a generic. So instead, we will form a GenericAppDeclRef if the type of the struct is a generic.

### CODE REVIEW

File: source/slang/slang-check-decl.cpp [hunk 1]
```diff
@@ -7627,6 +7628,16 @@ bool SemanticsVisitor::checkConformance(
             // (type constraints) represent additional requirements.
             return true;
         }
+        if (auto genericApp = as<GenericAppDeclRef>(declRef.declRefBase))
+        {
+            // When the sub type is generic, we can't just make a direct declref to inheritanceDecl
+            // because it won't be lowered to a concrete type. Instead, we need to form a
+            // GenericAppDeclRef to represent a concrete type.
+            declRefForSubTypeWitness = m_astBuilder->getGenericAppDeclRef(
```
Comment (csyonghe) [inline source/slang/slang-check-decl.cpp:7636]: should this be `m_astBuilder->getMemberDeclRef(declRef, inheritanceDecl)`?

Comment (kaizhangNV) [reply source/slang/slang-check-decl.cpp:7636]: it doesn't look like `getMemberDeclRef` handles the case if parentDecl is generic.
I tried it, and crash the core module compilation.

Comment (kaizhangNV) [reply source/slang/slang-check-decl.cpp:7636]: Do you think I should add that case in `getMemberDeclRef` and call it universally in this function?

Comment (kaizhangNV) [reply source/slang/slang-check-decl.cpp:7636]: Also, it doesn't handle the extensionDecl as well.

Comment (csyonghe) [reply source/slang/slang-check-decl.cpp:7636]: I see. I guess we could add a case in `getMemberDeclRef` that returns the same thing you constructed here.

**Review by csyonghe — APPROVED** [review]
