### PR TITLE
emit-spirv: handle IRVoidType in emitDebugTypeImpl

### LINKED ISSUE #9237: SPIR-V debug output: incorrect return type in DebugTypeFunction
# Issue Description
For functions returning void the `Result Type` operand of `DebugTypeFunction` is an unspecified nameless type. However, the NonSemantic.Shader.DebugInfo.100 spec says that "`Return Type` is a debug instruction that represents the type of return value of the function. If the function has no return value, this operand is `OpTypeVoid`."

# Reproducer Code
This is the minimal code that reproduces the problem:
```
[shader("compute")]
[numthreads(1, 1, 1)]
void Test()
{
}
```
Command line:
`slangc.exe -target spirv -fvk-use-entrypoint-name -O0 -g2 -stage compute -entry Test repro.slang`

# Expected Behavior
For the `Test` function that has no return value the `Return Type` operand of the corresponding `DebugTypeFunction` should be `OpTypeVoid`

# Actual Behavior
The `Result Type` operand of `DebugTypeFunction` is an unspecified nameless type. SPIR-V snippet only showing the relevant instructions:
`
         %15 = OpString ""
         %14 = OpExtInst %void %2 DebugTypeBasic %15 %uint_0 %uint_0 %uint_131072
         %18 = OpExtInst %void %2 DebugTypeFunction %uint_0 %14
         %19 = OpExtInst %void %2 DebugFunction %20 %18 %4 %uint_3 %uint_6 %10 %20 %uint_0 %uint_3
`

# Environment
 - slang-2025.23.2-windows-x86_64

### PR DESCRIPTION
**Pull request by zangold-nv**
This fixes a case where functions returning 'void' ended up being listed as returning a zero-sized unnamed type (instead of OpTypeVoid).

Fixes #9237

### CODE REVIEW

File: source/slang/slang-emit-spirv.cpp [hunk 1]
```diff
@@ -8798,7 +8798,11 @@ struct SPIRVEmitContext : public SourceEmitterBase, public SPIRVEmitSharedContex
         IRBuilder builder(type);
         if (IRFuncType* funcType = as<IRFuncType>(type))
         {
-            SpvInst* returnType = emitDebugType(funcType->getResultType());
+            SpvInst* returnType = ensureInst(m_voidType);
+            if (!as<IRVoidType>(funcType->getResultType()))
```
Comment (csyonghe) [inline source/slang/slang-emit-spirv.cpp:8802]: should this be handled as a parallel `if` case to line 8799? i.e.
```
if (IRFuncType* funcType = as<IRFuncType>(type))
{
   ...
}
else if (as<IRVoidType>(type))
{
     return ensureInst(m_voidType);
}

Comment (zangold-nv) [reply source/slang/slang-emit-spirv.cpp:8802]: I tried that initially, but it causes tests to fail during SPIR-V validation. Basically, we can't form a pointer with pointed-to type == OpTypeVoid, so we have to create the 0-size debugtype:

```
error: line 75: NonSemantic.Shader.DebugInfo.100 DebugTypePointer: expected operand Base Type is not a valid debug type
  %55 = OpExtInst %void %2 DebugTypePointer %void %uint_5349 %uint_131072
```

This is coming from a test with the following code:

```
// Test a pointer to a struct that has only one field and is an unsized array.
struct MeshStorage {
    uint64_t QuadData[];
};

//TEST_INPUT: set pStorage = ubuffer(data=[1 2 3 4 5 6 7 8],stride=4);
uniform MeshStorage* pStorage;
```

where globalParams->pStorage is being declared as a void pointer, like this:
```
%58 = OpString "pStorage"
%63 = OpString "GlobalParams_std140"
%55 = OpExtInst %void %2 DebugTypePointer %void %uint_5349 %uint_131072
%57 = OpExtInst %void %2 DebugTypeMember %58 %55 %4 %uint_13 %uint_22 %uint_0 %uint_64 %uint_0
%62 = OpExtInst %void %2 DebugTypeComposite %63 %uint_1 %4 %uint_0 %uint_0 %10 %63 %uint_64 %uint_131072 %57
```

... which seems like a separate bug, since it looks like it should just point to type MeshStorage. But, at least it illustrates the point that we can't return `m_voidType` when determining debugType for void pointers.

Comment (csyonghe) [reply source/slang/slang-emit-spirv.cpp:8802]: We have a pass that will eliminate the `MeshStorage` type to avoid limitations/problems with unsized arrays in structs. Because of the lowering, we can't form a pointer type to it. Looks like we should just handle the void* type and represent it as a uint* in debug type.
