### PR TITLE
Fix IR layout of 3-element vectors in cbuffers for -fvk-use-dx-layout

### LINKED ISSUE #6921: Results compiled with "-fvk-use-dx-layout" do not match DXC.
slangc Version: 2025.6.1

Description: When compiling SPIR-V using `slangc`, the struct layout does not match expectations. I have attached the test file and the commands used.

```hlsl
// DXC: dxc test.hlsl -T cs_6_6 -E Main -spirv -fvk-use-dx-layout -Fo test.dxc.spv
// Slang: slangc test.hlsl -profile sm_6_6 -stage compute -entry Main -target spirv -fvk-use-dx-layout -o test.slang.spv

struct Constants
{
    float3 Position;

    float3 Forward;

    float3 Right;

    float3 Up;

    float NearPlane;

    float FarPlane;

    float Fov;
};

[[vk::binding(0, 0)]]
ConstantBuffer<Constants> constants : register(b0, space0);

[[vk::binding(1, 0)]]
RWTexture2D<float4> output : register(u1, space0);

[numthreads(32, 32, 1)]
void Main(uint3 id: SV_DispatchThreadID)
{
    output[id.xy] = normalize(float4(constants.Forward, 1.0f));
}
```

Expected Result (DXC):
Image

Actual Result (Slang):
Image

### PR DESCRIPTION
**Pull request by jhelferty-nv**
Adhere better to the packing rules used by DXC with -fvk-use-dx-layout option.

The packing rules for D3D cbuffers are slightly different from how std140 and std430 handle packing, in particular around how they handle the alignment of vec3 types in structs. As an example, "struct { float a; float3 b; };" will get packed into 16 bytes in HLSL, while the std140 and std430 packing rules would align the float3 variable to an offset of 16. The front-end/AST already handled this correctly, but the IR layout code did not.

Also adds a documentation page for the GLSL target, which has some shortcomings relative to the SPIR-V target.

Fixes #6921.

### CODE REVIEW

**Comment by jhelferty-nv** [comment]
I think the SPIRV target is probably doing what it's supposed to at this point.

The GLSL target is the part that I'm still working my way through. In particular, would be good to get feedback on how best to handle what `checkConstantBufferRequiresScalarLayout()` is supposed to (but failing) to do. I don't really like this approach of iterating through the structs and re-checking the rules against std140 or std430. I think it might be better if I could apply a flag to the struct somehow in `slang-ir-layout.cpp`? It would be nice to get some guidance on whether that's the way to go, as well as how it might be accomplished.

Other issue is whether to just go ahead and promote everything that leaves a gap (vs std140/std430 rules) to either use `layout(scalar)` or the `GL_ARB_enhanced_layouts` extension (vs only doing it for stuff that needs scalar due to vec3 alignment). Forcing them to use those extensions would preserve the layout vs HLSL, but it might break things for any users relying on a 'broken' mapping of offsets from HLSL to GLSL. (I don't think I can justify adding padding variables in the IR for those without those features atm.)

File: source/slang/slang-ir-layout.cpp [hunk 1]
```diff
@@ -540,11 +547,21 @@ struct ConstantBufferLayoutRules : IRTypeLayoutRules
...
     {
-        IRIntegerValue countForAlignment = count;
+        // Align to the element size, and let adjustAlignmentForStructOffset handle the
+        // break at the 16-byte boundary.
+        IRIntegerValue countForAlignment = 1;
         return IRSizeAndAlignment(
             (int)(element.size * count),
             (int)(element.size * countForAlignment));
     }
+    virtual void adjustAlignmentForStructOffset(IRSizeAndAlignment& element, IRIntegerValue offset)
```
Comment (kaizhangNV) [inline source/slang/slang-ir-layout.cpp:557]: is `offset` the offset of the `element` in the struct?
The logic is not very easy to understand, can you make more comment to explain?

From my understand, what you are trying to do is that if the element is not cross the 16 byte boundary, do nothing. 
And if it's cross the boundary, aligned with 16. So it means that there will be padding after the last element?

Comment (kaizhangNV) [reply source/slang/slang-ir-layout.cpp:557]: I feel like this logic should be in the existing method `adjustOffsetForNextAggregateMember`.

File: tests/hlsl/cbuffer-16b-boundary-basic.slang [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+    float NearPlane;
+
+    // CHECK: OpMemberDecorate {{.*}} 7 Offset 68
+    float FarPlane;
+
+    // CHECK: OpMemberDecorate {{.*}} 8 Offset 72
+    vector<float16_t, 3> Half3Test;
+
+    // CHECK: OpMemberDecorate {{.*}} 9 Offset 80
+    float PackedAfterHalf3Test;
```
Comment (kaizhangNV) [inline tests/hlsl/cbuffer-16b-boundary-basic.slang:35]: I suggest you remove this variable, then see what happens, because next variable will cross the 16 byte boundary.

File: source/slang/slang-ir-layout.cpp (hunk 1 above)
Comment (jhelferty-nv) [reply source/slang/slang-ir-layout.cpp:557]: The problem with putting it in `adjustOffsetForNextAggregateMember` is that we need to know the size of the next member in order to know whether or not to adjust the offset, and we won't know that until we iterate to the next field.

For the case of `struct { float a; float3 b; }`, at the point where we call `adjustOffsetForNextAggregateMember` we only know the offset and alignment of `a`, so we don't know the size of `b` yet and thus don't know whether or not the offset should be adjusted. For example, if `b` is a `float4`, it needs to be adjusted, but if it's a `float3` it doesn't.

Hm, maybe you're suggesting I move `adjustOffsetForNextAggregateMember` up to where I've put `adjustAlignmentForStructOffset` and have it take the current element size as an additional argument. Let me give that a try.

File: source/slang/slang-ir-layout.cpp [hunk 3]
```diff
@@ -528,38 +538,55 @@ struct ConstantBufferLayoutRules : IRTypeLayoutRules
...
-    virtual IRSizeAndAlignment alignCompositeElement(IRSizeAndAlignment elementSize)
+    virtual IRIntegerValue adjustOffset(
+        IRIntegerValue offset,
+        IRIntegerValue elementSize,
+        IRType* lastFieldType,
+        IRIntegerValue lastFieldAlignment)
     {
-        return elementSize;
+        SLANG_UNUSED(elementSize);
+        if (as<IRMatrixType>(lastFieldType) || as<IRArrayTypeBase>(lastFieldType) ||
```
Comment (kaizhangNV) [inline source/slang/slang-ir-layout.cpp:579]: Why is this?
Whenever you add those special handling logic, probably need to think twice because it could break other things.
I see you add some container type here, but there are more container types other than just matrix/array/struct, e.g tuple, vector

**Comment by kaizhangNV** [comment]
You need to take care of the Falcor test failure, but address the comment first, I think they might be related.

File: source/slang/slang-ir-layout.cpp (hunk 3 above)
Comment (jhelferty-nv) [reply source/slang/slang-ir-layout.cpp:579]: This if statement is directly copying the logic that was at line 198 into the function instead of having it at the call site.

I'll take a second look.

Comment (jhelferty-nv) [reply source/slang/slang-ir-layout.cpp:579]: This `if` block adds the padding for `std140` and `std430`, mentioned in the packing rules for GL. Refer to [glspec 4.6 (core)](https://registry.khronos.org/OpenGL/specs/gl/glspec46.core.pdf), section 7.6.2.2 Standard Uniform Block Layout. Numbered rules 4-10 require padding after these struct member types. This is separate from `alignCompositeElement` which handles the 16 byte alignment that's needed for `std140` but not for `std430`. (That alignment needs to be applied to vector types as well as matrix/array/struct.)

So `adjustOffset` is doing different things for different targets. For the `std140` and `std430` buffers, `adjustOffset` is ensuring that the padding rule is being followed. For `constant` buffers, `adjustOffset` is making sure that we don't (as Vulkan puts it) "straddle" a 16 byte boundary.

**Comment by jhelferty-nv** [comment]
I think the falcor failure might be spurious? Updating the branch to trigger another validation run.

File: source/slang/slang-ir-layout.h [hunk 4]
```diff
@@ -27,6 +27,7 @@ struct CompilerOptionSet;
 /// Align `value` to the next multiple of `alignment`, which must be a power of two.
 inline IRIntegerValue align(IRIntegerValue value, int alignment)
 {
+    // SLANG_ASSERT((alignment != 0U) && ((alignment - 1U) & alignment) == 0U);
```
Comment (kaizhangNV) [inline source/slang/slang-ir-layout.h]: can you please remove this if this is unused?

**Review by kaizhangNV — DISMISSED** [review]
LGTM.

File: source/slang/slang-ir-layout.h (hunk 4 above)
Comment (jhelferty-nv) [reply source/slang/slang-ir-layout.h]: Removed. (This assert checks the power of two assumption for the alignment value that was broken previously, but it's probably not worth the runtime cost to keep.)

**Comment by jhelferty-nv** [comment]
Just to add some commentary breadcrumbs, the patch fixes the SPIR-V target, but the GLSL target will still be broken for this case. GLSL uses a base alignment of 4N for a 3 component vector and the final value becomes padding, so it's not possible to directly translate this packing from D3D to GLSL. Fixing GLSL target for the general case would likely involve using a 4-element vector and then some reinterpret casts to extract the elements.

Vulkan has laxer rules on offsets and padding when the `scalarBlockLayout` feature is enabled, so it doesn't have these problems.

Regarding the `packoffset` interaction, which I tried to fix at one point, I ended up backing out my changes from the final patch. Fixing it would require changes to the frontend/AST processing to match, and it's not really the target of this change. I'll open a separate bug.

**Review by kaizhangNV — APPROVED** [review]

File: tests/expected-failure.txt [hunk 5]
```diff
@@ -5,3 +5,5 @@ tests/language-feature/saturated-cooperation/fuse.slang (vk)
 tests/bugs/byte-address-buffer-interlocked-add-f32.slang (vk)
 tests/ir/loop-unroll-0.slang.1 (vk)
 tests/hlsl-intrinsic/texture/float-atomics.slang (vk)
+tests/hlsl/cbuffer-float3-offsets-aligned.slang.2 (vk)
```
Comment (csyonghe) [inline tests/expected-failure.txt:8]: Why do we add a test that is expected to fail? Any plan to fix this?

File: tests/hlsl/cbuffer-float3-offsets-aligned.slang [hunk 6]
```diff
@@ -0,0 +1,115 @@
+//TEST:SIMPLE(filecheck=SPIRV): -target spirv -profile cs_6_2 -entry computeMain -line-directive-mode none -fvk-use-dx-layout
+//TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=BUFFER):-slang -compute -dx12 -use-dxil -profile cs_6_2 -Xslang... -Xdxc -fvk-use-dx-layout -Xdxc -enable-16bit-types -X. -output-using-type
+//TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=BUFFER):-slang -compute -vk -profile cs_6_2 -Xslang... -fvk-use-dx-layout -X. -output-using-type
```
Comment (csyonghe) [inline tests/hlsl/cbuffer-float3-offsets-aligned.slang:3]: If this test is failing under `-emit-spirv-via-glsl` path, add a `-emit-spirv-directly` option here to prevent the glsl test failure.

File: tests/expected-failure.txt (hunk 5 above)
Comment (jhelferty-nv) [reply tests/expected-failure.txt:8]: These succeed on Vulkan using the SPIRV target, but do not succeed on Vulkan using the GLSL target. Kai told me to add the tests here to disable error reporting for Vulkan with GLSL target. It sounds like that's not correct; will fix.

File: tests/hlsl/cbuffer-float3-offsets-aligned.slang (hunk 6 above)
Comment (jhelferty-nv) [reply tests/hlsl/cbuffer-float3-offsets-aligned.slang:3]: Thanks, will do.
