### PR TITLE
Fix a bug on default initialization of interface typed value.

### LINKED ISSUE #3831: Initializing interface type with empty initializer results in invalid HLSL code
When you have a interface type `IHitInfo` and try to empty initialize it directly as `IHitInfo hit = {};` or indirectly by storing it in `struct PathState` and then empty initialize that `PathState path = {}`, Slang generates an invalid HLSL code dxc errors out.

Ideally Slang compiler would report an error, to make it easier to address.

### PR DESCRIPTION
**Pull request by csyonghe**
`default(IFoo)` should lower into a `DefaultConstruct : IFoo` inst instead of `MakeStruct : IFoo` for our passes to handle it correctly to produce valid HLSL output.

Closes #3831.

### CODE REVIEW

File: source/slang/slang-lower-to-ir.cpp [hunk 1]
```diff
@@ -4415,8 +4415,12 @@ struct ExprLoweringVisitorBase : public ExprVisitor<Derived, LoweredValInfo>
             }
             else if (auto aggTypeDeclRef = declRef.as<AggTypeDecl>())
             {
-                List<IRInst*> args;
+                if (aggTypeDeclRef.as<InterfaceDecl>())
+                {
+                    return LoweredValInfo::simple(getBuilder()->emitDefaultConstruct(irType));
+                }
```
Comment (jkwak-work) [inline source/slang/slang-lower-to-ir.cpp:4421]: I have a question here.
Can we cast to `InterfaceDecl` before casting to `AggTypeDecl`?
Or does it have to check `AggTypeDecl` first for a reason?

In other words, can this be changed to the following?
```
            else if (aggTypeDeclRef.as<InterfaceDecl>())
            {
                return LoweredValInfo::simple(getBuilder()->emitDefaultConstruct(irType));
            }
            else if (auto aggTypeDeclRef = declRef.as<AggTypeDecl>())
            {
```

**Review by jkwak-work — DISMISSED** [review]
Looks good to me.

File: source/slang/slang-lower-to-ir.cpp (hunk 1 above)
Comment (csyonghe) [reply source/slang/slang-lower-to-ir.cpp]: You are right, this is definitely cleaner. changed.
