### PR TITLE
Fix #9051: Add atomicAdd wrapper for signed int64_t on CUDA

### LINKED ISSUE #9051: Atomic operations with int64_t cause CUDA compilation error
# Issue Description

Using atomic operations with `int64_t` results in CUDA compilation errors.  That's because CUDA does not define atomic operations for signed 64-bit integers, it only provides the unsigned ones.

# Reproducer Code

```
# repro.slang
[CUDAKernel]
[AutoPyBindCUDA]
void atomic_add_bug(TensorView<int64_t> buffer) {
    int64_t old_value;
    buffer.InterlockedAdd(0, 1, old_value);
}

# repro.py
import slangtorch
import torch

slang_module = slangtorch.loadModule("repro.slang")

buffer = torch.zeros((1,), device='cuda', dtype=torch.int64)
slang_module.atomic_add_bug(buffer=buffer).launchRaw(blockSize=(1, 1, 1), gridSize=(1, 1, 1))
print(buffer)
```

# Expected Behavior

We expect this code to compile and run fine.

# Actual Behavior

We get a CUDA compilation error:

```
repro_cuda.cu
repro.slang(5): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (longlong *, long long)
      *((&old_value_0)) = atomicAdd((buffer_0).data_ptr_at<longlong>((0U)), (1LL));
                          ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(647): note #3326-D: function "atomicAdd(ulonglong4 *, ulonglong4)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) ulonglong4 atomicAdd(ulonglong4* address, ulonglong4 val) { ulonglong4 result; for (int i = 0; i < 4; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; }
                                           ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(646): note #3326-D: function "atomicAdd(ulonglong3 *, ulonglong3)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) ulonglong3 atomicAdd(ulonglong3* address, ulonglong3 val) { ulonglong3 result; for (int i = 0; i < 3; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; }
                                           ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(645): note #3326-D: function "atomicAdd(ulonglong2 *, ulonglong2)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) ulonglong2 atomicAdd(ulonglong2* address, ulonglong2 val) { ulonglong2 result; for (int i = 0; i < 2; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; }
                                           ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(644): note #3326-D: function "atomicAdd(uint4 *, uint4)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) uint4 atomicAdd(uint4* address, uint4 val) { uint4 result; for (int i = 0; i < 4; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; }
                                      ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(643): note #3326-D: function "atomicAdd(uint3 *, uint3)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) uint3 atomicAdd(uint3* address, uint3 val) { uint3 result; for (int i = 0; i < 3; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; }
                                      ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(642): note #3326-D: function "atomicAdd(uint2 *, uint2)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) uint2 atomicAdd(uint2* address, uint2 val) { uint2 result; for (int i = 0; i < 2; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; }
                                      ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(641): note #3326-D: function "atomicAdd(int4 *, int4)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) int4 atomicAdd(int4* address, int4 val) { int4 result; for (int i = 0; i < 4; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; } 
                                     ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(640): note #3326-D: function "atomicAdd(int3 *, int3)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) int3 atomicAdd(int3* address, int3 val) { int3 result; for (int i = 0; i < 3; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; } 
                                     ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(639): note #3326-D: function "atomicAdd(int2 *, int2)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) int2 atomicAdd(int2* address, int2 val) { int2 result; for (int i = 0; i < 2; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; } 
                                     ^
C:\Path\To\Repro\.slangtorch_cache\repro\b9c103f6b206b8e5\repro_cuda.cu(638): note #3326-D: function "atomicAdd(float3 *, float3)" does not match because argument #1 does not match parameter
  inline __declspec(__device__) float3 atomicAdd(float3* address, float3 val) { float3 result; for (int i = 0; i < 3; i++) *_slang_vector_get_element_ptr(&result, i) = atomicAdd(_slang_vector_get_element_ptr(address, i), _slang_vector_get_element(val, i)); return result; }
                                       ^
C:\packman-repo\chk\cuda\12.8.0-dev.7500+main.770c95ea7bf2b0b7f270fd7f69669751263d04aa-windows-x86_64-release\include\cuda_fp16.hpp(3447): note #3326-D: function "atomicAdd(__half *, __half)" does not match because argument #1 does not match parameter
  static __declspec(__device__) __inline  __half atomicAdd(__half *const address, const __half val) {
                                                 ^
C:\packman-repo\chk\cuda\12.8.0-dev.7500+main.770c95ea7bf2b0b7f270fd7f69669751263d04aa-windows-x86_64-release\include\cuda_fp16.hpp(3426): note #3326-D: function "atomicAdd(__half2 *, __half2)" does not match because argument #1 does not match parameter
  static __declspec(__device__) __inline  __half2 atomicAdd(__half2 *const address, const __half2 val) {
                                                  ^
C:\packman-repo\chk\cuda\12.8.0-dev.7500+main.770c95ea7bf2b0b7f270fd7f69669751263d04aa-windows-x86_64-release\include\crt\sm_90_rt.h(112): note #3326-D: function "atomicAdd(float4 *, float4)" does not match because argument #1 does not match parameter
  static __declspec(__device__) __inline float4 atomicAdd(float4 *__address, float4 val) { }
                                                ^
C:\packman-repo\chk\cuda\12.8.0-dev.7500+main.770c95ea7bf2b0b7f270fd7f69669751263d04aa-windows-x86_64-release\include\crt\sm_90_rt.h(109): note #3326-D: function "atomicAdd(float2 *, float2)" does not match because argument #1 does not match parameter
  static __declspec(__device__) __inline float2 atomicAdd(float2 *__address, float2 val) { }
                                                ^
C:\packman-repo\chk\cuda\12.8.0-dev.7500+main.770c95ea7bf2b0b7f270fd7f69669751263d04aa-windows-x86_64-release\include\sm_60_atomic_functions.h(93): note #3326-D: function "atomicAdd(double *, double)" does not match because argument #1 does not match parameter      
  static __inline __declspec(__device__) double atomicAdd(double *address, double val) { }
                                                ^
C:\packman-repo\chk\cuda\12.8.0-dev.7500+main.770c95ea7bf2b0b7f270fd7f69669751263d04aa-windows-x86_64-release\include\sm_20_atomic_functions.h(88): note #3326-D: function "atomicAdd(float *, float)" does not match because argument #1 does not match parameter        
  static __inline __declspec(__device__) float atomicAdd(float *address, float val) { }
                                               ^
C:\packman-repo\chk\cuda\12.8.0-dev.7500+main.770c95ea7bf2b0b7f270fd7f69669751263d04aa-windows-x86_64-release\include\device_atomic_functions.h(169): note #3326-D: function "atomicAdd(unsigned long long *, unsigned long long)" does not match because argument #1 does not match parameter
  static __inline __declspec(__device__) unsigned long long int atomicAdd(unsigned long long int *address, unsigned long long int val) { }
                                                                ^
C:\packman-repo\chk\cuda\12.8.0-dev.7500+main.770c95ea7bf2b0b7f270fd7f69669751263d04aa-windows-x86_64-release\include\device_atomic_functions.h(91): note #3326-D: function "atomicAdd(unsigned int *, unsigned int)" does not match because argument #1 does not match parameter
  static __inline __declspec(__device__) unsigned int atomicAdd(unsigned int *address, unsigned int val) { }
                                                      ^
C:\packman-repo\chk\cuda\12.8.0-dev.7500+main.770c95ea7bf2b0b7f270fd7f69669751263d04aa-windows-x86_64-release\include\device_atomic_functions.h(89): note #3326-D: function "atomicAdd(int *, int)" does not match because argument #1 does not match parameter
  static __inline __declspec(__device__) int atomicAdd(int *address, int val) { }
                                             ^
```

# Environment
 - Slang Version: 2025.21.2
 - Windows 11

# Additional context

This issue seems to already have been encountered with different atomic operations.  In `slang_cuda_prelude.h`:

https://github.com/shader-slang/slang/blob/ce376e1ef48781ae27b09f983f798b1b8d1988ca/prelude/slang-cuda-prelude.h#L2247

we can read:

```
// Signed 64-bit atomic wrappers
// CUDA only supports unsigned long long atomics, so we cast signed to unsigned
__device__ __forceinline__ long long atomicExch(long long* address, long long val)
{
    return (long long)atomicExch((unsigned long long*)address, (unsigned long long)val);
}
```

So it would be a matter of adding something similar for `atomicAdd`.

As a workaround, we currently can do:

```
// We mark this function as [CudaDeviceExport] to make sure it's taken into account by
// the Slang compiler even if it's not called.
[CudaDeviceExport]
void setup_atomic_add()
{
// CUDA atomicAdd is not supported for int64_t.
// Slang is supposed to define those, it does for some operations but not for atomicAdd.
// This is might break when the bug is fixed in Slang.
__requirePrelude(R"(
__device__ long long atomicAdd(long long* address, long long val)
{
    return (long long)atomicAdd((unsigned long long*)address, (unsigned long long)val);
}
)");
}
```

### PR DESCRIPTION
**Pull request by szihs**
CUDA only provides atomicAdd for unsigned long long, not signed.

### CODE REVIEW

File: prelude/slang-cuda-prelude.h [hunk 1]
```diff
@@ -2245,19 +2245,25 @@ struct ByteAddressBuffer
...
-    return (long long)atomicCAS(
+    return (longlong)atomicCAS(
         (unsigned long long*)address,
         (unsigned long long)compare,
         (unsigned long long)val);
 }
 
+__device__ __forceinline__ longlong atomicAdd(longlong* address, longlong val)
+{
+    return (longlong)atomicAdd((unsigned long long*)address, (unsigned long long)val);
```
Comment (jkwak-work) [inline prelude/slang-cuda-prelude.h:2264]: Wouldn't it make sense to use `ulonglong`?
https://github.com/shader-slang/slang/blob/938e51ee9ad6a1f82b75a7b8407cdfb20ad1bcfd/prelude/slang-cuda-prelude.h#L286-L287
