### PR TITLE
Fix the erroneous logic of determining whether or not to emit DepthReplacing.

### LINKED ISSUE #3884: Do not use `DepthReplacing` execution mode when the fragment shader is not modifying depth.
Helps improves performance.

### PR DESCRIPTION
**Pull request by csyonghe**
Closes #3884.

### CODE REVIEW

File: source/slang/slang-emit-spirv.cpp [hunk 1]
```diff
@@ -2960,24 +2961,19 @@ struct SPIRVEmitContext
...
+                mode = thisMode;
+            else if (mode != thisMode)
             {
                 needDepthReplacingMode = true;
-                if (mode == SpvExecutionModeMax)
-                    mode = thisMode;
-                else if (mode != thisMode)
-                    mode = SpvExecutionModeDepthReplacing;
+                mode = SpvExecutionModeDepthReplacing;
                 break;
```
Comment (ArielG-NV) [inline source/slang/slang-emit-spirv.cpp:2971]: Does the code here intentionally not `break;` at `if (mode == SpvExecutionModeMax)`?

Comment (csyonghe) [reply source/slang/slang-emit-spirv.cpp:2971]: No we can't break because the goal here is to find an evidence that we need DepthReplacing. And we don't know we don't need it unless we have examined every globalInst.

File: source/slang/slang-emit-spirv.cpp [hunk 2]
```diff
@@ -2960,24 +2961,19 @@ struct SPIRVEmitContext
...
         }
         if (!needDepthReplacingMode)
             return;
-        emitOpExecutionMode(getSection(SpvLogicalSectionID::ExecutionModes),
-            nullptr,
-            entryPoint,
-            SpvExecutionModeDepthReplacing);
-        if (mode != SpvExecutionModeDepthReplacing &&
-            mode != SpvExecutionModeMax)
+        if (mode != SpvExecutionModeMax)
```
Comment (ArielG-NV) [inline source/slang/slang-emit-spirv.cpp:2976]:
```suggestion
        if (mode == SpvExecutionModeMax)
            return;
```
purely a syntax candy suggestion: removes need for the indentation & braces below

**Review by ArielG-NV — DISMISSED** [review]
Everything looks good 👍

**Review by ArielG-NV — APPROVED** [review]

**Comment by csyonghe** [comment]
Thanks for the review!
