### PR TITLE
Fix GLSL emit logic for select expr

### LINKED ISSUE #892: Vector comparison returns wrong type
Vector comparison operators such as `operator ==(float3, float3)` should return `bool3`, which shouldn't be allowed directly as `if` condition or in branching(`x?y:z`) expressions.

Currently Slang does not issue any diagnostic message when source code does this, and generates invalid HLSL/GLSL that fails downstream compilation.

### PR DESCRIPTION
**Pull request by csyonghe**
Add special case emit logic for select expression (`x?y:z`) for GLSL when `x` is a `bool` vector. In this case, we should generate a call to `mix` instead of a select expression since GLSL does not support a vector-typed condition expression.

Fixes #892

### CODE REVIEW

File: source/slang/emit.cpp [hunk 1]
```diff
@@ -3959,14 +3959,29 @@ struct EmitVisitor
...
-                auto prec = kEOp_Conditional;
-                needClose = maybeEmitParens(outerPrec, prec);
-
-                emitIROperand(ctx, inst->getOperand(0), mode, leftSide(outerPrec, prec));
-                emit(" ? ");
-                emitIROperand(ctx, inst->getOperand(1), mode, prec);
-                emit(" : ");
-                emitIROperand(ctx, inst->getOperand(2), mode, rightSide(prec, outerPrec));
+                if (getTarget(ctx) == CodeGenTarget::GLSL &&
+                    inst->getOperand(0)->getDataType()->op != kIROp_BoolType)
```
Comment (tfoleyNV) [inline source/slang/emit.cpp]: I almost commented that we should use `mix` in all cases, even for scalars, since `?:` in GLSL is short-circuiting and `kIROp_Select` is not. Then I realized that the logic here in `emit.cpp` will never fold an operation with side effects in as a sub-expression, so that is a non-issue.

That is maybe a subtle point and worth documenting, but I agree with the design choice here to favor `?:` for the scalar case just to leave people with code more like what they wrote.

There is a long-term question for Slang of whether we eventually want to switch to having `?:`, `&&`, and `||` short-circuit and, if so, how to transition to those semantics without too much pain for existing users who might accidentally rely on the fact that they don't short-circuit today.
