### PR TITLE
Fix spirv debug info for pointer types.

### LINKED ISSUE #5317: Adding Function/Property to Struct With Pointer Results in Use of `SPV_KHR_relaxed_extended_instruction`
Premise:

`SPV_KHR_relaxed_extended_instruction` is _really_ poorly supported out there in the world, having just 5% total support per vulkaninfo (1% on linux). So I'm trying to avoid the use of it.

If I have the following slang shader:

```csharp
struct T
{
    uint inner;
}

struct Problem
{
    // Must be used by the shader in question.
	//
    // EDIT: May be a property or a function
    property myprop : uint
    {
        get {
            return 0;
        }
    }

    // Must be a pointer to a struct.
    //
    // Must exist within the struct. Does not need to be used.
    T *some_bda_ptr;
}

uniform Problem probs;

[shader("compute")]
float4 main()
    : TARGET0
{
    return float4(probs.myprop);
}
```

`slangc test.slang -g -o test.spv-asm` generates the following spirv:

```spvasm
; SPIR-V
; Version: 1.5
; Generator: Khronos; 40
; Bound: 126
; Schema: 0
               OpCapability VariablePointers
               OpCapability PhysicalStorageBufferAddresses
               OpCapability Shader
               OpExtension "SPV_KHR_non_semantic_info"
               OpExtension "SPV_KHR_variable_pointers"
               OpExtension "SPV_KHR_physical_storage_buffer"
               OpExtension "SPV_KHR_relaxed_extended_instruction"
          %2 = OpExtInstImport "NonSemantic.Shader.DebugInfo.100"
               OpMemoryModel PhysicalStorageBuffer64 GLSL450
               OpEntryPoint GLCompute %main "main" %entryPointParam_main %globalParams
               OpExecutionMode %main LocalSize 1 1 1
          %1 = OpString "struct T

{

    uint inner;

}



struct Problem

{

    // Must be used by the shader in question.

    //

    // EDIT: May be a property or a function

    property myprop : uint

    {

        get {

            return 0;

        }

    }



    // Must be a pointer to a struct.

    //

    // Must exist within the struct. Does not need to be used.

    T *some_bda_ptr;

}



uniform Problem probs;



[shader(\"compute\")]

float4 main()

    : TARGET0

{

    return float4(probs.myprop);

}

"
          %5 = OpString "C:\\Users\\conno\\Programming\\client\\test.slang"
               OpSource Slang 1
         %17 = OpString "main"
         %22 = OpString "slangc"
         %23 = OpString "-target spirv  -I \"C:\\VulkanSDK\\1.3.296.0\\Bin\" -matrix-layout-column-major -stage compute -entry main -g2"
         %56 = OpString "Problem.myprop.get"
         %62 = OpString "Problem"
         %69 = OpString "some_bda_ptr"
         %72 = OpString "this"
               OpName %Problem_std140 "Problem_std140"
               OpMemberName %Problem_std140 0 "some_bda_ptr"
               OpName %GlobalParams_std140 "GlobalParams_std140"
               OpMemberName %GlobalParams_std140 0 "probs"
               OpName %globalParams "globalParams"
               OpName %Problem "Problem"
               OpMemberName %Problem 0 "some_bda_ptr"
               OpName %this "this"
               OpName %entryPointParam_main "entryPointParam_main"
               OpName %main "main"
               OpName %T_natural "T_natural"
               OpMemberName %T_natural 0 "inner"
               OpDecorate %_ptr_PhysicalStorageBuffer_T_natural ArrayStride 4
               OpMemberDecorate %Problem_std140 0 Offset 0
               OpDecorate %GlobalParams_std140 Block
               OpMemberDecorate %GlobalParams_std140 0 Offset 0
               OpDecorate %globalParams Binding 0
               OpDecorate %globalParams DescriptorSet 0
               OpMemberDecorate %Problem 0 Offset 0
               OpDecorate %entryPointParam_main Location 0
               OpMemberDecorate %T_natural 0 Offset 0
       %void = OpTypeVoid
       %uint = OpTypeInt 32 0
    %uint_11 = OpConstant %uint 11
     %uint_5 = OpConstant %uint 5
   %uint_100 = OpConstant %uint 100
         %12 = OpTypeFunction %void
     %uint_0 = OpConstant %uint 0
    %uint_27 = OpConstant %uint 27
     %uint_8 = OpConstant %uint 8
    %uint_30 = OpConstant %uint 30
     %uint_6 = OpConstant %uint 6
               OpTypeForwardPointer %_ptr_PhysicalStorageBuffer_T_natural PhysicalStorageBuffer
%Problem_std140 = OpTypeStruct %_ptr_PhysicalStorageBuffer_T_natural
%GlobalParams_std140 = OpTypeStruct %Problem_std140
%_ptr_Uniform_GlobalParams_std140 = OpTypePointer Uniform %GlobalParams_std140
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
%_ptr_Uniform_Problem_std140 = OpTypePointer Uniform %Problem_std140
    %Problem = OpTypeStruct %_ptr_PhysicalStorageBuffer_T_natural
         %43 = OpTypeFunction %Problem %Problem_std140
         %51 = OpTypeFunction %uint %Problem
    %uint_13 = OpConstant %uint 13
     %uint_9 = OpConstant %uint 9
     %uint_1 = OpConstant %uint 1
    %uint_64 = OpConstant %uint 64
%uint_131072 = OpConstant %uint 131072
  %uint_5349 = OpConstant %uint 5349
    %uint_14 = OpConstant %uint 14
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
  %T_natural = OpTypeStruct %uint
%_ptr_PhysicalStorageBuffer_T_natural = OpTypePointer PhysicalStorageBuffer %T_natural
%globalParams = OpVariable %_ptr_Uniform_GlobalParams_std140 Uniform
%entryPointParam_main = OpVariable %_ptr_Output_v4float Output
%_ptr_Function_Problem = OpTypePointer Function %Problem
%_ptr_Function_uint = OpTypePointer Function %uint
%_ptr_Function__ptr_PhysicalStorageBuffer_T_natural = OpTypePointer Function %_ptr_PhysicalStorageBuffer_T_natural
         %73 = OpExtInst %void %2 DebugExpression
          %4 = OpExtInst %void %2 DebugSource %5 %1
         %10 = OpExtInst %void %2 DebugCompilationUnit %uint_100 %uint_5 %4 %uint_11
         %14 = OpExtInst %void %2 DebugTypeFunction %uint_0 %void
         %16 = OpExtInst %void %2 DebugFunction %17 %14 %4 %uint_27 %uint_8 %10 %17 %uint_0 %uint_27
         %21 = OpExtInst %void %2 DebugEntryPoint %16 %10 %22 %23
         %54 = OpExtInst %void %2 DebugTypeFunction %uint_0 %void
         %55 = OpExtInst %void %2 DebugFunction %56 %54 %4 %uint_13 %uint_9 %10 %56 %uint_0 %uint_13
         %61 = OpExtInstWithForwardRefsKHR %void %2 DebugTypeComposite %62 %uint_1 %4 %uint_6 %uint_8 %10 %62 %uint_64 %uint_131072 %68
         %66 = OpExtInst %void %2 DebugTypePointer %61 %uint_5349 %uint_131072
         %68 = OpExtInst %void %2 DebugTypeMember %69 %66 %4 %uint_6 %uint_8 %uint_0 %uint_64 %uint_0
         %70 = OpExtInst %void %2 DebugTypeComposite %62 %uint_1 %4 %uint_6 %uint_8 %10 %62 %uint_64 %uint_131072 %68
       %this = OpExtInst %void %2 DebugLocalVariable %72 %70 %4 %uint_13 %uint_9 %55 %uint_0 %uint_0
        %101 = OpExtInst %void %2 DebugInlinedAt %uint_30 %16
        %108 = OpExtInst %void %2 DebugInlinedAt %uint_30 %16
       %main = OpFunction %void None %12
         %13 = OpLabel
        %112 = OpVariable %_ptr_Function__ptr_PhysicalStorageBuffer_T_natural Function
        %104 = OpVariable %_ptr_Function_uint Function
         %20 = OpExtInst %void %2 DebugFunctionDefinition %16 %main
        %118 = OpExtInst %void %2 DebugScope %16
         %25 = OpExtInst %void %2 DebugLine %4 %uint_30 %uint_30 %uint_5 %uint_6
         %38 = OpAccessChain %_ptr_Uniform_Problem_std140 %globalParams %int_0
         %39 = OpLoad %Problem_std140 %38
        %119 = OpExtInst %void %2 DebugNoLine
        %120 = OpExtInst %void %2 DebugNoScope
         %99 = OpCompositeExtract %_ptr_PhysicalStorageBuffer_T_natural %39 0
        %100 = OpCompositeConstruct %Problem %99
               OpStore %112 %99
        %121 = OpExtInst %void %2 DebugScope %16
        %115 = OpExtInst %void %2 DebugLine %4 %uint_30 %uint_30 %uint_5 %uint_6
        %114 = OpLoad %_ptr_PhysicalStorageBuffer_T_natural %112
        %116 = OpCompositeConstruct %Problem %114
        %122 = OpExtInst %void %2 DebugNoLine
        %123 = OpExtInst %void %2 DebugScope %55 %108
        %107 = OpExtInst %void %2 DebugValue %this %116 %73
        %109 = OpExtInst %void %2 DebugLine %4 %uint_14 %uint_14 %uint_13 %uint_14
               OpStore %104 %uint_0
        %124 = OpExtInst %void %2 DebugScope %16
        %110 = OpExtInst %void %2 DebugLine %4 %uint_30 %uint_30 %uint_5 %uint_6
         %49 = OpLoad %uint %104
         %80 = OpConvertUToF %float %49
         %82 = OpCompositeConstruct %v4float %80 %80 %80 %80
               OpStore %entryPointParam_main %82
               OpReturn
        %125 = OpExtInst %void %2 DebugNoScope
               OpFunctionEnd
```

This includes a use of `OpExtInstWithForwardRefsKHR`, which is causing the extension to be added.

If I:
- Make the pointer point to a uint,
- Remove the use of the property.
- Make the `T*` into a `T`

The instruction and the extension go away. I don't know why this is being generated, but it would be a real boon to the usability of slang if this extension could be omitted.

If for some reason it's impossible to codegen around it, a flag to disable (or enable) its use would also be antiquate.

Thanks for this very useful language!

### PR DESCRIPTION
**Pull request by csyonghe**
Closes #5317.

### CODE REVIEW

File: source/slang/slang-emit-spirv.cpp [hunk 1]
```diff
@@ -6453,35 +6457,21 @@ struct SPIRVEmitContext
...
-                return emitOpDebugTypePointer(
-                    getSection(SpvLogicalSectionID::ConstantsAndTypes),
-                    nullptr,
-                    m_voidType,
-                    getNonSemanticDebugInfoExtInst(),
-                    debugBaseType,
-                    builder.getIntValue(builder.getUIntType(), storageClass),
-                    builder.getIntValue(builder.getUIntType(), kUnknownPhysicalLayout));
-            }
+            // If the base type of the pointer is basic types,
```
Comment (jkwak-work) [inline source/slang/slang-emit-spirv.cpp:6461]: I think this comment should be removed, because the "if" condition it was referring to is removed.

**Review by jkwak-work — APPROVED** [review]
Looks good to me
