### PR TITLE
Emit errors when seeing a matrix with row/col count of 1

### LINKED ISSUE #5987: Invalid SPIR-V generation for outer product mul
```
#version 460

struct TYPE_bindings_FragmentShaderOutputsExample {
    vector<float32_t, 4> m_color_0;
    vector<float32_t, 4> m_color_1;
};

layout (location = 0) in vector<float32_t, 2> BINDING_bindings_FragmentShaderInputsExample_texcoord;
layout (location = 0) out vector<float32_t, 4> BINDING_bindings_FragmentShaderOutputsExample_color_0;
layout (location = 1) out vector<float32_t, 4> BINDING_bindings_FragmentShaderOutputsExample_color_1;

[shader("fragment")] void main()
{
    matrix<float32_t, 4, 1> TEMP_3 = matrix<float32_t, 4, 1>(0);
    matrix<float32_t, 4, 1> r1_4 = TEMP_3;
    vector<float32_t, 4> TEMP_5 = vector<float32_t, 4>(0);
    vector<float32_t, 4> c1_6 = TEMP_5;
    matrix<float32_t, 1, 4> TEMP_7 = { c1_6[0], c1_6[1], c1_6[2], c1_6[3] };
    matrix<float32_t, 4, 4> TEMP_8 = mul(r1_4, TEMP_7);
    matrix<float32_t, 4, 4> m1_9 = TEMP_8;
    vector<float32_t, 4> TEMP_11 = vector<float32_t, 4>((m1_9[0][0]));
    vector<float32_t, 4> TEMP_12 = TEMP_11;
    vector<float32_t, 4> TEMP_13 = vector<float32_t, 4>(0);
    vector<float32_t, 4> TEMP_14 = TEMP_13;
    TYPE_bindings_FragmentShaderOutputsExample TEMP_15 = TYPE_bindings_FragmentShaderOutputsExample(TEMP_12, TEMP_14);
    TYPE_bindings_FragmentShaderOutputsExample TEMP_16 = TEMP_15;
    BINDING_bindings_FragmentShaderOutputsExample_color_0 = TEMP_16.m_color_0;
    BINDING_bindings_FragmentShaderOutputsExample_color_1 = TEMP_16.m_color_1;
    return;
}
```
```
slangc test.slang -target spirv -o test.spv
spirv-val test.spv
```
->
```
error: line 17: Matrix types can only be parameterized as having only 2, 3, or 4 columns.
  %mat1v4float = OpTypeMatrix %v4float 1
```

Specifically I believe this originates from this outer product mul (mat4x1 * mat1x4): `matrix<float32_t, 4, 4> TEMP_8 = mul(r1_4, TEMP_7);`

### PR DESCRIPTION
**Pull request by aleino-nv**
Such matrices aren't well supported by our targets, and we currently don't transform such types to supported ones.
Therefore, generate an error rather than outputting invalid target code.

This closes #5987.

### CODE REVIEW

File: source/slang/slang-check-decl.cpp [hunk 1]
```diff
@@ -11876,6 +11876,20 @@ void SemanticsDeclAttributesVisitor::checkVarDeclCommon(VarDeclBase* varDecl)
             getSink()->diagnose(varDecl, Diagnostics::pushOrSpecializationConstantCannotBeStatic);
         }
     }
+
+    if (auto matrixType = as<MatrixExpressionType>(varDecl->getType()))
```
Comment (aleino-nv) [inline source/slang/slang-check-decl.cpp:11880]: I [found out](https://github.com/shader-slang/slang/issues/5987#issuecomment-2579819116) that this is not quite the right place for this check.

Comment (csyonghe) [reply source/slang/slang-check-decl.cpp:11880]: Given that we eventually still plan to implement the support, I am fine with just add a last minute error reporting from the backend before emitting target code.

**Comment by aleino-nv** [comment]
I added a `-skip-matrix-dimension-validation` option for `slangc`, because we have some HLSL tests that use 1-matrices here:
https://github.com/shader-slang/slang/blob/master/tests/bugs/gh-4395.slang

However I still need to figure out how to pass this option to `slang` via the test framework.

**Comment by aleino-nv** [comment]
> I added a `-skip-matrix-dimension-validation` option for `slangc`, because we have some HLSL tests that use 1-matrices here: https://github.com/shader-slang/slang/blob/master/tests/bugs/gh-4395.slang
> 
> However I still need to figure out how to pass this option to `slang` via the test framework.

Scratch that, I just filter on target != HLSL now.

File: source/slang/slang-diagnostic-defs.h [hunk 2]
```diff
@@ -1658,6 +1658,12 @@ DIAGNOSTIC(
     overloadedParameterToHigherOrderFunction,
     "passing overloaded functions to higher order functions is not supported")
 
+DIAGNOSTIC(
+    39999,
+    Error,
+    matrixColumnOrRowCountIsOne,
+    "matrix of type '$0' has column or row count of 1")
```
Comment (csyonghe) [inline source/slang/slang-diagnostic-defs.h:1665]: This message is a noun and not a sentence on what is wrong. 
Consider "matrices with 1 column or row are not supported by the current code generation target".

File: source/slang/slang-emit.cpp [hunk 3]
```diff
@@ -1504,6 +1522,10 @@ Result linkAndOptimizeIR(
 #endif
     validateIRModuleIfEnabled(codeGenContext, irModule);
 
+    // Make sure there are no matrices with 1 row/column, except for HLSL where it's allowed
+    if (target != CodeGenTarget::HLSL)
```
Comment (csyonghe) [inline source/slang/slang-emit.cpp:1526]: call `isD3DTarget()` instead.

File: source/slang/slang-diagnostic-defs.h (hunk 2 above)
Comment (aleino-nv) [reply source/slang/slang-diagnostic-defs.h]: Done.

File: source/slang/slang-emit.cpp (hunk 3 above)
Comment (aleino-nv) [reply source/slang/slang-emit.cpp]: Done.

File: source/slang/slang-emit.cpp [hunk 4]
```diff
@@ -555,6 +555,24 @@ static void unexportNonEmbeddableIR(CodeGenTarget target, IRModule* irModule)
...
+    {
+        auto colCount = as<IRIntLit>(matrixType->getColumnCount());
+        auto rowCount = as<IRIntLit>(matrixType->getRowCount());
+
+        if ((rowCount && (rowCount->getValue() == 1)) || (colCount && (colCount->getValue() == 1)))
+        {
+            sink->diagnose(inst->sourceLoc, Diagnostics::matrixColumnOrRowCountIsOne);
+        }
+    }
+    for (auto child : inst->getModifiableChildren())
```
Comment (csyonghe) [inline source/slang/slang-emit.cpp:570]: We don’t need to recursively check all insts, just need to loop over all global insts and that should do it. At this stage, there can’t be any matrix type definitions that are not in global scope.

Comment (aleino-nv) [reply source/slang/slang-emit.cpp]: Done. However, now it's not printing out any source line information for the error.

I tried looping over the uses of the type, but that just got a lot of hits in the `[hlsl|glsl].meta.slang` files.
Is there an easy way to get all of the user-written usages of the type, for error reporting?

**Review by csyonghe — APPROVED** [review]

File: source/slang/slang-emit.cpp (hunk 4 above)
Comment (csyonghe) [reply source/slang/slang-emit.cpp]: I think this is fine for now. This is a temporary stopgap anyway, and we should be implementing the full support in the future.
