### PR TITLE
Fix generic function overloads in reflection API

### LINKED ISSUE #8633: findFunctionByName returns null for overloaded generic functions
When I have Slang code like this:
```
public
void print_generic_BAD<T>(T value)
{
    print("1 generic value");
}

public
void print_generic_BAD<T>(T value0, T value1)
{
    print("2 generic values");
}
```
and try to obtain a function pointer using `findFunctionByName("print_generic_BAD<int>")` I get a NULL.

However, when I have code like this:
```
public
void print_generic_GOOD<T>(T value)
{
    print("1 generic value");
}

public
void print_generic_GOOD2<T>(T value0, T value1)
{
    print("2 generic values");
}
```
both `findFunctionByName("print_generic_GOOD<int>")` and `findFunctionByName("print_generic_GOOD2<int>")` (note the name difference) bring me function pointer (so explicit specialization in isolation works).

And so does this example:
```
public
void print_int(int value)
{
    print("1 int value");
}

public
void print_int(int value0, int value1)
{
    print("2 int values");
}
```
where `findFunctionByName("print_int")` brings back a `FunctionReflection` with `isOverloaded` as true.

### PR DESCRIPTION
**Pull request by kaizhangNV**
Close #8633.

When calling `findFunctionByName<someGeneric<concrete_type>>` to find a generic function, it will report nullptr if there are overloads for the generic function.

The reason is that we didn't handle OverloadedExpr2 node in the reflection API.

The fix is to conservatively convert OverloadedExpr2 to OverloadedExpr and reuse to existing logic to keep handling the OverloadedExpr.

The alternative solution will be add logic of handling OverloadedExpr2 to every location that only handles OverloadedExpr. But it might be more complicated.

### CODE REVIEW

File: source/slang/slang-linkable.cpp [hunk 1]
```diff
@@ -813,6 +813,54 @@ Expr* ComponentType::tryResolveOverloadedExpr(Expr* exprIn)
     return visitor.maybeResolveOverloadedExpr(exprIn, LookupMask::Function, nullptr);
 }
 
+// We perform a conservative conversion from OverloadedExpr2 to OverloadedExpr here, it will
+// only convert the expression when all candidates are DeclRefExpr and share the same originalExpr
+// as that will be what OverloadedExpr expects
+static OverloadedExpr* convertOverloadExpr2(
```
Comment (tangent-vector) [inline source/slang/slang-linkable.cpp]: This comment is a good start, but I would like to see a more detailed explanation of the problem this is solving, the differences between the two overloaded expression representations (in terms of how they store the candidates), and a discussion of the strategy being used to attempt conversion.

It would also be good to document that this function returns `nullptr` on failure. Along those lines, it might be best to name this `tryConvertOverloadExpr2ToOverloadExpr` to both be more explicit about what conversion it performs and also that it only *tries* to perform the conversion, and can fail.

File: source/slang/slang-linkable.cpp [hunk 2]
```diff
@@ -855,6 +903,10 @@ Expr* ComponentType::findDeclFromString(String const& name, DiagnosticSink* sink
     {
         result = checkedExpr;
     }
+    else if (auto overloadExpr2 = as<OverloadedExpr2>(checkedExpr))
+    {
+        result = convertOverloadExpr2(overloadExpr2, astBuilder);
+    }
```
Comment (tangent-vector) [inline source/slang/slang-linkable.cpp]: It might be good to define a subroutine along the lines of:

    Expr* maybeSimplifyExprForReflectionAPIUsage(Expr* originalExpr, ASTBuilder* astBuilder);

That function would be a catch-all to try to simplify the given `originalExpr` in ways that may make it more useful as a result to expose via the reflection API, and return either a simplified expression or the original expression.

That subroutine could handle the conditional check for `OverloadedExpr2`, so that this and the other use site would just become calls like:

    result = maybeSimplifyExprForReflectionAPIUsage(result, astBuilder);

That refactor would keep the messy details out of the flow here, and also make it more clear *why* this logic is being invoked in the first place.

**Review by tangent-vector — CHANGES_REQUESTED** [review]
This is a reasonable short-term patch to address parts of the problem. I would like to see the following addressed before it lands:

* Add more complete commenting to the function that tries to convert an overloaded expression, explaining *why* the function exists, how it goes about solving the problem, and also documenting how it handles/reports failure.

* Refactor the use sites of the conversion routine to use a common bottleneck subroutine with a name that clearly indicates the purpose of the new logic. That function should get a good documentation comment.
 
The detailed comments may clarify some of these points.

(edit: removed my original request to have this PR not close out the relevant issue; on further thought I realize that this PR should cover the case the user reported and almost any non-contrived use case of the reflection API)
