### PR TITLE
Fix crash when calling interface method through interface property

### LINKED ISSUE #9816: Strange compilation error
```c++
public interface Camera {
    [Differentiable] public RayDesc sample_ray(vector<float, 2> uv);
};

public struct Perspective : Camera {
    [Differentiable] public RayDesc sample_ray(vector<float, 2> uv) {
        RayDesc ray;
        return ray;
    }
};

public interface IScene {
    public property Camera *camera;
};
struct Scene : IScene {
    Camera *camera;
};

uniform Scene _scene;

[shader("compute"), numthreads(16, 16, 1)]
void main(uint3 tid: SV_DispatchThreadID)
{
    RayDesc rayDesc = _scene.camera->sample_ray(float2(2));
}
```
with
`slangc.exe bug.slang -conformance Perspective:Camera -o out.spv`
gives
```
(0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unimplemented: Unhandled global inst in spirv-emit:
let  %1 : _     = this_type(%Tuple)
```

### PR DESCRIPTION
**Pull request by jvepsalainen-nv**
## Summary

When calling an interface method on a pointer-to-interface obtained through an interface property, the compiler crashed with "unimplemented: Unhandled global inst in spirv-emit: this_type" because the `DeclRef` lacked the witness substitution needed for dynamic dispatch.

## Root cause

In `maybeInsertImplicitOpForMemberBase`, `maybeDereference` runs before OverloadedExpr filtering. When a struct field shadows an inherited interface property, an `OverloadedExpr` is produced whose `OverloadedType` cannot be dereferenced. After filtering resolves to the concrete pointer type, the pipeline skips straight to `maybeOpenExistential`, which cannot open a pointer -- so the existential is never opened.

## Fix

Re-apply `maybeDereference` after OverloadedExpr filtering so the pointer is dereferenced before `maybeOpenExistential` runs. Remove the previous workaround in `emitCallToDeclRef`.

## Test

Added `tests/language-feature/dynamic-dispatch/interface-ptr-via-interface-property.slang` -- calls an interface method through a pointer-to-interface obtained via an interface property, targeting SPIRV with `-conformance`.

Fixes #9816

### CODE REVIEW

File: source/slang/slang-lower-to-ir.cpp [hunk 1]
```diff
@@ -936,6 +938,47 @@ LoweredValInfo emitCallToDeclRef(
     // Fallback case is to emit an actual call.
     //
     LoweredValInfo funcVal = emitDeclRef(context, funcDeclRef, funcType);
+
+    // When calling an interface method on an existential value obtained through
```
Comment (csyonghe) [inline source/slang/slang-lower-to-ir.cpp]: This is a band-aid, not a fix. The real problem is that we shouldn't be forming the declref without a meaningful ThisType substitution in the first place. Lower to IR should always lower declrefs faithfully. If the declrefs are wrong, the fault is in the type checker, not in the lower to ir logic.

**Review by csyonghe — CHANGES_REQUESTED** [review]
I don't think the fix is correct. The root cause is a lot deeper than this.

I think we have a problem that we cannot form a valid representation of a declref that represent a witness lookup into property, and that needs a systematic solution.

File: source/slang/slang-lower-to-ir.cpp (hunk 1 above)
Comment (jvepsalainen-nv) [reply source/slang/slang-lower-to-ir.cpp]: Reverted this and found the root cause. Updated PR and description.

File: source/slang/slang-check-expr.cpp [hunk 2]
```diff
@@ -5815,6 +5815,16 @@ Expr* SemanticsVisitor::maybeInsertImplicitOpForMemberBase(
             overloadedExpr->loc,
             overloadedExpr);
         // TODO: handle other cases of OverloadedExpr that need filtering.
+
+        // The filtering may have resolved the OverloadedExpr into a concrete
+        // expression whose type is dereferenceable (e.g. a pointer to an
+        // interface). Since maybeDereference was already called before the
+        // OverloadedExpr filtering and could not dereference the OverloadedType,
+        // we need to try again now that the type is known.
+        auto derefExpr2 = maybeDereference(baseExpr, checkBaseContext);
```
Comment (csyonghe) [inline source/slang/slang-check-expr.cpp]: I wonder if we should just move the `maybeDereference` call at the beginning of this function to after resolving overloadedExpr instead?

Comment (jvepsalainen-nv) [reply source/slang/slang-check-expr.cpp]: Moved to to after the OverloadedExpr filtering.
