### PR TITLE
Fix defaultConstruct of DescriptorHandler

### LINKED ISSUE #9932: SPIR-V ICE: defaultConstruct not implemented for DescriptorHandle<T> in AnyValue unpacking
## Summary

Using `as` (dynamic cast) on an `ILight` interface value to cast back to a concrete struct type that contains `DescriptorHandle<T>` fields triggers an Internal Compiler Error in the SPIR-V emitter. The error occurs because `defaultConstruct` is not implemented for `DescriptorHandle<T>`.

## Reproduction

```slang
interface ILight {
    LightSample eval(float3 p, float3 p_L, float3 wi);
}

struct DomeLight : ILight {
    float3x3 transform;
    float intensity;
    uint flags;
    DescriptorHandle<Texture2D<float4>> hdrTexture;
    DescriptorHandle<SamplerState> linearSampler;

    LightSample eval(float3 p, float3 p_L, float3 wi) { /* ... */ }
};

// This works fine - packing into ILight:
ILight light = lightData.Load<DomeLight>(offset);

// This triggers ICE - unpacking back to concrete type:
if (let dome = light as DomeLight) {
    // use dome-specific members
}
```

Compile with: `slangc -target spirv`

The ICE mentions `defaultConstruct` in the SPIR-V emitter, indicating it doesn't know how to create a default value for `DescriptorHandle<T>` when preparing the destination struct for AnyValue unpacking.

## Expected Behavior

`as DomeLight` should work. Since `DescriptorHandle<T>` is represented as `uint2` in SPIR-V, the default-constructed value should be `uint2(0, 0)`.

The forward path (packing DomeLight into AnyValue for ILight dispatch via `ByteAddressBuffer.Load<T>()`) already works correctly, proving the type system supports serializing/deserializing DescriptorHandle through AnyValue. The reverse path (`as` cast) just needs the same support for default construction.

## Workaround

Avoid `as` casts to concrete types with DescriptorHandle fields. Instead, check the type via an external discriminator and use the interface directly:

```slang
// Instead of: if (let dome = light as DomeLight) { ... }
// Use the interface methods directly:
if (lightsDesc[i].lightType == LightType.Dome) {
    ILight light = LightFactory.getLight(lightsDesc[i], lightData);
    let sample = light.eval(p, p_L, wi);  // works via interface dispatch
}
```

## Environment

- **Slang version**: 2026.2
- **Target**: SPIR-V (Vulkan 1.2)

## Related

- #9931 — ByteAddressBuffer.Load uint2 alignment bug (separate issue, same project)
- #9131 / #9386 — DescriptorHandle + AnyValue dynamic dispatch fix (the forward path that enabled this usage)

### PR DESCRIPTION
**Pull request by kaizhangNV**
Close #9932.

During lowering the Optional Type, if the HasValue is none, we will still need to default construct the type to get a clear layout. But for SPIRV, we don't handle the defaultConstruct for DescriptorHandler. So we just process this in the SPIRV legalization pass.

defaultConstruct for DescriptorHandler is already correctly handled in other targets so we don't need to do any special handling.

### CODE REVIEW

**Review by csyonghe — DISMISSED** [review]

File: source/slang/slang-ir-spirv-legalize.cpp [hunk 1]
```diff
@@ -1454,6 +1454,44 @@ struct SPIRVLegalizationContext : public SourceEmitterBase
...
+            {
+                // spvBindlessTextureNV: DescriptorHandle is uint64_t
+                auto uint64Type = builder.getUInt64Type();
+                auto zero64 = builder.getIntValue(uint64Type, 0);
+                castInst =
+                    builder.emitIntrinsicInst(type, kIROp_CastUInt64ToDescriptorHandle, 1, &zero64);
+            }
+            else
+            {
+                // Default: DescriptorHandle is uint2
```
Comment (jkwak-work) [inline source/slang/slang-ir-spirv-legalize.cpp:1480]: I think this implementation has a problem that Yong pointed out for CUDA and CPU targets, isn't it?:
https://github.com/shader-slang/slang/pull/9940#discussion_r2800596427
> This will be incorrect for cuda structured buffer, which is 16 bytes.
> Again, do not assume descriptor handle is uint2, unless you are in a spirv-only path.
