### PR TITLE
Fix legalization crash when processing metal parameter blocks.

### LINKED ISSUE #7606: Metal crash with slangpy test_array test
The following slangpy tests crash the slang compiler:
 
- `test_array.py`
  - `test_vectorize_struct_with_resource_array`
  - `test_vectorize_struct_with_ndbuffer_array`
  - `test_vectorize_struct_with_tensor_array`
  - `test_2d_mapped_vectorize_struct_with_tensor_array`
- `test_packed_arg.py`
  - `test_vectorize_struct_with_tensor_array`

Stack trace:

```
libc++abi.dylib!__cxa_throw (Unknown Source:0)
libslang.dylib!Slang::handleSignal(Slang::SignalType, char const*) (Unknown Source:0)
libslang.dylib!Slang::IRBuilder::emitFieldExtract(Slang::IRInst*, Slang::IRInst*) (Unknown Source:0)
libslang.dylib!Slang::coerceToLegalType(Slang::IRTypeLegalizationContext*, Slang::LegalType, Slang::LegalVal) (Unknown Source:0)
libslang.dylib!Slang::coerceToLegalType(Slang::IRTypeLegalizationContext*, Slang::LegalType, Slang::LegalVal) (Unknown Source:0)
libslang.dylib!Slang::coerceToLegalType(Slang::IRTypeLegalizationContext*, Slang::LegalType, Slang::LegalVal) (Unknown Source:0)
libslang.dylib!Slang::coerceToLegalType(Slang::IRTypeLegalizationContext*, Slang::LegalType, Slang::LegalVal) (Unknown Source:0)
libslang.dylib!Slang::legalizeInst(Slang::IRTypeLegalizationContext*, Slang::IRInst*) (Unknown Source:0)
libslang.dylib!Slang::IRTypeLegalizationPass::processModule(Slang::IRModule*) (Unknown Source:0)
libslang.dylib!Slang::legalizeResourceTypes(Slang::TargetProgram*, Slang::IRModule*, Slang::DiagnosticSink*) (Unknown Source:0)
libslang.dylib!Slang::linkAndOptimizeIR(Slang::CodeGenContext*, Slang::LinkingAndOptimizationOptions const&, Slang::LinkedIR&) (Unknown Source:0)
libslang.dylib!Slang::CodeGenContext::emitEntryPointsSourceFromIR(Slang::ComPtr<Slang::IArtifact>&) (Unknown Source:0)
libslang.dylib!Slang::CodeGenContext::emitWithDownstreamForEntryPoints(Slang::ComPtr<Slang::IArtifact>&) (Unknown Source:0)
libslang.dylib!Slang::CodeGenContext::_emitEntryPoints(Slang::ComPtr<Slang::IArtifact>&) (Unknown Source:0)
libslang.dylib!Slang::CodeGenContext::emitEntryPoints(Slang::ComPtr<Slang::IArtifact>&) (Unknown Source:0)
libslang.dylib!Slang::TargetProgram::_createEntryPointResult(long long, Slang::DiagnosticSink*, Slang::EndToEndCompileRequest*) (Unknown Source:0)
libslang.dylib!Slang::ComponentType::getEntryPointCode(long long, long long, ISlangBlob**, ISlangBlob**) (Unknown Source:0)
```

### PR DESCRIPTION
**Pull request by csyonghe**
Closes #7606.

When Slang compile for a bindful target, we will run the resource type legalization pass to hoist resource typed struct fields outside of the struct type and define them as global parameters and passing them around via dedicated function parameters.
When we compile for a bindless target, we don't run this pass.
However, Metal is a hybrid bindful and bindless target. We need  to run type legalization for the constant buffer, but skip type legalization for parameter block.

The previous attempt to support this behavior is to hack the type legalization pass to return `LegalVal::simple` when it sees a `ParameterBlock<T>`. However, whenever the code is accessing `parameterBlock.someNestedField`, the type of the nested field may get a `LegalType::tuple`, and now we will run into inconsistent scenarios where we have a `LegalVal::simple` on the operand val, and but the legalization logic is expecting that val to be a `LegalType::tuple`. This breaks a lot of assumptions and invariants in the type legalization pass, resulting unstable/fragile behavior.

To systematically solve this problem, this change generalizes the existing legalize buffer element type pass to translate `ParameterBlock<Texture2D>` (and similar cases) to `ParameterBlock<Texture2D.Handle>`. So that such parameter block will always be legalized to `LegalType:::simple` during type legalization, and we will never run into any inconsistent cases. This allowed us to get rid of the hacky logic in the type legalization pass to try to workaround the inconsistencies.

### CODE REVIEW

File: source/slang/slang-ir-lower-buffer-element-type.cpp [hunk 1]
```diff
@@ -2295,8 +2062,413 @@ TypeLoweringConfig getTypeLoweringConfigForBuffer(TargetProgram* target, IRType*
...
+    virtual bool shouldAlwaysCreateLoweredStorageTypeForCompositeTypes(
+        TypeLoweringConfig config) override
+    {
+        // For spirv backend, we always want to lower all array types, even if the element type
+        // comes out the same. This is because different layout rules may have different array
+        // stride requirements.
+        //
+        // Additionally, `buffer` blocks do not work correctly unless lowered when targeting
+        // GLSL.
+        return target->shouldEmitSPIRVDirectly() || config.addressSpace != AddressSpace::Input;
```
Comment (jkwak-work) [inline source/slang/slang-ir-lower-buffer-element-type.cpp]: The previous corresponding line for this seems to be the following,
```
 if (!target->shouldEmitSPIRVDirectly() || config.addressSpace == AddressSpace::Input)
```
It seems like the full logic is negated incorrect.
I think it should use `&&` instead of `||` like the following:
```
target->shouldEmitSPIRVDirectly() && config.addressSpace != AddressSpace::Input
```

File: source/slang/slang-ir-insts.lua [hunk 2]
```diff
@@ -1908,6 +1908,7 @@ local insts = {
 	-- Represents a no-op cast to convert a resource pointer to a resource on targets where the resource handles are
 	-- already concrete types.
 	{ CastDescriptorHandleToResource = { min_operands = 1 } },
+	{ CastResourceToDescriptorHandle = { min_operands = 1 } },
```
Comment (jkwak-work) [inline source/slang/slang-ir-insts.lua:1911]: It looks like this IR is newly added.
But I am having a trouble understanding where the new IR is used.
I don't see any lowering logic that emits this IR.

Is this IR needed?

Codex thinks that this new IR might be intended for the Metal case but it ended up using BitCast.
```
info.convertLoweredToOriginal = kIROp_CastDescriptorHandleToResource;
info.convertOriginalToLowered = kIROp_BitCast; // <=== Is this supposed to be kIROp_CastResourceToDescriptorHandle ???
```

File: source/slang/slang-ir-lower-buffer-element-type.cpp [hunk 3]
```diff
@@ -214,104 +214,173 @@
...
+    IRTypeLayoutRules* getLayoutRule() const { return IRTypeLayoutRules::get(layoutRuleName); }
+
     bool operator==(const TypeLoweringConfig& other) const
     {
-        return addressSpace == other.addressSpace && layoutRule == other.layoutRule;
+        return addressSpace == other.addressSpace && layoutRuleName == other.layoutRuleName;
     }
     HashCode getHashCode() const
     {
-        return combineHash(Slang::getHashCode(addressSpace), Slang::getHashCode(layoutRule));
```
Comment (jkwak-work) [inline source/slang/slang-ir-lower-buffer-element-type.cpp:227]: Oh. This seems like a bug to use a memory address value as a hash input.
Good catch.

File: source/slang/slang-ir-insts.lua (hunk 2 above)
Comment (csyonghe) [reply source/slang/slang-ir-insts.lua:1911]: You are right, it is supposed to be kIROp_CastResourceToDescriptorHandle  there.

File: source/slang/slang-ir-lower-buffer-element-type.cpp (hunk 1 above)
Comment (csyonghe) [reply source/slang/slang-ir-lower-buffer-element-type.cpp]: yeah, you are right, should change to && to stay consistent with previous logic.

**Review by jkwak-work — DISMISSED** [review]
Looks good to me.
