### PR TITLE
Emit diagnostic for __ref/__constref params with interface types in dynamic dispatch

### LINKED ISSUE #9906: Compiler error when using `__ref` parameter with interface type in dynamic dispatch
## Issue Description

Using `__ref` or `__constref` parameters with interface types that require dynamic dispatch should produce a clear diagnostic error. Currently:
- `__ref` crashes with internal compiler error (99999)
- `__constref` silently compiles, but the generated code is likely incorrect — the callee receives a reference to the packed `AnyValue` tagged union layout rather than the concrete type's storage

### `__ref` (crash)

```hlsl
[anyValueSize(16)]
interface IFoo {
    float getValue();
}

struct A : IFoo {
    float v;
    float getValue() { return v; }
}

struct B : IFoo {
    float v;
    float getValue() { return v * 2; }
}

float processRef(__ref IFoo obj) {
    return obj.getValue();
}

IFoo makeObj(uint id) {
    if (id == 0) return A(1.0);
    return B(2.0);
}

RWStructuredBuffer<float> output;

[numthreads(1,1,1)]
void main() {
    IFoo obj = makeObj(0);
    output[0] = processRef(obj);
}
```

### `__constref` (silent incorrect codegen)

Replace the function signature above with:

```hlsl
float processRef(__constref IFoo obj) {
    return obj.getValue();
}
```

This compiles without error but should be rejected for the same reason.

**Command:**
```bash
slangc -target spirv test.slang
```

## Expected Behavior

A clear diagnostic error for both cases, explaining that `__ref`/`__constref` parameters of interface types are not supported in dynamic dispatch contexts. Note that `inout` parameters work correctly because they use copy-in/copy-out semantics rather than true reference semantics.

## Actual Behavior

For `__ref`:
```
(0): error 99999: Slang compilation aborted due to an exception of N5Slang13InternalErrorE:
unexpected: Unhandled parameter direction in interprocedural edge
```

For `__constref`: compiles without error (should be rejected).

## Environment

- Slang Version: current main branch
- OS: macOS / Windows / Linux
- Target: SPIR-V (also reproducible with other targets)

### PR DESCRIPTION
**Pull request by jvepsalainen-nv**
Using `__ref` with an interface type in a dynamic dispatch context caused an internal compiler error (99999), and `__constref` silently compiled with incorrect codegen. Both are now rejected with a clear diagnostic (error 52010).

Dynamic dispatch uses a tagged union (AnyValue) representation which is incompatible with reference semantics — the callee would receive a reference to the packed representation rather than the concrete type's storage.

Note: The diagnostic fires for SPIRV and HLSL targets. CUDA handles existentials differently (no AnyValue packing in the type-flow pass), so `__ref`/`__constref` with interface types compiles without error on CUDA.

Changes:
- Add diagnostic 52010 (`refParamWithInterfaceTypeInDynamicDispatch`)
- Add helper `typeInvolvesDynamicDispatchInterface()` that checks whether a type is or transitively contains a dynamic dispatch interface (handles structs, arrays, optionals, tuples)
- Check `__ref`/`__constref` params before the `isConcreteType` optimization so struct-containing-interface cases are also caught
- Add `Ref` to the interprocedural edge switch to handle non-interface `__ref` params without crashing
- Deduplicate diagnostics so each parameter is reported only once regardless of how many call sites exist
- Enable all 6 `diagnose-ref-*` tests (previously disabled pending implementation)

Fixes #9906

### CODE REVIEW

File: source/slang/slang-ir-typeflow-specialize.cpp [hunk 1]
```diff
@@ -636,6 +636,40 @@ bool isOptionalExistentialType(IRInst* inst)
     return false;
 }
 
+// Returns true if the type is or transitively contains an interface type
+// that would require dynamic dispatch (i.e., not a COM interface and not builtin).
+static bool typeInvolvesDynamicDispatchInterface(IRType* type)
```
Comment (skiminki-nv) [inline source/slang/slang-ir-typeflow-specialize.cpp]: I would maybe figure out a better name for this function. `typeIncludesDynamicDispatch()`?

Comment (jvepsalainen-nv) [reply source/slang/slang-ir-typeflow-specialize.cpp]: True. Renamed function
