### PR TITLE
fix a autodiff crash

### LINKED ISSUE #8068: Slang crashes when specifying `[BackwardDifferentiable]` for interface methods
Minimal reproducing example:

```slang
interface IVector<T, int N> : IDifferentiable
    where T : __BuiltinFloatingPointType
{
    [BackwardDifferentiable]
    This max(T other);
}

struct InlineVector<T, int N> : IVector<T, N>
    where T : __BuiltinFloatingPointType
{
    typealias Differential = This;

    T[N] data;

    __init(T value) { data[0] = value; }

    [BackwardDifferentiable]
    This max(T other)
    {
        This result = this;

        [MaxIters(N)]
        for (int i = 0; i < N; i++)
            result.data[i] = max(result.data[i], other);

        return result;
    }
}

RWStructuredBuffer<float> g_output;

[shader("compute")]
void computeMain(uint3 thread_id : SV_DispatchThreadID)
{
    var input = InlineVector<float, 2>(0.0);
    var output = input.max(1.0);
    g_output[thread_id.x] = output.data[0];
}
```

Two ways to get around this currently:
* Omit `typealias Differential = This;` but this disables autodiff for the type
* Omit `[BackwardDifferentiable]` from the interface specification for `max` which seems to preserves autodiff capabilities

### PR DESCRIPTION
**Pull request by kaizhangNV**
close #8068.

Currently the AutoDiff aggressively scan every IR inst in searching the differentiable IR. This is not efficient and could have bug, details in https://github.com/shader-slang/slang/issues/8068#issuecomment-3214856668.

This PR change the behavior. It will do a initial filter to only gather the global differentiable IRs and IRFunc and IRGeneric as well. For IRGeneric, we will pick it only when it's used in other generic function (it's only useful when dealing with dynamic dispatch).

Then we will start searching reachable insts from this IR list by using the same method as before.

### CODE REVIEW

File: source/slang/slang-ir-autodiff.cpp [hunk 1]
```diff
@@ -3345,6 +3345,91 @@ struct AutoDiffPass : public InstPassBase
         return true;
     }
 
+    // This function will check whether a global inst can be gathered as a candidate for
```
Comment (csyonghe) [inline source/slang/slang-ir-autodiff.cpp:3348]: What's the intention of this function? If we are compiling a module that exports a generic differentiable function that isn't called from within the module, then we won't process it because it is not referenced by another function?

I don't quite understand why we need this filtering.

File: tests/diagnostics/autodiff-This-as-Differential.slang [hunk 2]
```diff
@@ -0,0 +1,45 @@
+//DIAGNOSTIC_TEST:SIMPLE:
```
Comment (csyonghe) [inline tests/diagnostics/autodiff-This-as-Differential.slang]: file names should be all lower case.

File: source/slang/slang-ir-autodiff.cpp (hunk 1 above)
Comment (kaizhangNV) [reply source/slang/slang-ir-autodiff.cpp:3348]: Assume this case

```
generic %1
{
         FarwardDifferentiate(spcialiize(%2, ...))
}

generic %2
{
         reference to %1
}
```

Previously, since we scan every IR, we will definitely transcribe `%2`, because of `%1`.
However, if `%1` is not a function at all, and there is no one even use it, why would we still need to transcribe %2?

This filter function just serves this purpose, we only want to scan a IR inst that really call into a auto-diff function.

Comment (kaizhangNV) [reply source/slang/slang-ir-autodiff.cpp:3348]: The basic idea is that we only need to scan every function, and traverse its children to find auto-diff inst.

However, there are couple of exceptions:

- There could be global inst e.g. `let FunType = FarwardDifferentiate(...)`, so we will collect this as well.
- To handle the dynamic dispatch case, so we will also gather generic in the worklist. But this generic has to be called somewhere.

Comment (csyonghe) [reply source/slang/slang-ir-autodiff.cpp:3348]: I wonder if the right logic is to skip all generic witness tables when discovering the forward/backward differentiate insts.

Comment (kaizhangNV) [reply source/slang/slang-ir-autodiff.cpp:3348]: I asked myself this question as well.
But I don't have a very confident answer, the only way I can verify is running all the existing tests.

Comment (kaizhangNV) [reply source/slang/slang-ir-autodiff.cpp:3348]: Actually, I discussed this with Sai already, and he thinks it should be fine that we can skip all generic witness table.
From my point of view, as long as this won't break the dynamic dispatch logic, we should be fine.
As that is the only case that auto-diff would transcribe a generic function.

Comment (saipraveenb25) [reply source/slang/slang-ir-autodiff.cpp:3348]: My understanding is that, since we do not support dynamic dispatch for generic interfaces under any target, we should not see a case where a generic witness table is being used after the specialization pass is complete. 
We could see a witness table with generic entries, of course, but not witness tables inside generics.
