### PR TITLE
Incrementally update candidate extension cache

### LINKED ISSUE #8954: Apparent leakage of state causing reflection system to return incorrect results depending on call order
When using specializeWithArgTypes via slangpy, I've hit a situation in which the order of calls affects whether specialize will succeed. The example code reproduces it.

It seems that if I specifically:
- Load a module with Foo that inherits IFoo, and contains testfunc(IFoo x)
- Call specializeWithArgTypes(Foo)
- Load a 2nd module with Foo2 that is **extended** to inherit IFoo2 and contains testfunc2(IFoo2 x)
- Call specializeWithArgTypes(Foo2)

The 2nd call will return null. 

The issue only occurs when using extensions (i.e. not if Foo2 inherits IFoo2 directly) and is dependent on the order in which modules are loaded.

I believe it also occurs if using generic syntax instead such as `void testfunc<T: IFoo>(T x)`

```

# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

import pytest

import slangpy as spy
import slangpy.testing.helpers as helpers


# Limit the device types tested here to just one, since these tests are not device specific.
DEVICE_TYPES = helpers.DEFAULT_DEVICE_TYPES[0:1]

@pytest.mark.parametrize("device_type", DEVICE_TYPES)
@pytest.mark.parametrize("runa", [False,True])
@pytest.mark.parametrize("runb", [False,True])
def test_interface(device_type: spy.DeviceType, runa: bool, runb: bool):
    """
    Reproduced 'leakage' of type information between tests due to some apparent global state in the session. When both
    code paths are run, the 2nd specialize will fail even though all types involved are completely independent.

    If Foo2 is made to directly inherit from IFoo2 instead of going via an extension, the test will pass.

    If the execution of 'runa' is moved AFTER module2 is loaded, the test will pass.
    """

    # Note: use_cache=False to avoid any caching effects interfering with separate test runs
    device = helpers.get_device(type=device_type, use_cache=False)

    # Create a module with an IFoo interface, a Foo struct implementing it, and a function taking IFoo
    code = f"""
    interface IFoo {{}}
    struct Foo: IFoo {{}}
    void test_func(IFoo x) {{}}
    """
    module1 = helpers.create_module(device, code)

    # If enabled, attempt to specialize test_func with Foo
    if runa:
        func = module1.layout.require_function_by_name("test_func").specialize_with_arg_types([module1.layout.require_type_by_name("Foo")])
        assert func is not None, "Could not specialize function 1"

    # Create a 2nd similar module with IFoo2, Foo2, and test_func2. In this case, Foo2 implements IFoo2 via an extension.
    code = f"""
    interface IFoo2 {{}}
    struct Foo2 {{}}
    extension Foo2: IFoo2 {{}}
    void test_func2(IFoo2 x) {{}}
    """
    module2 = helpers.create_module(device, code)

    # If enabled, attempt to specialize test_func2 with Foo2
    # This fails if runa is also True
    if runb:
        func = module2.layout.require_function_by_name("test_func2").specialize_with_arg_types([module2.layout.require_type_by_name("Foo2")])
        assert func is not None, "Could not specialize function 2"

```

### PR DESCRIPTION
**Pull request by jhelferty-nv**
Fixes #8954

The candidate extension cache now updates incrementally as modules are loaded via API, following the ContainerDecl pattern. Previously, the cache was built once and never updated, causing extensions from later-loaded modules to not be found during specialization.

Only affects API/reflection contexts where modules are loaded dynamically. Module-scoped compilation was unaffected as all imports are processed upfront before the cache is built.

### CODE REVIEW

File: source/slang/slang-check-decl.cpp [hunk 1]
```diff
@@ -11616,7 +11618,28 @@ List<ExtensionDecl*> const& SharedSemanticsContext::getCandidateExtensionsForTyp
             {
                 _addCandidateExtensionsFromModule(module->getModuleDecl());
             }
+            m_candidateExtensionListsBuiltForModuleCount = m_linkage->loadedModulesList.getCount();
+        }
+    }
+    else if (!m_module)
```
Comment (kaizhangNV) [inline source/slang/slang-check-decl.cpp:11624]: I'm not sure what this condition really means?
Can you explain?

Comment (kaizhangNV) [reply source/slang/slang-check-decl.cpp:11624]: Especially, I need to understand why this else-if branch indicates this is compilation API or reflection API context.

Comment (jhelferty-nv) [reply source/slang/slang-check-decl.cpp:11624]: It was documented up at line 11593. To make it clearer, I could refactor that and this if statement into a separate `isReflectionContext()` method that returns whether `m_module` is `nullptr`?

Comment (jhelferty-nv) [reply source/slang/slang-check-decl.cpp:11624]: I've refined the comment a bit. The terminology used elsewhere is 'ad hoc context', so I've switched to that.

**Comment by kaizhangNV** [comment]
I think you need to add a unit test.

**Comment by kaizhangNV** [comment]
I removed it from the merge queue, as we need a unit test in `slang-unit-test` using slang API to reproduce the bug.

**Comment by jhelferty-nv** [comment]
> I think you need to add a unit test.

The test is added on the slangpy side, see: https://github.com/shader-slang/slangpy/pull/631. It was checked in disabled, but can be enabled after the fix goes in. (It seemed redundant to add a unit test whenever a slangpy test would also exist.)
