### PR TITLE
Fix language server crash.

### LINKED ISSUE #7749: Slangd crashes a few seconds after loading this shader
Hi! Here's a quick language server crash I ran into on Slang 2025.12.1 on Windows while developing a shader.
The observed behavior is that slangd crashes (with Windows error code 0xC0000005) after the "textDocument/didOpen" message is sent with a certain shader (which has an unclosed brace because I was in the middle of writing the `sortLoHi` function).

slangd running in Windows Terminal crashing after receiving a shader

I've managed to reproduce this on the command line using Windows Terminal:

1. `cd` into `slangd`'s directory, run `slangd.exe`, and copy and paste the text below followed by two newlines:

```
Content-Length: 86

{"id":0,"jsonrpc":"2.0","method":"initialize","params":{"clientInfo":{"name":""}}}
```

Wait for slangd to respond with a message of Content-Length 2924.

2. Finish the initialization handshake by copying and pasting the text below followed by two newlines:

```
Content-Length: 51

{"id":1,"jsonrpc":"2.0","method":"initialized"}
```

Wait for slangd to respond with a workspace/configuration message. slangd seems to work if you never respond to this message.

3. Copy and paste the text below followed by 4 newlines:

```
Content-Length: 3414

{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"slang","text":"RWTexture2D<float4> texFrame; // Output texture\nuniform float iTime; // In seconds\nuniform float2 iResolution; // Screen size\n\nstatic const float kInfinity = asfloat(0x7f800000);\nstatic const uint32_t kIdNone = 0xFFFFFFFF;\n\nstruct Intersection\n{\n\tfloat t = kInfinity;\n\tuint32_t id = kIdNone;\n\t\n\tbool missed() {\n\t\treturn id == kIdNone;\n\t}\n\t\n\t[mutating]\n\tvoid update(uint32_t newId, float newT)\n\t{\n\t\tif(newT >= 0 && newT < t)\n\t\t{\n\t\t\tt = newT;\n\t\t\tid = newId;\n\t\t}\n\t}\n};\n\nstruct Ray\n{\n\tfloat3 origin;\n\tfloat3 direction;\n\tfloat3 at(float t)\n\t{\n\t\treturn mad(origin, direction, float3(t));\n\t}\n};\n\n// Returns the t-value of the intersection of the infinite line\n// with the plane given by\n// `dot(planeNormal, p) == planeDist`.\nfloat intersectPlane(Ray ray, float3 planeNormal, float planeDist)\n{\n\t// dot(planeNormal, o + d * t) == planeDist\n\t// -> dot(planeNormal, o) + t * dot(planeNormal, d) == planeDist\n\t// -> t = (planeDist - dot(planeNormal, o)) / dot(planeNormal, d)\n\treturn (planeDist - dot(planeNormal, ray.origin))\n\t\t/ dot(planeNormal, ray.direction);\n}\n\nfloat2 sortLoHi(float2 v)\n{\n\t\n\nstruct OBB\n{\n\t// Note that these are more parameters than we need;\n\t// technically, the sides of an OBB must all be perpendicular,\n\t// so there's only 3 (position) + 3 (side lengths) + 3 (rotation)\n\t// degrees of freedom.\n\tfloat3 corner;\n\tfloat3 edges[3];\n\t\n\t// Returns the t-value of the intersection of the OBB with\n\t// the ray.\n\t// The returned t-value may be negative; i.e. this assumes\n\t// the camera is outside of the box.\n\t// On miss, returns infinity.\n\tfloat intersect(Ray ray)\n\t{\n\t\tray.origin -= corner;\n\t\t\n\t\tfloat2 tCloseFar;\n\t\tfloat tFar;\n\t\t[ForceUnroll]\n\t\tfor(int i = 0; i < 3; i++)\n\t\t{\n\t\t\tconst float3 edge = edges[i];\n\t\t\tconst float edgeDist = dot(edge, ray.origin);\n\t\t\tconst float factor = rcp(dot(edge, ray.direction));\n\t\t\tfloat2 slab = (float2(0, dot(edge, edge)) - edgeDist)\n\t\t\t\t* factor;\n\t\t\tslab = \n\t\t\tif(i == 0)\n\t\t\t{\n\t\t\t\ttClose = min(slab.x, slab.y);\n\t\t\t\ttFar   = max(slab.x, slab.y);\n\t\t\t}\n\t\t\telse\n\t\t\t{\n\t\t\t\ttClose = min3(tClose, slab.x, slab.y);\n\t\t\t\ttFar = max3(tFar, slab.x, slab.y);\n\t\t\t}\n\t\t\tthisSlab = sortLoHi(thisSlab);\n\t\t\ttCloseFar.x = \n\t\t}\n\t\treturn kInfinity;\n\t}\n};\n\n[shader(\"compute\")]\n[numthreads(16, 16, 1)]\nvoid main(uint2 thread: SV_DispatchThreadID)\n{\n\tfloat2 uv = (2.0 * float2(thread) - iResolution.xy) / iResolution.y;\n\t\n\t// Right-handed Z-up coordinate system, same as Blender's\n\tRay ray;\n\tray.origin = float3(0, -4, 4);\n\tstatic const float kSqrtP5 = sqrt(.5);\n\tray.direction = float3(\n\t\tuv.x,\n\t\tkSqrtP5 -kSqrtP5 * uv.y,\n\t\t-kSqrtP5 -kSqrtP5 * uv.y\n\t);\n\t\n\tIntersection intersection;\n\tintersection.update(0, intersectPlane(ray, float3(0,0,1), 0));\n\tOBB obb = OBB(float3(-1,-1,-1),{float3(2,0,0),float3(0,2,0), float3(0,0,2)});\n\tintersection.update(1, obb.intersect(ray));\n\t\n\tfloat3 color;\n\tif(intersection.missed())\n\t{\n\t\tcolor = float3(0.0, 0.0, 1.0);\n\t}\n\telse\n\t{\n\t\tcolor = float3(intersection.t / 10.0);\n\t}\n\t\n\ttexFrame[thread] = float4(color, 1.0);\n}\n","uri":"temp.slang","version":1}}}
```

After a second or two, slangd will crash; running `echo %errorlevel%` then returns -1073741819.

Thanks!

### PR DESCRIPTION
**Pull request by csyonghe**
Fixes #7749.

- Fixed a bug in parser that caused us to aggressively parse the function bodies if the function is a struct member, and the struct is nested inside another function.
- Allow `getResultType` to return `ErrorType` if the result type on the function hasn't been checked.
- Throw critical exception and abort compilation to prevent crash if a decl doesn't have a parent.

### CODE REVIEW

File: source/slang/slang-check-decl.cpp [hunk 1]
```diff
@@ -9672,9 +9672,8 @@ void SemanticsVisitor::checkForRedeclaration(Decl* decl)
 
     // Sanity check: there should always be a parent declaration.
     //
-    SLANG_ASSERT(parentDecl);
     if (!parentDecl)
-        return;
+        SLANG_ABORT_COMPILATION("decl has no parent.");
```
Comment (jkwak-work) [inline source/slang/slang-check-decl.cpp:9676]: Feel free to ignore this comment.
But I think it will be a good idea to leave a comment here explaining why we are throwing an exception, because it is not a common case.

**Review by jkwak-work — APPROVED** [review]
Looks good to me.

File: source/slang/slang-check-decl.cpp (hunk 1 above)
Comment (csyonghe) [reply source/slang/slang-check-decl.cpp:9676]: A normal compile shouldn't hit this case, it is only possible to reach here when in language server mode where we intentionally ignore compile errors and force type checking to continue.
