### PR TITLE
Fix pointer field/member access for GLSL

### LINKED ISSUE #6710: Issues with pointer field/member access when targeting GLSL
Repro attached:
[skybox-174573421218.zip](https://github.com/user-attachments/files/19542315/skybox-174573421218.zip)
Slang Discord support thread for context: https://discord.com/channels/1303735196696445038/1355954139393425408

Here is the shader:
```c
struct Vertex {
    float3 position;
    float uv_x;
    float3 normal;
    float uv_y;
    float4 color;
}

struct PerObjectData {
    float4x4 transform;
    int obj_id;
    int albedo_index;
    int pad0, pad1;
}

struct Light {
    float4 position, color;
}

struct SceneUniforms {
    float4x4 view, world, projection, inv_view, inv_projection, view_world, proj_view_world, pad;
    PerObjectData obj_data[2000];
    Light lights[64];
}


struct VSOutput {
    float4 Position : SV_Position;
    float3 TexCoord : TEXCOORD;
}

struct PushConsts {
    int object_index;
    Vertex* verts;
};

ConstantBuffer<PushConsts> push_consts;
ConstantBuffer<SceneUniforms> uniforms;

// Removes the translation component (last row and last column),
// leaving only the rotation 
float4x4 remove_translation(float4x4 mat) {
    return float4x4(
        mat._11, mat._12, mat._13, 0,
        mat._21, mat._22, mat._23, 0,
        mat._31, mat._32, mat._33, 0,
        0,       0,       0,       1
    );
}

func get_vertex(vertex_id: int)->Vertex {
    let vs = push_consts.verts as Vertex[];
    return vs.value[vertex_id];
}

[shader("vertex")]
VSOutput main(in int vert_index: SV_VertexID) : SV_Position {
    VSOutput output;
    let vertex = get_vertex(vert_index);
    output.TexCoord = push_consts.verts[vert_index].position.xyz;
    output.Position = mul(uniforms.projection * remove_translation(uniforms.view), float4(output.TexCoord, 1.0));
    output.Position.z = 1;
    return output;
}
```

compile with `slang shader.slang -profile glsl_450 -target glsl -o shader.glsl -entry main -dump-repro-on-error -capability GLSL_450`

### PR DESCRIPTION
**Pull request by fairywreath**
Closes #6710.

Fixes field/member acceses for pointer(`*`) syntax when targeting GLSL. The current behavior returns internal error 9999/unexpected IR during code emit.

### CODE REVIEW

File: source/slang/slang-emit-glsl.cpp [hunk 1]
```diff
@@ -2158,7 +2166,7 @@ bool GLSLSourceEmitter::tryEmitInstExprImpl(IRInst* inst, const EmitOpInfo& inOu
                 bool needClose = maybeEmitParens(outerPrec, prec);
                 emitOperand(inst->getOperand(0), prec);
                 m_writer->emit("._data.");
-                emitOperand(inst->getOperand(1), getInfo(EmitOp::General));
```
Comment (fairywreath) [inline source/slang/slang-emit-glsl.cpp:2161]: Internal error 9999/unexpected IR was previously encountered here because `getOperand(1)` is a `IRStructKey` type which the emitter does not handle. Instead, we canjust emit the field name directly here.

File: tests/spirv/pointer-2.slang [hunk 2]
```diff
@@ -0,0 +1,70 @@
+//TEST:SIMPLE(filecheck=CHECK_SPV): -entry vertexMain -stage vertex -emit-spirv-directly -target spirv
+//TEST:SIMPLE(filecheck=CHECK_GLSL): -entry vertexMain -stage vertex -target glsl
```
Comment (csyonghe) [inline tests/spirv/pointer-2.slang:2]: Can you add a test that -target spirv -emit-spirv-via-glsl and check for “;Glslang” to verify the glsl is valid and can be compiled by glslang.

**Review by csyonghe — APPROVED** [review]
