### PR TITLE
Print warning when operator<< shifting too much

### LINKED ISSUE #3944: Operator << incorrectly truncates values.
uint8_var << 15

Is resolved to call <<(uint8, uint8) but should be calling << (int, int) instead with a warning.

We should also make sure related operators such as * also get treated correctly.

### PR DESCRIPTION
**Pull request by jkwak-work**
Closes #3944

For the given type of the left side operand to `operator<<` is not big enough for the right side operand, print a warning that the result will be always zero.

### CODE REVIEW

File: source/slang/slang-ir-operator-shift-overflow.cpp [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+                    auto rhsLit = as<IRIntLit>(rhs);
+                    if (!rhsLit)
+                        continue;
+
+                    IRIntegerValue shiftAmount = rhsLit->getValue();
+
+                    IRInst* lhs = opShiftLeft->getOperand(0);
+                    IRUse lhsType = lhs->typeUse;
+
+                    // TODO: Not sure how to get the size of the type.
```
[the remark this answers is not in the document]
Comment (csyonghe) [reply source/slang/slang-ir-operator-shift-overflow.cpp:37]:
```
IRSizeAndAlignment sizeAlignment;
if (SLANG_SUCCEED(getNaturalSizeAndAlignment(lhs->getDataType(), sizeAlignment))
    ...
```

File: source/slang/slang-ir-operator-shift-overflow.cpp [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+                    {
+                        (void)lhsType;
+                        printf("JKWAK found 'operator<<' shifting by %" PRId64 "\n", shiftAmount);
+                        //sink->diagnose(child, Diagnostics::operatorShiftLeftOverflow);
+                    }
+                }
+            }
+        }
+
+        // TODO: Need to figure out if this can be just "inst->getChildren()"
```
[the remark this answers is not in the document]
Comment (csyonghe) [reply source/slang/slang-ir-operator-shift-overflow.cpp:47]: GetChildren should be fine. The difference is that getDecorationAndChildren also includes all decorations. There is no code inside decorations so it is fine to skip them.

File: source/slang/slang-ir-operator-shift-overflow.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (jkwak-work) [reply source/slang/slang-ir-operator-shift-overflow.cpp]: I couldn't use `getNaturalSizeAndAlignment()`.
The following is the funciton signature of it,
```
Result getNaturalSizeAndAlignment(CompilerOptionSet& optionSet, IRType* type, IRSizeAndAlignment* outSizeAndAlignment);
```
I couldn't provide the first argument.
This function is mostly called from "slang-emit-XXX.cpp", which has an access to "targetProgram".
But on my case, this function is called during "generateIR()", which is too early and don't have an access to "targetProgram" yet.

I had to manually get the type sizes but I am not sure about the size of "intptr_t" and "uintptr_t" cases.

[the remark this answers is not in the document]
Comment (csyonghe) [reply source/slang/slang-ir-operator-shift-overflow.cpp]: You can use the option from the linkage->m_optionSet. The linkage can be obtained from codeGenContext.

[the remark this answers is not in the document]
Comment (jkwak-work) [reply source/slang/slang-ir-operator-shift-overflow.cpp]: Thank you for the information. I will try it.

[the remark this answers is not in the document]
Comment (jkwak-work) [reply source/slang/slang-ir-operator-shift-overflow.cpp]: That worked and now the code looks cleaner.
Thank you for the help.

File: source/slang/slang-ir-operator-shift-overflow.cpp [hunk 3]
```diff
@@ -0,0 +1,66 @@
+// slang-ir-operator-shift-overflow.cpp
```
Comment (sriramm-nv) [inline source/slang/slang-ir-operator-shift-overflow.cpp:1]: please add a header with some details about this file.

File: source/slang/slang-diagnostic-defs.h [hunk 4]
```diff
@@ -740,6 +740,8 @@ DIAGNOSTIC(41021, Error, differentiableFuncMustHaveOutput, "a differentiable fun
 DIAGNOSTIC(41022, Error, differentiableFuncMustHaveInput, "a differentiable function must have at least one differentiable input.")
 DIAGNOSTIC(41023, Error, getStringHashMustBeOnStringLiteral, "getStringHash can only be called when argument is statically resolvable to a string literal")
 
+DIAGNOSTIC(41030, Warning, operatorShiftLeftOverflow, "left shift amount, `$1`, is bigger than the bit count of type, `$0`.")
```
Comment (sriramm-nv) [inline source/slang/slang-diagnostic-defs.h:743]: how about?
"left shift amount, `$1`, exceeds the maximum number of bits supported by the data type, `$0`.")

File: source/slang/slang-ir-operator-shift-overflow.cpp [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+#include "slang-ir-operator-shift-overflow.h"
```
Comment (sriramm-nv) [inline source/slang/slang-ir-operator-shift-overflow.cpp:2]: you might want to rename this into something more generic, so that additional checks can be added here. 

lets say, if you want to check for valid integer promotions for various other operators, other than shift..

File: source/slang/slang-ir-operator-shift-overflow.cpp [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+
+    class DiagnosticSink;
+    struct IRModule;
+
+    void checkForOperatorShiftOverflowRecursive(
+        IRInst* inst,
+        CompilerOptionSet& optionSet,
+        DiagnosticSink* sink)
+    {
+        if (auto code = as<IRGlobalValueWithCode>(inst))
```
Comment (sriramm-nv) [inline source/slang/slang-ir-operator-shift-overflow.cpp:19]: in some code,  i noticed that we have patterns like 
auto code = as<IRGlobalValueWithCode>(inst);
if (!code)
 continue;

this is done to keep the nesting managable. but I leave this up to you.

File: source/slang/slang-ir-operator-shift-overflow.cpp [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+
+                    IRInst* lhs = opShiftLeft->getOperand(0);
+                    IRType* lhsType = lhs->getDataType();
+
+                    IRSizeAndAlignment sizeAlignment;
+                    if (SLANG_FAILED(getNaturalSizeAndAlignment(optionSet, lhsType, &sizeAlignment)))
+                        continue;
+
+                    IRIntegerValue shiftAmount = rhsLit->getValue();
+                    if (sizeAlignment.size * 8 <= shiftAmount)
```
Comment (sriramm-nv) [inline source/slang/slang-ir-operator-shift-overflow.cpp:43]: instead of using a magic number 8, you may choose to define it as a const / compile-time macro.

File: tests/diagnostics/warning_operator_left_shift_overflow.slang [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+
+    uint result = (u8 << 0)
+        + (u8 << 1)
+        + (u8 << 2)
+        + (u8 << 3)
+        + (u8 << 4)
+        + (u8 << 5)
+        + (u8 << 6)
+        + (u8 << 7)
+        // CHECK-NOT: warning 41030:
```
Comment (sriramm-nv) [inline tests/diagnostics/warning_operator_left_shift_overflow.slang:19]: is this `check-not` required?

**Review by sriramm-nv — APPROVED** [review]
Overall I don't have any complaints with the implementation. Just some minor cleanup suggested. Please feel free to merge this as you see it fit

File: source/slang/slang-diagnostic-defs.h (hunk 4 above)
Comment (jkwak-work) [reply source/slang/slang-diagnostic-defs.h:743]: I like "exceeds" and "number of" is probably more natural in English expression than "count of".
I will change the message.
But there is no "maximum" nor minimum for the number of bits, so I will skip that word.

I am little more concerned about showing the "$1" in the middle of the message tho.
Probably I should move it to the end of the line like this,
```
left shift amount exceeds the number of bits, (`$0` << `$1`).
```

File: source/slang/slang-ir-operator-shift-overflow.cpp (hunk 5 above)
Comment (jkwak-work) [reply source/slang/slang-ir-operator-shift-overflow.cpp:2]: I may need to do it to handle the other operators.
But the approach for the other operators are not decided yet so I wouldn't be preemptive about it yet.

File: source/slang/slang-ir-operator-shift-overflow.cpp (hunk 6 above)
Comment (jkwak-work) [reply source/slang/slang-ir-operator-shift-overflow.cpp:19]: Aha, you are talking about the indentation.
You are right, I can change it here.

FYI, this line was copied from another file, slang-ir-missing-return.cpp.

File: source/slang/slang-ir-operator-shift-overflow.cpp (hunk 7 above)
Comment (jkwak-work) [reply source/slang/slang-ir-operator-shift-overflow.cpp:43]: I think 8 is pretty straight forward.
There is absolutely zero chance that the number 8 will be changed to other numbers like 7 or 9.
Using a constant variable for this seems an unnecessary overkill with less readability.

File: source/slang/slang-ir-operator-shift-overflow.cpp (hunk 3 above)
Comment (jkwak-work) [reply source/slang/slang-ir-operator-shift-overflow.cpp:1]: There is a chance that this file may evolve to do something more than what it does now.
It seems too early to write a descriptive comment for it at this point, because it will stale and add more cost of code/comment maintenance for no good reason.

File: source/slang/slang-ir-operator-shift-overflow.cpp (hunk 6 above)
Comment (jkwak-work) [reply source/slang/slang-ir-operator-shift-overflow.cpp:19]: It turned out I cannot do it for this case.
There is another block down there that needs to be executed regardless code is null pointer or not.

**Review by sriramm-nv — DISMISSED** [review]

**Comment by sriramm-nv** [comment]
looks good to me

File: source/slang/slang-ir-operator-shift-overflow.cpp [hunk 9]
```diff
@@ -0,0 +1,66 @@
...
+    void checkForOperatorShiftOverflowRecursive(
+        IRInst* inst,
+        CompilerOptionSet& optionSet,
+        DiagnosticSink* sink)
+    {
+        if (auto code = as<IRGlobalValueWithCode>(inst))
+        {
+            for (auto block : code->getBlocks())
+            {
+                for (auto opShiftLeft : block->getChildren())
```
Comment (csyonghe) [inline source/slang/slang-ir-operator-shift-overflow.cpp:23]: In the future we mostly likely are going to extend this pass to check for other operators as well. So might be good to turn this into
```
for (auto inst : block->getChildren())
{
    switch(inst->getOp()) { ... }
}
```

**Review by csyonghe — DISMISSED** [review]

File: source/slang/slang-ir-operator-shift-overflow.cpp (hunk 9 above)
Comment (jkwak-work) [reply source/slang/slang-ir-operator-shift-overflow.cpp:23]: `inst` is already in use.
I will go with... `opInst`

File: source/slang/slang-diagnostic-defs.h [hunk 10]
```diff
@@ -740,6 +740,8 @@ DIAGNOSTIC(41021, Error, differentiableFuncMustHaveOutput, "a differentiable fun
 DIAGNOSTIC(41022, Error, differentiableFuncMustHaveInput, "a differentiable function must have at least one differentiable input.")
 DIAGNOSTIC(41023, Error, getStringHashMustBeOnStringLiteral, "getStringHash can only be called when argument is statically resolvable to a string literal")
 
+DIAGNOSTIC(41030, Warning, operatorShiftLeftOverflow, "left shift amount exceeds the number of bits, (`$0` << `$1`).")
```
Comment (csyonghe) [inline source/slang/slang-diagnostic-defs.h:743]: Maybe also add that "..., the result is always 0."

**Review by csyonghe — APPROVED** [review]
