### PR TITLE
[GFX] Fix d3d12 buffer view creation logic for StructuredBuffers.

### LINKED ISSUE #3952: Allow GFX to automatically create D3D SRV based on the element type of a StructuredBuffer.

### PR DESCRIPTION
**Pull request by csyonghe**
Fixes #3952.

When binding a buffer resource to a StructuredBuffer parameter in D3D12, we need to specify an element stride. This stride can be derived from Slang's reflection info.

This change changes the logic in resource buffer view creation and binding, so that when binding a buffer to a buffer entry, we will create a specialized descriptor with the stride info, and cache the descriptor on the buffer view object.

### CODE REVIEW

File: tools/gfx/d3d12/d3d12-shader-object-layout.h [hunk 1]
```diff
@@ -66,6 +66,9 @@ class ShaderObjectLayoutImpl : public ShaderObjectLayoutBase
         /// as a sub-object.
         uint32_t subObjectIndex;
 
+        /// The stride of a structured buffer.
+        uint32_t bufferElementStride;
```
Comment (jkwak-work) [inline tools/gfx/d3d12/d3d12-shader-object-layout.h:70]: This variable may be used with an uninitialized value.

**Review by jkwak-work — DISMISSED** [review]

File: tools/gfx/d3d12/d3d12-shader-object-layout.h (hunk 1 above)
Comment (csyonghe) [reply tools/gfx/d3d12/d3d12-shader-object-layout.h:70]: We actually default initialize the whole struct whenever it is initialized, so this is fine.

**Review by jkwak-work — APPROVED** [review]

**Review by jkwak-work — APPROVED** [review]
