### PR TITLE
Fix a bug that warning 39001 can't be fully disabled.

### LINKED ISSUE #3108: Warning 39001 can't be fully disabled, also it's a bit of a questionable warning
Given a shader like the following: https://shader-playground.timjones.io/bf04ddc45bbb59ea22e72ae44b975cbb

You will get the following warnings:
```
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(3): warning 39001: explicit binding for parameter 'g_bindlessTexture3D' overlaps with parameter 'g_bindlessTexture2D'
[[vk::binding(1,0)]] Texture3D g_bindlessTexture3D[];
                               ^~~~~~~~~~~~~~~~~~~
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(2): note: see declaration of 'g_bindlessTexture2D'
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(3): warning 39001: explicit binding for parameter 'g_bindlessTexture3D' overlaps with parameter 'g_bindlessTexture2D'
[[vk::binding(1,0)]] Texture3D g_bindlessTexture3D[];
                               ^~~~~~~~~~~~~~~~~~~
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(2): note: see declaration of 'g_bindlessTexture2D'
```

Even after adding `-warnings-disable 39001`, slang will still output messages even though the warning was disabled:

```
[[vk::binding(1,0)]] Texture3D g_bindlessTexture3D[];
                               ^~~~~~~~~~~~~~~~~~~
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(2): note: see declaration of 'g_bindlessTexture2D'
[[vk::binding(1,0)]] Texture3D g_bindlessTexture3D[];
                               ^~~~~~~~~~~~~~~~~~~
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(2): note: see declaration of 'g_bindlessTexture2D'
```

I also think this warning is slightly questionable in the case of bindless resources - I think having overlapping bindings is the normal way one implements bindless texturing, having a descriptor for each texture type.  

That being said, this bug is really just about the fact that disabling this warning still produces output when it shouldn't.

### PR DESCRIPTION
**Pull request by csyonghe**
Fixes #3108.

### CODE REVIEW

File: source/slang/slang-parameter-binding.cpp [hunk 1]
```diff
@@ -946,11 +946,11 @@ static void addExplicitParameterBinding(
...
             else
             {
-                getSink(context)->diagnose(paramA, diagnosticInfo,
+                bool written = getSink(context)->diagnose(paramA, diagnosticInfo,
                     getReflectionName(paramA),
                     getReflectionName(paramB));
-
-                getSink(context)->diagnose(paramB, Diagnostics::seeDeclarationOf, getReflectionName(paramB));
+                if (written)
+                    getSink(context)->diagnose(paramB, Diagnostics::seeDeclarationOf, getReflectionName(paramB));
```
Comment (expipiplus1) [inline source/slang/slang-parameter-binding.cpp:953]: would it be too leetcode to write this new idiom as `diagnose(foo) && diagnose(bar)`?
