### PR TITLE
Fix ignored test count when retried

### LINKED ISSUE #7681: slang-test counts failed test as ignored when it is retired.
The retry logic has a problem that the failed test is counted as ignored.

```
● Bash(build/Debug/bin/slang-test.exe tests/compute/ieee754-nan-comparisons.slang -v)
  ⎿  Error: Supported backends: fxc dxc glslang spirv-dis clang visualstudio gcc genericcpp nvrtc llvm spirv-opt metal
     found test: 'tests/compute/ieee754-nan-comparisons.slang'
     ignored test: 'tests/compute/ieee754-nan-comparisons.slang'
     Retrying 1 failed tests...
     FAILED test: 'tests/compute/ieee754-nan-comparisons.slang'

     ===
     0% of tests passed (0/1), 1 tests ignored
     ===

     … +4 lines (ctrl+r to see all)

● The test is being ignored.
```

### PR DESCRIPTION
**Pull request by jvepsalainen-nv**
Fix counting failed test as ignored when it is retried

Fixes #7681

Do not add test result at the end of the test if the test failed
and is deferred for re-run.

In `TestReporter::_addResult()` update the test counters only if the current test results are valid. This prevents
errors in ignored and total test counts.

### CODE REVIEW

File: tools/slang-test/test-reporter.cpp [hunk 1]
```diff
@@ -145,7 +145,12 @@ void TestReporter::endTest()
 
     m_currentInfo.message = m_currentMessage;
 
-    _addResult(m_currentInfo);
+    // Only add the result if addResult() was explicitly called at least once.
+    // This prevents tests that are deferred for retry from being counted as "ignored".
+    if (m_numCurrentResults > 0)
```
Comment (jkwak-work) [inline tools/slang-test/test-reporter.cpp]: I am not sure how we can decide to add the result based on the count of the result.

I am still getting the same "1 ignored" message with the following command,
```
$ build/Release/bin/slang-test.exe  -enable-debug-layers true -api dx12  ./tests/compute/ieee754-nan-comparisons.slang
Supported backends: fxc dxc glslang spirv-dis clang visualstudio gcc genericcpp nvrtc llvm spirv-opt metal tint
Check vk,vulkan: Supported
Check dx12,d3d12: Supported
Check dx11,d3d11: Supported
Check cuda: Supported
Check wgpu,webgpu: Supported
ignored test: 'tests/compute/ieee754-nan-comparisons.slang (dx11)'
[tests/compute/ieee754-nan-comparisons.slang.1 syn (dx12)] slang-test: tests/compute/ieee754-nan-comparisons.slang:128:12: error: CHECK: expected string not found in input
 // CHECK: 0
           ^

[tests/compute/ieee754-nan-comparisons.slang.1 syn (dx12)] slang-test: actual-output:33:2: note: scanning from here
1
 ^

Retrying 1 failed tests...
[tests/compute/ieee754-nan-comparisons.slang.1 syn (dx12)] slang-test: tests/compute/ieee754-nan-comparisons.slang:128:12: error: CHECK: expected string not found in input
 // CHECK: 0
           ^

[tests/compute/ieee754-nan-comparisons.slang.1 syn (dx12)] slang-test: actual-output:33:2: note: scanning from here
1
 ^

FAILED test: 'tests/compute/ieee754-nan-comparisons.slang.1 syn (dx12)'

===
0% of tests passed (0/1), 1 tests ignored
===

1 failing tests:
---
tests/compute/ieee754-nan-comparisons.slang.1 syn (dx12)
---
```
I am intentionally making the test to fail in order to test it,
```
$ git diff
diff --git a/tests/compute/ieee754-nan-comparisons.slang b/tests/compute/ieee754-nan-comparisons.slang
index 70a252cb1..5ab50ea10 100644
--- a/tests/compute/ieee754-nan-comparisons.slang
+++ b/tests/compute/ieee754-nan-comparisons.slang
@@ -21,7 +21,7 @@ void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
     uint testIndex = 0;

     // Test 1: NaN == NaN should be false
-    // CHECK: 0
+    // CHECK: 1
     outputBuffer[testIndex++] = (fNAN == fNAN) ? 1u : 0u;

     // Test 2: NaN != NaN should be true
```

Comment (jvepsalainen-nv) [reply tools/slang-test/test-reporter.cpp]: dx11 gets ignored also when the test is not intentionally failing:
```
% ./build/Debug/bin/slang-test tests/compute/ieee754-nan-comparisons.slang                  
Supported backends: glslang spirv-dis clang genericcpp llvm spirv-opt metal
Check vk,vulkan: Not Supported
Check mtl,metal: Supported
Check cuda: Not Supported
ignored test: 'tests/compute/ieee754-nan-comparisons.slang (dx11)' 
passed test: 'tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)' 

===
100% of tests passed (1/1), 1 tests ignored
===
```

Without the fix and adding failure it includes the failing mtl test into ignored tests:
```
% ./build/Debug/bin/slang-test tests/compute/ieee754-nan-comparisons.slang
Supported backends: glslang spirv-dis clang genericcpp llvm spirv-opt metal
Check vk,vulkan: Not Supported
Check mtl,metal: Supported
Check cuda: Not Supported
ignored test: 'tests/compute/ieee754-nan-comparisons.slang (dx11)' 
[tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)] slang-test: tests/compute/ieee754-nan-comparisons.slang:128:12: error: CHECK: expected string not found in input
 // CHECK: 0
           ^

[tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)] slang-test: actual-output:33:2: note: scanning from here
1
 ^

ignored test: 'tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)' << BUG: add (mtl) test into ignored
Retrying 1 failed tests...
[tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)] slang-test: tests/compute/ieee754-nan-comparisons.slang:128:12: error: CHECK: expected string not found in input
 // CHECK: 0
           ^

[tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)] slang-test: actual-output:33:2: note: scanning from here
1
 ^

FAILED test: 'tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)' 

===
0% of tests passed (0/1), 2 tests ignored
===

1 failing tests:
---
tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)
---
```

With the fix the failing test is not part of ignored tests:
```
% ./build/Debug/bin/slang-test tests/compute/ieee754-nan-comparisons.slang
Supported backends: glslang spirv-dis clang genericcpp llvm spirv-opt metal
Check vk,vulkan: Not Supported
Check mtl,metal: Supported
Check cuda: Not Supported
ignored test: 'tests/compute/ieee754-nan-comparisons.slang (dx11)' 
[tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)] slang-test: tests/compute/ieee754-nan-comparisons.slang:128:12: error: CHECK: expected string not found in input
 // CHECK: 0
           ^

[tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)] slang-test: actual-output:33:2: note: scanning from here
1
 ^

Retrying 1 failed tests...
[tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)] slang-test: tests/compute/ieee754-nan-comparisons.slang:128:12: error: CHECK: expected string not found in input
 // CHECK: 0
           ^

[tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)] slang-test: actual-output:33:2: note: scanning from here
1
 ^

FAILED test: 'tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)' 

===
0% of tests passed (0/1), 1 tests ignored
===

1 failing tests:
---
tests/compute/ieee754-nan-comparisons.slang.1 syn (mtl)
---
```

Comment (jvepsalainen-nv) [reply tools/slang-test/test-reporter.cpp]: Using result counter to check if counters are updated was maybe not the clearest way to implement the fix. Added patch that use `m_testResultAdded` to check if result counters can be updated.

**Comment by jkwak-work** [comment]
I think... you may want to bring up a discussion about this to make the report more appropriate.

Currently slang-test reports a failed test as "ignored", but what it actually means is that "Failed and rescheduled for retry".
I think we should refactor to handle it properly.

By "properly", I mean that the current implementation of retry logic is a bit hacky and it is piggy backing on the logic initially for the ignored tests, because that was a way to treat the test as not failed.

But I think we should... refactor it in a way that there should be an explicit list for the failed-and-need-to-retry tests that is different from ignored tests.

**Comment by jvepsalainen-nv** [comment]
I see, retry logic is indeed a bit hacky. Current version fixes the issue in incorrect counting so that the retried tests are not counted as ignored and they are not counted twice in total test count but some refactoring would make it more clear.

File: tools/slang-test/slang-test-main.cpp [hunk 2]
```diff
@@ -5496,6 +5502,8 @@ SlangResult innerMain(int argc, char** argv)
         else
         {
             // If there are too many failed tests, don't bother retrying.
+            printf("Too many failed tests for retry(%d) - setting all to failed\n", (int)context.failedFileTests.getCount());
```
Comment (jvepsalainen-nv) [inline tools/slang-test/slang-test-main.cpp]: /format

File: tools/slang-test/test-reporter.cpp [hunk 3]
```diff
@@ -344,15 +340,27 @@ static void _appendTime(double timeInSec, StringBuilder& out)
...
     }
 
-    // If no result was added for this test it is deferred for retry
-    // Skip updating test counters
-    if (!m_testResultAdded)
+    // If test is pending retry, don't count it in any statistics yet
+    // The test will be re-run and reported again with a final result
+    if (info.testResult == TestResult::PendingRetry)
     {
+        printf("failed(pending retry) '%S'\n",
```
Comment (jvepsalainen-nv) [inline tools/slang-test/test-reporter.cpp]: /format

File: tools/unit-test/slang-unit-test.h [hunk 4]
```diff
@@ -8,10 +8,17 @@ enum class TestResult
...
     // overall.
-    Ignored,
-    Pass,
-    ExpectedFail,
-    Fail,
+    // NOTE! Do NOT reorder or change values 0-3. The slang-llvm prebuilt library depends on these.
+
+    // Special states with negative values (lowest precedence)
+    Uninitialized = -2, ///< Test result not yet set - initial state before any results are added
+    PendingRetry = -1,  ///< Test failed and is scheduled for retry - not counted in any statistics yet
```
Comment (jvepsalainen-nv) [inline tools/unit-test/slang-unit-test.h]: /format

**Review by expipiplus1 — APPROVED** [review]
This looks like a good improvement! thanks!
