### PR TITLE
Fix SPIR-V invalid default init interface values

### LINKED ISSUE #9462: Invalid SPIR-V generated for default-initialized interface variables
# Issue Description
Slangc generates invalid SPIR-V for default-initialized interface variables.

This is related to #9191. In case the related issue is resolved as to trigger an error for default-initialized interface variables, then this issue is no longer relevant.

# Reproducer Code

```slang
// test.slang
interface IHelper
{
    int getVal();
}

struct HelperImpl1 : IHelper
{
    int storedVal;

    int getVal() { return storedVal; }
}

IHelper test(int val)
{
    IHelper ret = { };

    switch (val % 4)
    {
    case 0:
    {
        ret = { HelperImpl1(val) };
        break;
    }

    default:
        break;
    }

    return ret;
}

RWStructuredBuffer<int> gOutputBuffer;

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    uint tid = dispatchThreadID.x;
    IHelper helper = test(int(tid));
    int outputVal = helper.getVal();
    gOutputBuffer[tid] = outputVal;
}
```

```SLANG_RUN_SPIRV_VALIDATION=1 /builds3/slang/build/RelWithDebInfo/bin/slangc -target spirv -stage compute -entry computeMain test.slang```

# Expected Behavior
Succesful compilation. Possibly a warning triggered (see #9191).

# Actual Behavior
SPIR-V validation enabled:

```
error: line 88: OpStore Pointer <id> '23[%ret]'s type does not match Object <id> '33[%33]'s type.
  OpStore %ret %33
...
(0): internal error 99999: Validation of generated SPIR-V failed.
```

# Environment
 - Slang Version: commit 25c1c6e5e08d3cb618c847e1d4dc24eb003bc199
 - Ubuntu 24.04
 - GPU/Driver version:  NVIDIA GeForce RTX 3080 / 580.105.08

# Additional context
N/A

### PR DESCRIPTION
**Pull request by NV-xiaoyongs**
Fixes #9462 

Add IR pass to fix mismatched default values on control-flow edges after existential lowering, preventing invalid OpStore type mismatches. Add regression unit test.

### CODE REVIEW

File: source/slang/slang-ir-fix-default-init-stores.cpp [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+
+#include "slang-ir-fix-default-init-stores.h"
+
+#include "slang-ir-inst-pass-base.h"
+#include "slang-ir-insts.h"
+
+namespace Slang
+{
+
+static bool _isDefaultValue(IRInst* inst)
```
Comment (skiminki-nv) [inline source/slang/slang-ir-fix-default-init-stores.cpp]: This feels like a workaround rather than fixing the actual issue. By default, I would have attempted the following in this order:

1. Identify the cases where `slangc` generates incorrectly typed defaults and fix that.; If this doesn't work:
2. Always emit `kIROp_DefaultConstruct` to signal default construction for a variable. Then, lower `kIROp_DefaultConstruct` into a type-specific concrete construction code using the concrete default value (possibly this pass).

The general problem with a fixup pass like this is that it's bound to regress silently when new types are added and the next person is not aware of this switch-case requiring updates. I also wonder whether it would be possible for this pass to incorrectly "fix" broken slang input by accepting a default value of a wrong type and converting that to the right type--although I guess earlier passes should have already caught that.

**Review by skiminki-nv — COMMENTED** [review]
I would like @csyonghe to take a look.

Other than possibly the general design, the code looks good to me.
