### PR TITLE
Filter out unused vertex attributes to fix WARNING-Shader-OutputNotConsumed

### LINKED ISSUE #7493: Vulkan validation layer warning: WARNING-Shader-OutputNotConsumed:
Following tests are affected:

- tests/compute/texture-sample-grad-offset-clamp.slang
- tests/compute/texture-sampling-no-1d-arrays.slang
- tests/compute/texture-sampling.slang

full output is:

```
warning: -937765618 - WARNING-Shader-OutputNotConsumed:
vkCreateGraphicsPipelines(): pCreateInfos[0].pVertexInputState Vertex attribute at location 3 not consumed by vertex shader.

warning: -937765618 - WARNING-Shader-OutputNotConsumed:
vkCreateGraphicsPipelines(): pCreateInfos[0].pVertexInputState Vertex attribute at location 4 not consumed by vertex shader.

warning: -937765618 - WARNING-Shader-OutputNotConsumed:
vkCreateGraphicsPipelines(): pCreateInfos[0].pVertexInputState Vertex attribute at location 5 not consumed by vertex shader.

warning: -937765618 - WARNING-Shader-OutputNotConsumed:
vkCreateGraphicsPipelines(): pCreateInfos[0].pVertexInputState Vertex attribute at location 6 not consumed by vertex shader.
```

The issue comes from the fact that the render pipeline built in render-test has a fixed layout that contains attributes not used in all test shaders. Not sure it's worth addressing or just live with the warning.

### LINKED ISSUE #7495: Enable Vulkan Validation Layers for CI
Slang should enable Vulkan Validation Layers when running tests in CI.

I've updated slang-rhi to enable more of the required extensions for SPIRV. PR is here https://github.com/shader-slang/slang/pull/7494

There are a number of remaining issues though, listed below.

Validation errors:

- https://github.com/shader-slang/slang/issues/7492
- https://github.com/shader-slang/slang/issues/7491
- https://github.com/shader-slang/slang/issues/7490
- https://github.com/shader-slang/slang/issues/4795
- https://github.com/shader-slang/slang/issues/4794

Validation warnings:

- https://github.com/shader-slang/slang/issues/7493

### PR DESCRIPTION
**Pull request by gtong-nv**
# Filter out unused vertex attributes to avoid VVL warning

This PR filters out unused vertex attributes when creating the input layout in `render-test` to resolve Vulkan Validation Layer (VVL) warnings. It uses the Slang Reflection API to query what attributes missing the binding info to filter out the unused attributes.

- Implements a new `filterInputElements` helper in `shader-input-layout.cpp` that inspects the vertex shader reflection data.
- Uses `collectUsedAttributes` to recursively traverse the entry point parameters and identify attributes (semantic "A") that are actually used and have valid bindings.
- Calculates the number of slots used by each attribute (handling matrices and varying input sizes correctly) to accurately mark used locations.
- Only the used attributes are passed to `createInputLayout`, preventing VVL warnings about unconsumed inputs.

## Fixes
- Fixes `WARNING-Shader-OutputNotConsumed` validation errors when running tests with VVL enabled.
- Closes #7495
- Closes #7493

### CODE REVIEW

File: tools/render-test/shader-input-layout.cpp [hunk 1]
```diff
@@ -1594,4 +1594,71 @@ void generateTextureDataRGB8(TextureData& output, const InputTextureDesc& inputD
...
+    }
+}
+
+List<InputElementDesc> filterInputElements(
+    const InputElementDesc* allInputElements,
+    int allInputElementsCount,
+    slang::ProgramLayout* programLayout)
+{
+    // Identify which attributes are actually used by the vertex shader
+    bool usedAttributes[7] = {false};
```
Comment (jkwak-work) [inline tools/render-test/shader-input-layout.cpp]: Where is the magic number 7 coming from?
And {false} is misleading. It only sets the first element as false and the rest elements are initialized by the default value of the type.
In other words, if it was {true}, it could have set only the first element to true and the rest to false.

I think it will be better to just use and empty brace, {}.

File: tools/render-test/shader-input-layout.cpp [hunk 2]
```diff
@@ -1594,4 +1594,71 @@ void generateTextureDataRGB8(TextureData& output, const InputTextureDesc& inputD
...
+            unsigned paramCount = entryPoint->getParameterCount();
+            for (unsigned j = 0; j < paramCount; j++)
+            {
+                collectUsedAttributes(entryPoint->getParameterByIndex(j), usedAttributes);
+            }
+        }
+    }
+
+    // Build the filtered list of input elements
+    List<InputElementDesc> inputElements;
```
Comment (jkwak-work) [inline tools/render-test/shader-input-layout.cpp:1655]: Probably it will be better to `reserve` when we know the max size and it is small

**Review by jkwak-work — DISMISSED** [review]
Looks good to me.

But we're we having VVL errors and ignoring them?
I think they should be treated as test failure if they are printed.

**Comment by gtong-nv** [comment]
https://github.com/shader-slang/slang/blob/master/tools/render-test/slang-support.h#L52

We only handle `Slang::DebugMessageType::Error`, but not `Slang::DebugMessageType::Warning`, so the VVL warnings are ignored for now. I have to turn on that to debug the issue.
But there are other Warning message (from both Vulkan and DX) and we can't treat them as failure. Will create a new ticket to track it

File: tools/render-test/shader-input-layout.cpp (hunk 2 above)
Comment (gtong-nv) [reply tools/render-test/shader-input-layout.cpp:1655]: done

File: tools/render-test/shader-input-layout.cpp (hunk 1 above)
Comment (gtong-nv) [reply tools/render-test/shader-input-layout.cpp]: It's the max number of input desc. I updated the code to use a HashSet to avoid maintaining the raw bool array and size

**Review by jkwak-work — APPROVED** [review]
Looks good to me
