### PR TITLE
Diagnostic for metal ref mesh output assignment

### LINKED ISSUE #7498: Slang produces broken mesh shader code when targeting Metal
I have the following "hello world" mesh shader function:

```slang
struct PushConst {
  float3 color;
  Texture2D.Handle texture;
};

[[push_constant]]
PushConst push_const;

struct VsOutput {
  float4 pos : SV_Position;
  float2 uv : TEXCOORD0;
  float4 color : COLOR0;
};

static const float4 POSITIONS[] = {
  float4(0.0, 1.0, 0.0, 1.0),
  float4(1.0, -1.0, 0.0, 1.0),
  float4(-1.0, -1.0, 0.0, 1.0),
};

static const float2 UVS[] = {
  float2(0.5, 0.0),
  float2(1.0, 1.0),
  float2(0.0, 1.0),
};

[shader("mesh")]
[numthreads(1, 1, 1)]
[outputtopology("triangle")]
void main_ms(out vertices VsOutput verts[3], out indices uint3 tris[1]) {
  SetMeshOutputCounts(3, 1);

  float4 color = float4(push_const.color, 1.0);

  // Output vertices
  for (uint i = 0; i < 3; i++) {
    verts[i].pos = POSITIONS[i];
    verts[i].uv = UVS[i];
    verts[i].color = color;
  }

  // Output indices
  tris[0] = uint3(0, 1, 2);
}

```

When compiling for Metal, this fails:

```bash
✦ ❯ ~/Downloads/slang-2025/bin/slangc -profile sm_6_6 -target metallib -o triangle.out ./shaders/triangle.slang
metal 32023.619: ./shaders/triangle.slang(38): error :  use of undeclared identifier '_S2'; did you mean '_S1'?
        _S2[i_0]->pos_0 = POSITIONS_0[i_0];
        ^~~
        _S1
metal 32023.619: ./shaders/triangle.slang(34): note :  '_S1' declared here
    float4 _S1 = float4(push_const_0->color_1, 1.0);
           ^
metal 32023.619: ./shaders/triangle.slang(38): error :  member reference type 'float' is not a pointer
        _S2[i_0]->pos_0 = POSITIONS_0[i_0];
        ~~~~~~~~  ^
metal 32023.619: ./shaders/triangle.slang(39): error :  use of undeclared identifier '_S2'; did you mean '_S1'?
        _S2[i_0]->uv_0 = UVS_0[i_0];
        ^~~
        _S1
metal 32023.619: ./shaders/triangle.slang(34): note :  '_S1' declared here
    float4 _S1 = float4(push_const_0->color_1, 1.0);
           ^
metal 32023.619: ./shaders/triangle.slang(39): error :  member reference type 'float' is not a pointer
        _S2[i_0]->uv_0 = UVS_0[i_0];
        ~~~~~~~~  ^
metal 32023.619: ./shaders/triangle.slang(40): error :  use of undeclared identifier '_S2'; did you mean '_S1'?
        _S2[i_0]->color_0 = _S1;
        ^~~
        _S1
metal 32023.619: ./shaders/triangle.slang(34): note :  '_S1' declared here
    float4 _S1 = float4(push_const_0->color_1, 1.0);
           ^
metal 32023.619: ./shaders/triangle.slang(40): error :  member reference type 'float' is not a pointer
        _S2[i_0]->color_0 = _S1;
        ~~~~~~~~  ^
6 errors generated.
```

```bash
✦ ❯ ~/Downloads/slang-2025/bin/slangc -profile sm_6_6 -target metal -o triangle.out ./shaders/triangle.slang

#include <metal_stdlib>
#include <metal_math>
#include <metal_texture>
using namespace metal;

#line 22 "./shaders/triangle.slang"
constant array<float2, int(3)> UVS_0 = { float2(0.5, 0.0), float2(1.0, 1.0), float2(0.0, 1.0) };

#line 16
constant array<float4, int(3)> POSITIONS_0 = { float4(0.0, 1.0, 0.0, 1.0), float4(1.0, -1.0, 0.0, 1.0), float4(-1.0, -1.0, 0.0, 1.0) };

#line 10
struct VsOutput_0
{
    float4 pos_0 [[position]];
    float2 uv_0 [[user(TEXCOORD0)]];
    float4 color_0 [[user(COLOR0)]];
};


#line 2
struct PushConst_0
{
    float3 color_1;
    texture2d<float, access::sample> texture_0;
};


#line 31
[[mesh]] void main_ms(metal::mesh<VsOutput_0, void, int(3), int(1), metal::topology::triangle> _slang_mesh, PushConst_0 constant* push_const_0 [[buffer(0)]])
{

#line 32
    _slang_mesh.set_primitive_count((1U));

    float4 _S1 = float4(push_const_0->color_1, 1.0);

#line 34
    uint i_0 = 0U;


    for(;;)
    {

#line 37
        if(i_0 < 3U)
        {
        }
        else
        {

#line 37
            break;
        }

#line 38
        _S2[i_0]->pos_0 = POSITIONS_0[i_0];
        _S2[i_0]->uv_0 = UVS_0[i_0];
        _S2[i_0]->color_0 = _S1;

#line 37
        i_0 = i_0 + 1U;

#line 37
    }

#line 44
    _slang_mesh.set_index(0U*3+0,(uint3(0U, 1U, 2U))[0]);
    _slang_mesh.set_index(0U*3+1,(uint3(0U, 1U, 2U))[1]);
    _slang_mesh.set_index(0U*3+2,(uint3(0U, 1U, 2U))[2]);
    ;

#line 45
    return;
}

```

It looks like instead of using `POSITIONS_0` and `UVS_0`, it attempts to fetch data from non existing `_S2`.

```
✦ ❯ ~/Downloads/slang-2025/bin/slangc -version
2025.10.4
```

### PR DESCRIPTION
**Pull request by jhelferty-nv**
When slang detects assignment to a mesh output reference on metal, generate a diagnostic message. (Metal mesh shader outputs must be assigned via 'set' instead of 'ref'.)

Fixes #7498

### CODE REVIEW

**Comment by jhelferty-nv** [comment]
This change is failing in CI, but only on the [build (linux, release, gcc, x86_64)](https://github.com/shader-slang/slang/actions/runs/17467259031/job/49619262449?pr=8365#logs) variant.

With a bit of local testing, it looks like it might be a result of using `metallib` instead of `metal` as the target? In this particular release build it looks like reporting the absence of the `metal` compiler might interfere somehow with reporting the new error I added.

I'll update the test to use `-target metal`.

**Comment by jkwak-work** [comment]
I am a little confused about this PR.
1. I think the repro shader should compile and get the mesh shader working for Metal. I don't understand why @tangent-vector suggested it to error out. If ref is not available on Metal, shouldn't we legalize it to make it working?
2. If we want to error it out, I think it should be handled by the capability. I see the following lines and it looks like it should be already error out. If this is not working properly, we need to fix it and make the capability handle the error,
```
struct OutputVertices
{
        [require(glsl_hlsl_spirv, meshshading)] // <====== ref is not available for metal
        __intrinsic_op($(kIROp_MeshOutputRef))
        ref;
 ```

File: source/slang/slang-diagnostic-defs.h [hunk 1]
```diff
@@ -2960,6 +2960,11 @@ DIAGNOSTIC(
     Error,
     divisionByMatrixNotSupported,
     "division by matrix is not supported for Metal and WGSL targets.")
+DIAGNOSTIC(
+    56103,
+    Error,
+    assignToRefNotSupported,
+    "assignment to mesh output member via reference not supported for Metal target.")
```
Comment (jkwak-work) [inline source/slang/slang-diagnostic-defs.h]: I am not sure if this error message is good enough for the end-users to fix the problem to use `set` method rather than `ref`.

Comment (jhelferty-nv) [reply source/slang/slang-diagnostic-defs.h]: Can you help refine the diagnostic message? How about "assignment to mesh output must be at vertex granularity for Metal target."

Comment (jkwak-work) [reply source/slang/slang-diagnostic-defs.h]: I like to suggest the following,
```
Metal requires the whole struct to be assigned at once to Mesh output.
```

**Review by jkwak-work — APPROVED** [review]
Looks good to me.

I had to go through some learning curve to understand the intention of the changes.
Thanks for all the explanations.

**Comment by jhelferty-nv** [comment]
@jkwak-work I've updated the diagnostic based on your feedback. I also noticed that the error number I originally picked was already used elsewhere, so I incremented by one. Mind reapproving?

**Review by jkwak-work — APPROVED** [review]
Looks good to me
