### PR TITLE
Lookup refactor

### LINKED ISSUE #8201: Crash when defining properties returning associated types in interfaces
```slang
// main.slang
interface IMLP<T, int In, int Out>
{
    associatedtype Parameters : IDifferentiablePtrType;
    associatedtype Configuration;

    property Parameters parameters { get; }
    property Configuration configuration { get; }
    property DifferentialPtrPair<Parameters> parametersDual { get; }
}
```

When compiling the code above with `slangc main.slang` I get:

```
main.slang: note 99999: an internal error threw an exception while working on code near this location
    property DifferentialPtrPair<Parameters> parametersDual { get; }
                                                              ^~~
```

### PR DESCRIPTION
**Pull request by kaizhangNV**
Close #8201.

This PR unify the lowering logic for LookupDeclRef of an interface requirement. We will always lower this AST node to a
LookupWitness IR. The key of this IR is the special witnessTableType `ThisTypeWitness`, this witness Table is simply a wrapper for an interface type. Our current specialization pass doesn't handle this kind of LookupWitness IR at all, so we
will also add the specialization of this type IR as well.

### CODE REVIEW

File: source/slang/slang-lower-to-ir.cpp [hunk 1]
```diff
@@ -9410,8 +9410,13 @@ struct DeclLoweringVisitor : DeclVisitor<DeclLoweringVisitor, LoweredValInfo>
             context->astBuilder,
             createDefaultSpecializedDeclRef(subContext, nullptr, decl->getThisTypeDecl()));
         subContext->thisType = thisType;
-        // Create a stand-in witness that represents `ThisType` conforms to the interface.
-        subContext->thisTypeWitness = subBuilder->createThisTypeWitness((IRType*)finalVal);
+        {
+            IRBuilderInsertLocScope insertScope(subBuilder);
+            subBuilder->setInsertInto(subBuilder->getModule());
```
Comment (csyonghe) [inline source/slang/slang-lower-to-ir.cpp]: I wonder why is this needed. We should just make whatever IR inst that reprents "this_witness" a hoistable inst and let the ir builder automatically determine the scope.

File: source/slang/slang-lower-to-ir.cpp [hunk 2]
```diff
@@ -11838,88 +11834,31 @@ LoweredValInfo emitDeclRef(IRGenContext* context, Decl* decl, DeclRefBase* subst
...
-            //
-            auto irSatisfyingVal = context->irBuilder->emitLookupInterfaceMethodInst(
-                type,
-                irWitnessTable,
-                irRequirementKey);
-            return LoweredValInfo::simple(irSatisfyingVal);
-        }
-        else
-        {
-            // This case is a reference to a member declaration of the interface
```
Comment (csyonghe) [inline source/slang/slang-lower-to-ir.cpp:11897]: I think this branch is still needed, because we could still have interface members that does not represent a requirement. For example, 
```
interface Foo { struct P { int x; }; }
```

simply defines `Foo::P` as an ordinary type.

Our language does not allow user code that does this, but there could be some synthesis logic that adds ordinary members to an interface like this.

Comment (kaizhangNV) [reply source/slang/slang-lower-to-ir.cpp:11897]: Oh, that's the 1st time I heard about this.

File: source/slang/slang-lower-to-ir.cpp (hunk 1 above)
Comment (kaizhangNV) [reply source/slang/slang-lower-to-ir.cpp]: right, updated.

File: source/slang/slang-lower-to-ir.cpp [hunk 3]
```diff
@@ -11857,40 +11884,23 @@ LoweredValInfo emitDeclRef(IRGenContext* context, Decl* decl, DeclRefBase* subst
...
-                // defined in some base interface from an interface type.
-                // For now we just lower that decl as if it is referenced
-                // from the same interface directly, e.g. a reference to
-                // IBase.AssocType from IDerived:IBase will be lowered as
-                // IRAssocType(IBase).
-                // We may want to consider unifying our IR representation to
-                // represent associated types with lookupWitness inst even inside
-                // interface definitions.
-                return emitDeclRef(
+                // Copy ThisTypeWitness locally if necessary
```
Comment (csyonghe) [inline source/slang/slang-lower-to-ir.cpp:11891]: Why do we need to copy here? Won't the `lowerSimpleVal` process create the `thisWitness` at the current scope of builder?

Comment (kaizhangNV) [reply source/slang/slang-lower-to-ir.cpp:11891]: No, we could still reference `thisWitness` defined in original interface generic.
