### PR TITLE
Fix div-by-zero error during sccp.

### LINKED ISSUE #2892: Divide by 0 causes crash in SCCP
Take 

```
//TEST(compute):COMPARE_COMPUTE_EX:-slang -compute -shaderobj -output-using-type
//TEST(compute, vulkan):COMPARE_COMPUTE_EX:-vk -compute -shaderobj -output-using-type
//TEST(compute, vulkan):COMPARE_COMPUTE_EX:-cpu -compute -shaderobj -output-using-type
//TEST(compute, vulkan):COMPARE_COMPUTE_EX:-cuda -compute -shaderobj -output-using-type

//TEST_INPUT:ubuffer(data=[0], stride=4):out,name outputBuffer
RWStructuredBuffer<uint> outputBuffer;

uint check<let b : bool>()
{
    return 1 / int(b);
}

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
	uint tid = dispatchThreadID.x;
    
    uint a = check<false>();
    uint b = check<true>();
    
	outputBuffer[tid] = a + b; 
}
```

Crashes in 

LatticeVal evalDiv(IRType* type, LatticeVal v0, LatticeVal v1)

When dividing v0 by 0.

Perhaps there should be an Error or DivBy0 or some other Flavor to represent this result. This could then be detected and cause termination, with a suitable diagnostic. 

I had assumed that this issue was in part due to being generic, and therefore would appear in IR passes because that's where generic specialization takes place. But will also fail with 

```
int doThing(int v) { return v; }
doThing(1 / 0);
```

### PR DESCRIPTION
**Pull request by csyonghe**
Fixes #2892.

### CODE REVIEW

File: source/slang/slang-ir-ssa-simplification.h [hunk 1]
```diff
@@ -5,13 +5,14 @@ namespace Slang
 {
     struct IRModule;
     struct IRGlobalValueWithCode;
+    class DiagnosticSink;
 
     // Run a combination of SSA, SCCP, SimplifyCFG, and DeadCodeElimination pass
     // until no more changes are possible.
-    void simplifyIR(IRModule* module);
+    void simplifyIR(IRModule* module, DiagnosticSink* sink = nullptr);
```
Comment (jsmall-nvidia) [inline source/slang/slang-ir-ssa-simplification.h:12]: The sink seems to be the mechanism to report the error to caller. Should we require a sink to be passed?

**Review by jsmall-nvidia — APPROVED** [review]

File: source/slang/slang-ir-ssa-simplification.h (hunk 1 above)
Comment (csyonghe) [reply source/slang/slang-ir-ssa-simplification.h:12]: There are several calls to `simplifyIR` from a pass that currently don't have access to `sink`. Plumbing `sink` through every pass feels messy. We should probably have a base context type for a pass that carries the sink over to simplify things. But for now this is fine since all errors will eventually be captured by a `simplifyIR` call in `linkAndOptimizeIR`, where a sink is provided there. When `sink` is not provided, the compilation can still continue normally upon a div-by-zero error (we simply don't fold).
