### PR TITLE
Dyn dispatch fix varying io

### LINKED ISSUE #10403: ICE when using interface type in varying (inter-stage) parameters
# ICE when using interface type in varying (inter-stage) parameters

## Issue Description

Using an interface type directly in a varying (inter-stage) parameter position causes an internal compiler error (`SLANG_UNEXPECTED("unhandled type kind")`). This affects interface-typed fields in vertex output / fragment input structs, direct interface-typed entry point parameters, interface-typed return values, and compound types containing interfaces (arrays, Optional).

## Reproducer Code

```hlsl
interface IFoo
{
    float getValue();
}

struct ImplA : IFoo
{
    float x;
    float getValue() { return x; }
}

struct VertexOutput
{
    IFoo foo : TEXCOORD0;
    float4 pos : SV_Position;
}

[shader("vertex")]
VertexOutput vertexMain(float3 position : POSITION)
{
    VertexOutput output;
    ImplA a;
    a.x = 1.0;
    output.foo = a;
    output.pos = float4(position, 1.0);
    return output;
}
```

**Command:**
```bash
slangc test.slang -target spirv
```

## Expected Behavior

The compiler should emit a clear diagnostic rejecting interface types in varying parameters, such as `error[E39028]: parameter 'foo' is not a valid varying parameter`. Interface types carry runtime type tags and witness tables that cannot be interpolated between pipeline stages.

## Actual Behavior

```
error[E99999]: Slang compilation aborted due to an exception of N5Slang13InternalErrorE unexpected: unhandled type kind
```

The same crash occurs on all targets (spirv, hlsl, glsl, metal, wgsl) and for all positions: struct fields, direct parameters, return types, arrays of interface, and Optional wrapping interface.

Note: concrete structs implementing interfaces work correctly as varying parameters (they are fully resolved types with known layout).

## Test Plan

Enable the following disabled tests after the fix:
- `tests/language-feature/dynamic-dispatch/diagnose-interface-varying-output.slang`
- `tests/language-feature/dynamic-dispatch/diagnose-interface-varying-input.slang`
- `tests/language-feature/dynamic-dispatch/diagnose-interface-varying-compound.slang`

### PR DESCRIPTION
**Pull request by jvepsalainen-nv**
The parameter binding code in `processEntryPointVaryingParameter` handles
`DeclRefType` by checking for specific declaration kinds (StructDecl,
GlobalGenericParamDecl, EnumDecl, AssocTypeDecl) but did not handle
InterfaceDecl. When an interface type appeared in a varying parameter
position, the code fell through to `SLANG_UNEXPECTED("unhandled type
kind")`, causing an internal compiler error.

Interface types carry runtime type tags and witness tables that cannot be
interpolated between pipeline stages, so they are fundamentally invalid
as varying parameters. The fix adds InterfaceDecl to the handled cases,
returning nullptr to signal an unsupported type -- the same pattern used
for TextureType, SamplerStateType, ConstantBufferType, and other types
that are invalid in varying positions.

Three additional changes harden the error handling paths:

- Array element type: added nullptr check after processing the element
  type layout, preventing a null dereference when the element type is
  unsupported (e.g. IFoo[2] as varying).

- Top-level parameters: replaced SLANG_ASSERT + silent skip with an
  explicit E39028 diagnostic, so the user gets a clear error when an
  interface type is used as a direct entry point varying parameter.

- Return types: added E39028 diagnostic when the entry point return
  type layout is null, and skip setting the result layout to prevent
  downstream crashes in IR passes.

Fixes #10403

### CODE REVIEW

File: source/slang/slang-parameter-binding.cpp
Comment (skiminki-nv) [inline source/slang/slang-parameter-binding.cpp:2033]: This function needs a comment that it returns nullptr for invalid varying parameters

File: source/slang/slang-parameter-binding.cpp [hunk 1]
```diff
@@ -2231,6 +2231,9 @@ static RefPtr<TypeLayout> processEntryPointVaryingParameter(
                 state,
                 varLayout);
 
+            if (!elementTypeLayout)
```
[the remark this answers is not in the document]
Comment (jvepsalainen-nv) [reply source/slang/slang-parameter-binding.cpp:2242]: done

File: source/slang/slang-parameter-binding.cpp
Comment (jvepsalainen-nv) [reply source/slang/slang-parameter-binding.cpp:2033]: Added comment
