### PR TITLE
Enable Vulkan-SPIRV validation rules, and fix all validation errors.

### LINKED ISSUE #8743: Invalid explicit layout decorations on type for operand
# Issue Description

There is a new validation error with Vulkan 1.4.328 and Slang 2025.19

# Reproducer Code

Use the attached file and execute
```
 spirv-val foundation.slang.spv --relax-block-layout --uniform-buffer-standard-layout --scalar-block-layout --allow-localsizeid --target-env vulkan1.4
```

# Expected Behavior

No validation error

# Actual Behavior

There is a validation error:

```
vulkan1.4error: line 1481: [VUID-StandaloneSpirv-None-10684] Invalid explicit layout decorations on type for operand '84[%_ptr_Function_GltfMesh_natural]'
  %85 = OpVariable %_ptr_Function_GltfMesh_natural Function
```

# Environment
 - Slang Version: 2025.19
 - OS : Windows 11

# Files

[foundation.slang.zip](https://github.com/user-attachments/files/22969805/foundation.slang.zip)

### PR DESCRIPTION
**Pull request by csyonghe**
We aren't calling spirv validation with vulkan rules, and have been generating invalid spirv in many of our tests.

This PR enables these validation rules, and fixed all failing tests.

Closes #8743.

### CODE REVIEW

File: source/slang-glslang/slang-glslang.cpp [hunk 1]
```diff
@@ -169,9 +169,10 @@ extern "C"
 #else
     __attribute__((__visibility__("default")))
 #endif
-        bool glslang_validateSPIRV(const uint32_t* contents, int contentsSize)
+    bool
+    glslang_validateSPIRV(const uint32_t* contents, int contentsSize)
 {
-    spv_target_env target_env = SPV_ENV_UNIVERSAL_1_6;
+    spv_target_env target_env = SPV_ENV_VULKAN_1_4;
```
Comment (jkwak-work) [inline source/slang-glslang/slang-glslang.cpp:174]: The default value in spirv-val.exe is still `SPV_ENV_UNIVERSAL_1_6`:
```
  spv_target_env target_env = SPV_ENV_UNIVERSAL_1_6;
```
https://github.com/KhronosGroup/SPIRV-Tools/blob/021f92a757002fcdba6a73154ed46a203d3a56b8/tools/val/val.cpp#L135

But it has a command-line argument, `--target-env`, that can override it:
https://github.com/KhronosGroup/SPIRV-Tools/blob/021f92a757002fcdba6a73154ed46a203d3a56b8/tools/val/val.cpp#L190-L193

I am not sure how we can improve this without using one fixed value.

Comment (csyonghe) [reply source/slang-glslang/slang-glslang.cpp:174]: Since we are generating spirv for vulkan, we should always use the vulkan environment.

File: source/slang/slang-ir-glsl-legalize.cpp [hunk 2]
```diff
@@ -1656,26 +1666,15 @@ ScalarizedVal createSimpleGLSLGlobalVarying(
...
-                    // Array sizes differ, need type adapter
-                    RefPtr<ScalarizedTypeAdapterValImpl> typeAdapter =
-                        new ScalarizedTypeAdapterValImpl;
-                    typeAdapter->actualType = systemValueInfo->requiredType;
-                    typeAdapter->pretendType = builder->getArrayType(inType, declaredArraySize);
-                    typeAdapter->val = val;
-
-                    val = ScalarizedVal::typeAdapter(typeAdapter);
-                    break;
                 }
```
Comment (jkwak-work) [inline source/slang/slang-ir-glsl-legalize.cpp:1669]: Don't we need `break` here?
The comment says
> // Find first array declarator 

So it sounds like it should stop after handling the first array.

File: source/slang/slang-ir-inline.cpp [hunk 3]
```diff
@@ -1023,6 +1031,37 @@ struct TypeInliningPass : InliningPassBase
                     return false;
                 return true;
             }
+        case kIROp_BorrowInParamType:
+        case kIROp_BorrowInOutParamType:
+            {
+                if (shouldInlineBorrowRefTypesForSPIRV)
```
Comment (jkwak-work) [inline source/slang/slang-ir-inline.cpp:1037]: It looks like we can reduce the indentation if we have,
```
if (!shouldInlineBorrowRefTypesForSPIRV)
    return false;
```

File: tests/ir/dump-module.slang [hunk 4]
```diff
@@ -4,7 +4,7 @@
 // is to see the file you requested. If there's a bug in slang-module output, it's
 // important that -dump-module looks at the specific file you requested.
 
-//TEST:COMPILE: tests/ir/dump-module.slang -o tests/ir/dump-module.slang-module -target spirv -embed-downstream-ir
+//TEST:COMPILE: tests/ir/dump-module.slang -o tests/ir/dump-module.slang-module -target spirv -embed-downstream-ir -skip-spirv-validation
```
Comment (jkwak-work) [inline tests/ir/dump-module.slang:7]: I am wondering why we need `-skip-spirv-validation` on a few tests.
When the output file name is `*.slang-module`, doesn't it make the validation skip with the following code?
```
    if (optionSet.getBoolOption(CompilerOptionName::SkipSPIRVValidation) ||
        optionSet.getBoolOption(CompilerOptionName::IncompleteLibrary)) // <=== THIS?
        return false;
```

Comment (csyonghe) [reply tests/ir/dump-module.slang:7]: This particular tests uses spirv linkage decoration which is still experimental and not part of Vulkan-spirv.
