### PR TITLE
Handle uninitialized resources in structs

### LINKED ISSUE #8443: [SPIRV] Slang producing invalid spir-v for Texture2D in struct conditionally initialized and used
# Issue Description
Given the following example shader, the SPIR-V produced contains the error:
```
error: line 40: OpConstantComposite Result Type <id> '10[%10]' is not a composite type.
  %41 = OpConstantComposite %10
```

# Reproducer Code
The example shader:
```
Texture2D<float4> tex1;
SamplerState samp;

struct S {
    float2 uv;
    Texture2D<float4> t;
};

float4 main(float2 coord : TEXCOORD0, float param : TEXCOORD1) : SV_Target {
    bool b = (param > 0.5);

    S s = (S)0;
    s.uv = coord;

    if (b) {
        s.t = tex1;
    }

    float4 col = float4(0,0,0,1);

    if (b) {
        col = s.t.Sample(samp, s.uv);
    }

    return col;
}
```
Compiled with: 
```
slangc.exe -profile sm_6_0 -target spirv -entry main -stage pixel -o output.spv repro.hlsl
```
# Expected Behavior
slang should produce valid SPIR-V or produce an error in this case.

# Actual Behavior
Invalid SPIR-V generated.

# Environment
 - Slang Version (release version number or commit hash): 2025.16.1

### PR DESCRIPTION
**Pull request by jhelferty-nv**
Fixes #8443

Aggregate types consisting of or containing an opaque type are no longer considered C-style types.

This has the side-effect of disallowing default-initialization. e.g., the following are now errors:
```slang
struct S { float4 v; Texture2D<float4> tex; }
S s1 = (S)0; // error
S s2 = {}; // error
```

### CODE REVIEW

File: source/slang/slang-check-conversion.cpp [hunk 1]
```diff
@@ -127,6 +127,19 @@ bool SemanticsVisitor::_readValueFromInitializerList(
...
+        // Resource types can only ever be bound to parameters.
+        // But there is likely a fair amount of legacy code
+        // out there that depends on it being true. This should
+        // eventually be an error, but for now it's a warning.
+        if (auto resourceType = as<ResourceType>(toType))
+        {
+            getSink()->diagnose(
+                fromInitializerListExpr->loc,
+                Diagnostics::cannotUseInitializerListForResourceType,
+                toType);
```
Comment (jhelferty-nv) [inline source/slang/slang-check-conversion.cpp]: So the one downside here is that instead of the one warning, we end up with two warnings, because a later chunk of code notices that the source is uninitialized:
```
tests/spirv/zero-init-tex2d-field.slang(27): warning 30506: cannot use initializer list for resource type 'Texture2D<vector<float,4>>'
    S s = (S)0;
          ^
tests/spirv/zero-init-tex2d-field.slang(27): warning 41016: use of uninitialized variable ''
    S s = (S)0;
          ^
```

Comment (jhelferty-nv) [reply source/slang/slang-check-conversion.cpp]: I've copied over `diagnoseOnce` pattern to fix this.

File: source/slang/slang-check-conversion.cpp [hunk 2]
```diff
@@ -127,6 +127,21 @@ bool SemanticsVisitor::_readValueFromInitializerList(
...
+        // out there that depends on it being true. This should
+        // eventually be an error, but for now it's a warning.
+        // Use diagnoseOnce to avoid duplicate warnings when iterating
+        // over array elements or struct fields.
+        if (as<ResourceType>(toType))
+        {
+            diagnoseOnce(
+                fromInitializerListExpr->loc,
+                Diagnostics::cannotDefaultInitializeResourceType,
+                toType);
```
Comment (jhelferty-nv) [inline source/slang/slang-check-conversion.cpp]: New problem. If we put the check in here, then it'll get triggered by something as innocuous as:
```slang
struct Test1 {
  float value;
  Texture2D<float4> tex[2];
};
ParameterBlock<Test1> test1;
```
That's because we create a default constructor while checking the struct, and when we attempt to build one for the array it uses the coerce initializer list path. Hm

Comment (jhelferty-nv) [reply source/slang/slang-check-conversion.cpp]: Addressed this by iterating for warnings separately. Putting the diagnostic in the original location would probably work if this were an error and we were stopping immediately, but we want to generate all possible warnings and then continue, so .. for now, let's go with a separate iteration path.

File: source/slang/slang-check-conversion.cpp [hunk 3]
```diff
@@ -929,6 +929,104 @@ bool SemanticsVisitor::_readAggregateValueFromInitializerList(
...
+        // For other types (scalars, vectors, matrices), one argument is consumed
+        ioArgIndex++;
+        return;
+    }
+
+    // No more arguments - this type will be default-initialized
+    // Check if it contains resource types
+    if (as<ResourceType>(type))
+    {
+        getSink()->diagnose(loc, Diagnostics::cannotDefaultInitializeResourceType, type);
```
Comment (jhelferty-nv) [inline source/slang/slang-check-conversion.cpp]: This warning is arguably a bit redundant with the one happening in slang-ir-use-uninitialized-values.cpp, except that that one happens late enough that it won't show up via the language server. So I've added this one at the front end.

This check had originally been up before line 132, but that logic has different stopping conditions. It seemed preferable to make it its own thing rather than try to make the other code do two things.

File: source/slang/slang-ir-use-uninitialized-values.cpp [hunk 4]
```diff
@@ -640,7 +640,19 @@ static void checkUninitializedValues(IRFunc* func, DiagnosticSink* sink)
...
+                               inst->findDecoration<IRLinkageDecoration>() != nullptr;
+
+                if (hasName)
+                {
+                    sink->diagnose(load, Diagnostics::usingUninitializedVariable, inst);
+                }
+                else
+                {
+                    // For poison ops and other unnamed instructions, show type instead
+                    sink->diagnose(load, Diagnostics::usingUninitializedValue, type);
```
Comment (jhelferty-nv) [inline source/slang/slang-ir-use-uninitialized-values.cpp:654]: When assigning a zero-initialized value to a struct containing a resource, the resource ends up with an unnamed `Poison` value. This resulted in an empty string for the variable name. I wanted to make this at least half-way useful, so I fall back to printing the type.

File: source/slang/slang-check-decl.cpp [hunk 5]
```diff
@@ -9681,7 +9689,27 @@ void SemanticsDeclBodyVisitor::visitParamDecl(ParamDecl* paramDecl)
...
+        // init context.
+        bool isSynthesizedCtorParam = false;
+        if (auto ctorDecl = as<ConstructorDecl>(paramDecl->parentDecl))
+        {
+            isSynthesizedCtorParam = ctorDecl->findModifier<SynthesizedModifier>() != nullptr;
+        }
+
+        if (isSynthesizedCtorParam)
+        {
+            SemanticsVisitor subVisitor(withInSynthesizedDefaultInit());
```
Comment (kaizhangNV) [inline source/slang/slang-check-decl.cpp]: This feels not always correct.

If there are other failures in the `coerce`, you will ignore it as well.

So I think we should also check if there are other warnings/errors returned by the subVisitor.

File: source/slang/slang-check-decl.cpp [hunk 6]
```diff
@@ -2677,14 +2680,18 @@ static Expr* constructDefaultConstructorForType(SemanticsVisitor* visitor, Type*
...
         initListExpr->type = visitor->getASTBuilder()->getInitializerListType();
         Expr* outExpr = nullptr;
         auto fromType = type;
         if (auto atomicType = as<AtomicType>(fromType))
         {
             fromType = atomicType->getElementType();
         }
-        if (visitor->_coerceInitializerList(fromType, &outExpr, initListExpr))
+        // Use a sub-visitor with the synthesized default init flag set to suppress
+        // warnings about default-initializing resource types.
```
Comment (jhelferty-nv) [inline source/slang/slang-check-decl.cpp]: TODO: Add sample slang code of what we're trying to suppress?

File: source/slang/slang-check-decl.cpp (hunk 5 above)
Comment (jhelferty-nv) [reply source/slang/slang-check-decl.cpp]: TODO (talking with Kai)
- Improve explanation of why
- Add some lines of slang code, example of what will hit this issue

**Comment by jhelferty-nv** [comment]
Based on offline discussion, it sounds like we want to consider `S s = S(0);` to be an error whenever `S` contains an opaque type. Revising..

File: source/slang/slang-check-decl.cpp (hunk 5 above)
Comment (jhelferty-nv) [reply source/slang/slang-check-decl.cpp]: This logic is probably more trouble than it's worth, so I'll switch it out for the `diagnoseOnce` pattern, even though that means we'll be missing real duplicate diagnostics. Seems like a reasonable trade-off.

(Just to close the loop, since it may be unclear what I was doing: If you look at `withInSynthesizedDefaultInit()` I was creating a sub-context (copy of original) and seting a boolean variable on it. This is the standard pattern for nesting contexts and changing variables on them, and does not otherwise impact diagnostic reporting.)
