### PR TITLE
Eliminate empty structs during type legalization

### LINKED ISSUE #574: GLSL compiler on Vulkan doesn't accept empty structs
To repeat run render-test with the following options 

```
tests/bugs/gh-357.slang -vk -slang -compute -o tests/bugs/gh-357.slang.2.actual.txt
```

This generates the following error from glslang compiler

```
ERROR: slang:4: '' :  syntax error, unexpected RIGHT_BRACE
ERROR: 1 compilation errors.  No code generated.
```

The code that slang has generated is 

```
#version 450
struct BaseImpl_0
{
};

float BaseImpl_getVal_0(BaseImpl_0 this_0)
{
    return (1.00000000000000000000);
}

layout(std430) buffer _S1 {
    float outputBuffer_0[];
};
layout(local_size_x = 4, local_size_y = 1, local_size_z = 1) in;void main()
{
    uint tid_0 = (gl_GlobalInvocationID).x;
    /* unhandled */;
    BaseImpl_0 base_0;
    float rs_0 = BaseImpl_getVal_0(base_0);
    ((outputBuffer_0)[tid_0]) = rs_0;
    return;
}
```

Which looks as if the problem is the glslang compiler as used on Vulkan does not accept structs which have no members. 

Tim suggests  "The right fix is for Slang's "type legalization" pass to completely eliminate empty `struct` types by legalizing them to an empty tuple. It is a bit unfortunate to remove empty `struct` types for HLSL output as well, but it is more consistent to do it everywhere."

### PR DESCRIPTION
**Pull request by csyonghe**
Both DXC and some vulkan drivers have issues with empty structs (#574). This pull request fixes the issue by eliminating thoses empty structs in type legalization step.

The solution is very easy: just return an emtpy tuple when legalizing an empty struct.

Fixes #574

### CODE REVIEW

File: source/slang/ir-legalize-types.cpp [hunk 1]
```diff
@@ -818,6 +818,8 @@ static LegalVal legalizeInst(
             args,
             inst->getOperandCount());
 
+    case kIROp_undefined:
```
Comment (csyonghe) [inline source/slang/ir-legalize-types.cpp]: I am not sure I understand the IR, but this is what is needed to get the test cases to pass.

In the IRFunc, I can see that there is an inst after a param inst that has opcode "kIROp_undefined", with only a non-null type field and 0 operands. I assume that this is intending to keep a reference of the IRType?

However when trying to lower this instruction, we will triger an unimplemented case here. This is somehow not triggered without making the change in this PR, which I don't get why.

Comment (tfoleyNV) [reply source/slang/ir-legalize-types.cpp]: The `undefined` op is used for the value of an SSA variable before it has been written; if code actually *uses* the `undefined` then it should really be an error, but we need to eliminate dead/useless code before we can go issuing errors like that.

I think the code you have here isn’t quite complete, because a `LegalVal` for a legalized instruction should follow the “shape” of its `LegalType`. That is, if the type of the instruction is a tuple, we should return a tuple of `undefined` values, etc.
 
The main place we see an `undefined` show up today ends up being for empty `struct` variables since the SSA pass thinks they are uninitialized (It never sees a `store` to them). The way you’ve handled `undefined` here works for that one case.

Realistically either lowering or the SSA pass should be smart enough to know that an empty `struct` is always initializer and write a zero argument `makeStruct` to it.

Anyway, your fix here is fine for now, but we should eventually expand it to work with any shape of type.
