### PR TITLE
Fix FindTypeByName reflection API not finding stdlib types.

### LINKED ISSUE #1357: Namespace support breaks Reflection::FindTypeByName
`FindTypeByName("ParameterBlock<MyStruct>")` returns `ErrorType` since #1304 

It seems that lookup for `ParameterBlock` failed when type-checking the parsed expression tree.

### PR DESCRIPTION
**Pull request by csyonghe**
Fixes #1357

### CODE REVIEW

File: source/slang/slang-check-shader.cpp [hunk 1]
```diff
@@ -1290,7 +1290,7 @@ namespace Slang
         // it defines keywords like `true` and `false`).
         //
         RefPtr<Scope> scope = new Scope();
-        scope->parent = getLinkage()->getSessionImpl()->baseLanguageScope;
+        scope->parent = getLinkage()->getSessionImpl()->slangLanguageScope;
```
Comment (tfoleyNV) [inline source/slang/slang-check-shader.cpp:1293]: Great catch here.
