### PR TITLE
Fix for mixed block/embedded usage of structs in SPIRV

### LINKED ISSUE #7431: In mixed uniform/ParameterBlock syntax, Slang generates invalid Vulkan code
For this code:
```
import playground;

struct Test {
    float f_float;
};

uniform Test u_struct;
ParameterBlock<Test> pb_struct;
uniform Test u_struct_array[2];

RWStructuredBuffer<float> results;

[shader("compute")]
[numthreads(1, 1, 1)]
void compute_main(uint3 tid: SV_DispatchThreadID)
{
    if (any(tid != uint3(0)))
        return;

    results[0] = u_struct.f_float;
    results[1] = pb_struct.f_float;
    results[2] = u_struct_array[0].f_float;
    results[3] = u_struct_array[1].f_float;
}
```

Vulkan validation complains about:
```
[ERROR] (rhi) driver: error: -1520283006 - VUID-VkShaderModuleCreateInfo-pCode-08737:
vkCreateShaderModule(): pCreateInfo->pCode (spirv-val produced an error):
rules: A Block or BufferBlock cannot be nested within another Block or BufferBlock.
  %GlobalParams_natural = OpTypeStruct %Test_natural %_Array_natural_Test2
The Vulkan spec states: If pCode is a pointer to SPIR-V code, pCode must adhere to the validation rules described by the Validation Rules within a Module section of the SPIR-V Environment appendix (https://vulkan.lunarg.com/doc/view/1.4.309.0/windows/antora/spec/latest/chapters/shaders.html#VUID-VkShaderModuleCreateInfo-pCode-08737)
```

This blocks adding `ParameterBlock` as tested members of SlangPy's `test_shader_cursor`

### PR DESCRIPTION
**Pull request by jhelferty-nv**
Per Vulkan VUID-VkShaderModuleCreateInfo-pCode-08737, if a SPIRV struct is marked as a block, it cannot also be a field in another structure. This change iterates over a program and identifies structs with this condition, and moves the block usage into a wrapper struct.

Fixes #7431

### CODE REVIEW

File: source/slang/slang-ir-spirv-legalize.cpp [hunk 1]
```diff
@@ -2107,6 +2107,96 @@ struct SPIRVLegalizationContext : public SourceEmitterBase
...
+                            innerStruct->findDecorationImpl(kIROp_SPIRVBufferBlockDecoration))
+                        {
+                            embeddedBlockStructs.add(innerStruct);
+                        }
+                    }
+                }
+            }
+        }
+
+        for (auto globalInst : m_module->getGlobalInsts())
```
Comment (jhelferty-nv) [inline source/slang/slang-ir-spirv-legalize.cpp]: I'm not sure if this is the best way to find all the parameters referencing the structure. I guess I could try and iterate through `embeddedBlockStructs[n].uses` as an alternative?

File: tests/bugs/gh-7431.slang [hunk 2]
```diff
@@ -0,0 +1,37 @@
+//TEST(compute):COMPARE_COMPUTE(filecheck-buffer=CHECKOUT):-vk -compute -output-using-type
```
Comment (jhelferty-nv) [inline tests/bugs/gh-7431.slang:1]: I noticed that hlsl target has a different issue with this test:
```
error: D3D12SerializeRootSignature failed
Shader register range of type CBV (root parameter [1], visibility ALL, descriptor table slot [0]) overlaps with another shader register range (root parameter[0], visibility ALL, descriptor table slot [0]).
```
Should we be trying to fix this for the d3d target? If so, I assume this is a separate issue. Beyond the overlapping ranges, it looks like the reflection json and d3d target are assigning different binding points.

File: source/slang/slang-ir-spirv-legalize.cpp (hunk 1 above)
Comment (jhelferty-nv) [reply source/slang/slang-ir-spirv-legalize.cpp]: Eh, I'm not sure if that works. Instead of I've augmented the first pass to collect global parameter instructions that use structs, to reduce the number of passes we need over the entire program.

File: tests/bugs/gh-7431.slang (hunk 2 above)
Comment (jhelferty-nv) [reply tests/bugs/gh-7431.slang:1]: @kaizhangNV Any thoughts on the above?

Comment (jhelferty-nv) [reply tests/bugs/gh-7431.slang:1]: I've filed #7611 as a follow-up task.

**Review by csyonghe — COMMENTED** [review]
Looks good to me. Thanks for the fix!
