### PR TITLE
Fix issue of infinity float literal

### LINKED ISSUE #5280: WGSL: infinity float literal not working
Affected tests:

- tests/bugs/inf-float-literal.slang

It seems a float suffix of 'f' is appended to 'inf':

    WGPU error: Error while parsing WGSL: :13:19 error: unresolved value 'inff'
                a_0 = inff;

### PR DESCRIPTION
**Pull request by kaizhangNV**
Closes #5280.

### CODE REVIEW

**Review by csyonghe — APPROVED** [review]

**Comment by kaizhangNV** [comment]
I noticed that this change doesn't work, as WGSL doesn't allow any constant infinity during compile time.
1.0/0.0 will report compile error.

**Comment by csyonghe** [comment]
NaN is not supported by the wgsl spec, but we should be able to work around the compiler error by emitting something like:
```
let tmp = 0.0;
let nan = 1.0/tmp;
```

**Comment by kaizhangNV** [comment]
That's correct

But I don't know how to emit the code for this. As the code is emit for a float literal.

So we might need to wrap this as a inline function. Don't know if there is better option?

**Comment by csyonghe** [comment]
An easy way to do this is to copy `ensurePrelude` from `slang-emit-metal.cpp`, and call
```
ensurePrelude(R"(fn getNan()->f32 {var tmp = 0.0f; return 1.0f/nan;}\n");
```
before emitting `getNan()` for the nan literal.

**Comment by kaizhangNV** [comment]
Ah, that's great.
I thought about prelude, but I'm not aware of that we have prelude for wgsl.

**Comment by kaizhangNV** [comment]
This new change should work:
image

File: source/slang/slang-emit-wgsl.cpp [hunk 1]
```diff
@@ -26,6 +26,39 @@
 namespace Slang
 {
 
+// In WGSL, expression of "1.0/0.0" is not allowed, it will report compile error,
```
Comment (aleino-nv) [inline source/slang/slang-emit-wgsl.cpp:29]: I don't know how solid the foundations for infinity/etc are in our other back-ends, but at least for WGSL there seems to be little/no foundation.

https://www.w3.org/TR/WGSL/#differences-from-ieee754

I suppose we can add this support just for the test here, but what are we really testing if we have basically no guarantees from WGSL?

Comment (aleino-nv) [reply source/slang/slang-emit-wgsl.cpp:29]: "Implementations may assume that overflow, infinities, and NaNs are not present at runtime."

Comment (csyonghe) [reply source/slang/slang-emit-wgsl.cpp:29]: I am OK with us generating out of spec code that works on majority of the platforms that most of our users care about. We can promise our user nothing, but still provide a decent solution that works most of the time, instead of enforcing restrictions that just adds friction.

Comment (aleino-nv) [reply source/slang/slang-emit-wgsl.cpp:29]: I suspected that's the policy for Slang, but good to have it confirmed.

While on the subject, what's the plan in case Slang does start specifying some of this stuff?
Are we fine with breaking apps that may be relying on behavior that Slang never promised?

**Review by csyonghe — APPROVED** [review]
