### PR TITLE
Reuse code for Metal and WGSL entry point legalization

### LINKED ISSUE #5933: wgsl @location attribute not emitted for entry-point varyings
I'm trying to slang-ify a very simple slang "hello triangle" example flor WebGPU, targeting WGSL. Here's the minimal slang shader:
```
struct VertexOutput {
    float4 clipPos : SV_POSITION;
    float3 color;
}

[shader("vertex")]
func vertexMain(float3 pos: POSITION, float3 color: COLOR0)->VertexOutput {
    VertexOutput out;
    out.clipPos = float4(pos, 1.0);
    out.color = color;
    return out;
}
```

I compile it on the 2024.17 release using this command:
```
.\bin\slangc.exe shaders.slang -target wgsl -entry vertexMain -o ..\src\vertex.wgsl
```

And then I get this invalid WGSL as the output:
```
struct VertexOutput_0
{
    @builtin(position) clipPos_0 : vec4<f32>,
    @location(0) color_0 : vec3<f32>,
};

@vertex
fn vertexMain( pos_0 : vec3<f32>,  color_1 : vec3<f32>) -> VertexOutput_0
{
    var out_0 : VertexOutput_0;
    out_0.clipPos_0 = vec4<f32>(pos_0, 1.0f);
    out_0.color_0 = color_1;
    return out_0;
}
```

This fails to compile in WGSL with the error:
```
      Entry point vertexMain at Vertex is invalid
        Argument 0 varying error
          Entry point arguments and return values must all have bindings
```

If I manually edit the WGSL to add  `@location` attributes, it's fine:
```
fn vertexMain( @location(0) pos_0 : vec3<f32>,  @location(1) color_1 : vec3<f32>) -> VertexOutput_0
```

---

Note that if I instead use an input structure instead of entry parameters, the wgsl `@location` attributes are correctly emitted. The problem is specific to entry parameters. Here's some slang using an input struct:
```
struct VertexInput {
    float3 pos : POSITION;
    float3 color : COLOR0;
}

struct VertexOutput {
    float4 clipPos : SV_POSITION;
    float3 color;
}

[shader("vertex")]
func vertexMain(VertexInput v)->VertexOutput {
    VertexOutput out;
    out.clipPos = float4(v.pos, 1.0);
    out.color = v.color;
    return out;
}
```

And here's the valid WGSL it produces. Note the `@location` attributes correctly applied to the members of `VertexInput_0`:
```
struct VertexOutput_0
{
    @builtin(position) clipPos_0 : vec4<f32>,
    @location(0) color_0 : vec3<f32>,
};

struct VertexInput_0
{
    @location(0) pos_0 : vec3<f32>,
    @location(1) color_1 : vec3<f32>,
};

@vertex
fn vertexMain( v_0 : VertexInput_0) -> VertexOutput_0
{
    var out_0 : VertexOutput_0;
    out_0.clipPos_0 = vec4<f32>(v_0.pos_0, 1.0f);
    out_0.color_0 = v_0.color_1;
    return out_0;
}
```

### PR DESCRIPTION
**Pull request by fairywreath**
Related to #4657, related to #5933.

Reuse common code for Metal and WGSL entry point legalization. 

Hoisting + packing is also currently not done for WGSL entry point parameters and they are required for #5933 as only struct entry points are given attributes. I will have a follow up fix for that as that change will break lots of test and I do not want to make this PR any bigger.

#4657 ultimately aims to also unify the legalization logic with C/CPP/CUDA backends - this PR is a good first step to unify the shading language backends.

### CODE REVIEW

**Comment by fairywreath** [comment]
I recommend comparing the (old) individual implementations of the legalization in their separate files with the new unified implementation to make the review process easier.

File: source/slang/slang-ir-legalize-varying-params.cpp [hunk 1]
```diff
@@ -1544,4 +1547,2333 @@ void depointerizeInputParams(IRFunc* entryPointFunc)
...
+
+        ShortList<IRType*> permittedTypes;
+        bool isUnsupported = false;
+
+        // Only used by Metal.
+        bool isSpecial = false;
+
+        SystemValueInfo()
+        {
+            // most commonly need 2
```
Comment (csyonghe) [inline source/slang/slang-ir-legalize-varying-params.cpp:1595]: This shouldn't be needed, as shortlist by default will statically allocate 16 elements on stack.

File: source/slang/slang-ir-legalize-varying-params.cpp [hunk 2]
```diff
@@ -1,11 +1,14 @@
 // slang-ir-legalize-varying-params.cpp
 #include "slang-ir-legalize-varying-params.h"
 
+#include "core/slang-common.h"
 #include "slang-ir-clone.h"
 #include "slang-ir-insts.h"
 #include "slang-ir-util.h"
 #include "slang-parameter-binding.h"
 
+#include <set>
```
Comment (csyonghe) [inline source/slang/slang-ir-legalize-varying-params.cpp:10]: this shouldn't be needed?

File: source/slang/slang-ir-legalize-varying-params.cpp [hunk 3]
```diff
@@ -1,11 +1,14 @@
 // slang-ir-legalize-varying-params.cpp
 #include "slang-ir-legalize-varying-params.h"
 
+#include "core/slang-common.h"
```
Comment (csyonghe) [inline source/slang/slang-ir-legalize-varying-params.cpp:4]: this shouldn't be needed.

**Review by csyonghe — APPROVED** [review]
It's great to see the duplicated code being removed. Thank you for putting together the cleanup!

I wonder if we can make this even cleaner by having a base class, and move all the metal/wgsl specific logic into derived classes?

**Comment by fairywreath** [comment]
> I wonder if we can make this even cleaner by having a base class, and move all the metal/wgsl specific logic into derived classes?

Yes this is doable. Should I modify this PR or have these changes as a follow-up?

**Comment by fairywreath** [comment]
> Yes this is doable. Should I modify this PR or have these changes as a follow-up?

I will update this PR - it should be easy to view the changes commit by commit so readability/reviewing is not an issue

File: source/slang/slang-ir-legalize-varying-params.cpp (hunk 2 above)
Comment (fairywreath) [reply source/slang/slang-ir-legalize-varying-params.cpp:9]: `std::set` is actually used and was added here #4536. Looking at that PR's commit history, A custom TreeMap/TreeSet was considered to be added but `std::set` ended up being used.

**Review by csyonghe — APPROVED** [review]
Looks good to me. Thanks for the cleanup!

Our CPU/CUDA backend is in great need of a refactor to reuse the same varying legalization logic we have for other targets. We are missing a lot of legalization there. This PR is a good step towards the greater unification.

**Comment by csyonghe** [comment]
Looks like there are still conflicts.

**Comment by fairywreath** [comment]
Sorry for the plethora of dirty commits but the last two commits are the only changes, the rest are reverted(I had incorrect merge commits). I had to move additional logic from #5963.

**Review by csyonghe — APPROVED** [review]
