### PR TITLE
Fix missing Aligned operand for PhysicalStorageBuffer stores

### LINKED ISSUE #9614: SPIR-V: copying struct from/to pointer results in validation error
This is a quite strange one, only happens specifically when directly copying structs from a pointer:

```slang
struct Foo {
    uint x, y, z, w;
};
[numthreads(64)]
void CS_Main(uniform Foo* src, uniform Foo* dst, uint tid: SV_DispatchThreadID) {
    dst[tid] = src[tid];
}
```

Results in:
```
error: line 67: Memory accesses with PhysicalStorageBuffer must use Aligned.
  OpStore %24 %33
```

Does not happen if struct is modified in some way, but still not enough to just copy to local var:
```slang
    Foo v = src[tid];
    v.x++;
    dst[tid] = v;
```

### PR DESCRIPTION
**Pull request by jkwak-work**
Add required Aligned memory access operand to OpStore instructions when storing to PhysicalStorageBuffer pointers in emitCopyLogical() and emitSwizzledStore().

Fixes #9614

### CODE REVIEW

File: source/slang/slang-emit-spirv.cpp [hunk 1]
```diff
@@ -7600,6 +7600,20 @@ struct SPIRVEmitContext : public SourceEmitterBase, public SPIRVEmitSharedContex
         if (destPtrType->hasAddressSpace())
             addrSpace = destPtrType->getAddressSpace();
         auto ptrElementType = builder.getPtrType(kIROp_PtrType, sourceElementType, addrSpace);
+
+        // Compute memory access operands for PhysicalStorageBuffer alignment
+        int memoryAccessMask = 0;
+        int alignment = -1;
+        if (destPtrType && addressSpaceToStorageClass(destPtrType->getAddressSpace()) ==
```
Comment (jhelferty-nv) [inline source/slang/slang-emit-spirv.cpp]: probably minor: 7 lines up you're derefing `destPtrType` without a null check.

Comment (jkwak-work) [reply source/slang/slang-emit-spirv.cpp]: Good point.
I made some changes to clean it up.
