### PR TITLE
Fix scenario where type coerce constraints were not erroring

### LINKED ISSUE #9626: Type coercion constraint does not correctly constrain parameters in some scenarios
# Issue Description
Type coercion constraint does not correctly constrain parameters in some scenarios.

# Reproducer Code
Link: https://godbolt.org/z/WWMjMzaEK
```slang
RWStructuredBuffer<int> outputBuffer;
int castableConstraint1<ToType, FromType>(FromType input) where ToType(FromType)
{
    return 1;
}

struct CustomStruct1
{
    int data;
    __init(int other)
    {
        data = other;
    }
}

struct CustomStruct2
{
    int data;
    __init(int other)
    {
        data = other;
    }
}

[shader("compute")]
[numthreads(1,1,1)]
void computeMain(uint3 threadId : SV_DispatchThreadID)
{
    uint index = threadId.x;
    outputBuffer[0] = (true
        && castableConstraint1<CustomStruct2, CustomStruct1>(CustomStruct1(1)) == 1
    )? 1 : 0;
}
```

# Expected Behavior
Slang produces an error for the invalid code since `CustomStruct2` does not implement a `__init` to cast into `CustomStruct1`.

# Actual Behavior
Slang compiles the code.

# Environment
 - Slang Version: (TOT) 5894ce5fe3f59f9e71b0a39e713715efe0ae27e0
 - OS: Windows 11

### PR DESCRIPTION
**Pull request by 16-Bit-Dog**
Fixes #9626

Problem & Solution:
* Fix scenario where type coerce constraints were not erroring, add relevant positive/negative tests
* Lay groundwork needed to implement full support for type coerce constraints by making `coerce` emit variants of `TypeCoercionWitness`, a `Builtin` (uses intrinsic conversion logic to coerce) and `DeclRef` variant (user definition is used to coerce, conversion is the stored declRef). Currently this information is only used to improve the errors Slang generates.

### CODE REVIEW

File: source/slang/slang-check-conversion.cpp [hunk 1]
```diff
@@ -1184,15 +1186,36 @@ ConversionCost SemanticsVisitor::getImplicitConversionCostWithKnownArg(
...
 bool SemanticsVisitor::_coerce(
     CoercionSite site,
     Type* toType,
     Expr** outToExpr,
     QualType fromType,
     Expr* fromExpr,
     DiagnosticSink* sink,
-    ConversionCost* outCost)
+    ConversionCost* outCost,
+    DeclRef<Decl>* outDeclRefUsedToConvert)
```
Comment (csyonghe) [inline source/slang/slang-check-conversion.cpp]: This should just return a `TypeCoercionWitness*`.

We can have `class BuiltinTypeCoercionWitness` to rerpresent all coercions that are handled by `IRBuilder::emitCast()`. Then we have `DeclRefTypeCoercionWitness` that represent the implicit ctor declref that can be called to perform any user-defined coercion. This way we don't need to synthesize any funcdecls to represent builtin coercions.

File: source/slang/slang-lower-to-ir.cpp [hunk 2]
```diff
@@ -1939,9 +1939,16 @@ struct ValLoweringVisitor : ValVisitor<ValLoweringVisitor, LoweredValInfo, Lower
 
     LoweredValInfo visitTypeCoercionWitness(TypeCoercionWitness*)
     {
-        // When we fully support type coercion constraints, we should lower the witness into a
-        // function that does the conversion.
+        // For now we do not use the result of a `TypeCoercionWitness` in any senario, so this logic
```
Comment (csyonghe) [inline source/slang/slang-lower-to-ir.cpp]: this should lower into a callable function that convert from T to U.

I do think we will need it to support generic functions like:
```
void myFunc(T t) where U(T)
{
      U u = t; // invoke the witness to convert!
}
```

**Comment by mkeshavaNV** [comment]
@16-Bit-Dog - Can you please mark this as Draft if you're not looking at this for now? Thanks!

**Comment by mkeshavaNV** [comment]
@csyonghe could you please re-review.

File: tests/language-feature/generics/type-coerce-constraint-2.slang [hunk 3]
```diff
@@ -0,0 +1,64 @@
+// TEST(compute):COMPARE_COMPUTE(filecheck-buffer=POSITIVE_CHECK_1): -vk -shaderobj
+// TEST(compute):COMPARE_COMPUTE(filecheck-buffer=POSITIVE_CHECK_2): -vk -shaderobj
```
Comment (jkwak-work) [inline tests/language-feature/generics/type-coerce-constraint-2.slang]: I think you can share the result checking keyword; replace POSITIVE_CHECK_2 with POSITIVE_CHECK_1:
```
// TEST(compute):COMPARE_COMPUTE(filecheck-buffer=POSITIVE_CHECK): -vk -shaderobj
// TEST(compute):COMPARE_COMPUTE(filecheck-buffer=POSITIVE_CHECK): -vk -shaderobj
```

File: source/slang/glsl.meta.slang [hunk 4]
```diff
@@ -155,7 +155,7 @@ public property uint3 gl_WorkGroupSize
     [require(meshshading)]
     get
     {
-        return WorkgroupSize();
+        return (uint3)WorkgroupSize();
```
Comment (csyonghe) [inline source/slang/glsl.meta.slang]: why is this needed?

File: source/slang/slang-check-constraint.cpp [hunk 5]
```diff
@@ -339,6 +339,118 @@ Type* SemanticsVisitor::TryJoinTypes(ConstraintSystem* constraints, QualType lef
...
+    auto toType = getToType(astBuilder, constraintDeclRef);
+    auto conversionCost = visitor->getConversionCost(toType, fromType);
+    if (constraintDecl->findModifier<ImplicitConversionModifier>())
+    {
+        // The viable conversion is not an implicit conversion, but implicit was requested, fail
+        if (conversionCost > kConversionCost_GeneralConversion)
+        {
+            if (shouldEmitError)
+            {
+                TypeCoercionWitness* typeCoercionWitness{};
```
Comment (csyonghe) [inline source/slang/slang-check-constraint.cpp]: = nullptr;

File: source/slang/slang-lower-to-ir.cpp [hunk 6]
```diff
@@ -1937,11 +1937,33 @@ struct ValLoweringVisitor : ValVisitor<ValLoweringVisitor, LoweredValInfo, Lower
...
+    LoweredValInfo visitBuiltinTypeCoercionWitness(BuiltinTypeCoercionWitness* witness)
     {
-        // When we fully support type coercion constraints, we should lower the witness into a
-        // function that does the conversion.
-        return LoweredValInfo();
+        auto irBuilder = getBuilder();
+        auto fromType = lowerType(context, witness->getFromType());
+        auto toType = lowerType(context, witness->getToType());
+        auto funcType = getBuilder()->getFuncType(1, &fromType, toType);
+        IRFunc* irFunc = irBuilder->createFunc();
```
Comment (csyonghe) [inline source/slang/slang-lower-to-ir.cpp:1946]: should probably mark the function as forceinline to simply the output code.

File: tests/language-feature/generics/type-coerce-constraint-2.slang [hunk 7]
```diff
@@ -0,0 +1,63 @@
+// TEST(compute):COMPARE_COMPUTE(filecheck-buffer=POSITIVE_CHECK): -vk -shaderobj -xslang -DPOSITIVE_CHECK_1
+// TEST(compute):COMPARE_COMPUTE(filecheck-buffer=POSITIVE_CHECK): -vk -shaderobj -xslang -DPOSITIVE_CHECK_2
```
Comment (csyonghe) [inline tests/language-feature/generics/type-coerce-constraint-2.slang]: this test is not specific to vulkan so we should run it on all targets.

File: source/slang/slang-check-constraint.cpp [hunk 8]
```diff
@@ -339,6 +339,118 @@ Type* SemanticsVisitor::TryJoinTypes(ConstraintSystem* constraints, QualType lef
...
+    // To emit an error, `maybeContext` must be provided.
+    SLANG_ASSERT(!shouldEmitError || shouldEmitError && maybeContext);
+
+    DeclRef<TypeCoercionConstraintDecl> constraintDeclRef =
+        astBuilder
+            ->getGenericAppDeclRef(genericDeclRef, args.getArrayView().arrayView, constraintDecl)
+            .as<TypeCoercionConstraintDecl>();
+    auto fromType = getFromType(astBuilder, constraintDeclRef);
+    auto toType = getToType(astBuilder, constraintDeclRef);
+    auto conversionCost = visitor->getConversionCost(toType, fromType);
```
Comment (csyonghe) [inline source/slang/slang-check-constraint.cpp]: getConversionCost() is as expensive as _coerce. This function calls getConversionCost() and then calls _coercion later in both shouldEmitError and !shouldEmitError branches. Should just call _coerce once here, and reuse the cost and resolved declref for code generation and error reporting.

File: source/slang/glsl.meta.slang (hunk 4 above)
Comment (16-Bit-Dog) [reply source/slang/glsl.meta.slang]: This change will be removed.
note: `WorkgroupSize` returns a `int3`, not a `uint3`.

**Comment by 16-Bit-Dog** [comment]
All suggestions have been addressed, thank-you for the review.
