### PR TITLE
Handle Sampler array in combined texture sampler lowering pass.

### LINKED ISSUE #7246: Array of Sampler2D's loses register attribute when converting to hlsl
Using `slangc -target hlsl`, specifying a Sampler2D array

```slang
Sampler2D tex[16] : register(t0, space2) : register(s0, space2);
```

Loses the register attributes when splitting from the combined texture+sampler into separate variables

```slang
Texture2D<float4 >  tex_texture_0[int(16)];
SamplerState  tex_sampler_0[int(16)];
```

## Expected

```slang
Texture2D<float4 >  tex_texture_0[int(16)] : register(t0, space2);
SamplerState  tex_sampler_0[int(16)] : register(s0, space2);
```

### LINKED ISSUE #8852: slangc segfaults on all wgsl conversions
# Issue Description
On my mac the version of slangc is working fine ```Mac:wasm mike$ slangc -v
1752257177```

But i cannot find _any_ version of slangc for linux that doesn't segfault immediately on any files I throw at it.

```
mike@zoobox:~/Downloads/slang-2025.19.1-linux-x86_64/bin$ ./slangc -v
2025.19.1
mike@zoobox:~/Downloads/slang-2025.19.1-linux-x86_64/bin$ /home/mike/repo/engine/wasm/../cpp/engine/graphics/core/shaders/effects/gaussian.slang -target wgsl  -o /home/mike/repo/engine/wasm/build/shaders/delme.wgsl
Segmentation fault (core dumped)
mike@zoobox:~/Downloads/slang-2025.
```

# Reproducer Code
```
struct VSOutput
{
    float4 pos : SV_Position;
    float2 texcoord;
};

[[vk::binding(1, 1)]]
Sampler2D textures[];

//https://godotshaders.com/shader/screen-space-edge-detection-outline-shader/
//https://ameye.dev/notes/edge-detection-outlines/
//https://ameye.dev/notes/rendering-outlines/

//#define SHARPNESS 46.0
#define SHARPNESS 10.0

// Original CG input params (original constant buffer)
// struct input
// {
//   float2 video_size;
//   float2 texture_size;
//   float2 output_size;
//   float frame_count;
//   float frame_direction;
//   float frame_rotation;
// };

//Note - 2D & 3D gaussian kernels are separable and are (usually) more efficient to be separated as such on the GPU
// thus, we do a horizontal pass followed by a vertical one
// More on this at page 30 of
// https://etd.ohiolink.edu/acprod/odb_etd/etd/r/1501/10?clear=10&p10_accession_num=ohiou1257891307
//
// Apply first pass of 9x9 "gaussian" kernel
// 1D kernel (approx) - [ 20, 11, 8, 6, 6, 6, 8, 11, 20 ]
// Also note that sharpness doesn't affect the kernel width, but just how far the samples are from the center

[shader("vertex")]
VSOutput vertexMain(uint vertexIndex : SV_VertexID)
{
    VSOutput output;

    output.texcoord = float2((vertexIndex << 1) & 2, vertexIndex & 2);
    output.pos = float4(output.texcoord * 2.0f - 1.0f, 0.0f, 1.0f);

    return output;
}

[shader("fragment")]
float4 fragmentGaussianHorizontalMain(VSOutput input)
{
    const float2 texCoord = input.texcoord;
    float4 sum = float4(0.0);

    sum += textures[0].Sample(float2(texCoord.x, texCoord.y - 4.0 / (SHARPNESS * 128.0))) *0.05;
    sum += textures[0].Sample(float2(texCoord.x, texCoord.y - 3.0 / (SHARPNESS * 128.0))) *0.09;
    sum += textures[0].Sample(float2(texCoord.x, texCoord.y - 2.0 / (SHARPNESS * 128.0))) *0.12;
    sum += textures[0].Sample(float2(texCoord.x, texCoord.y - 1.0 / (SHARPNESS * 128.0))) *0.15;
    sum += textures[0].Sample(float2(texCoord.x, texCoord.y)) * 0.16;
    sum += textures[0].Sample(float2(texCoord.x, texCoord.y + 1.0 / (SHARPNESS * 128.0))) *0.05;
    sum += textures[0].Sample(float2(texCoord.x, texCoord.y + 2.0 / (SHARPNESS * 128.0))) *0.09;
    sum += textures[0].Sample(float2(texCoord.x, texCoord.y + 3.0 / (SHARPNESS * 128.0))) *0.12;
    sum += textures[0].Sample(float2(texCoord.x, texCoord.y + 4.0 / (SHARPNESS * 128.0))) *0.15;
    return sum;
}

[shader("fragment")]
float4 fragmentGaussianVerticalMain(VSOutput input)
{
    const float2 texCoord = input.texcoord;
    float4 sum = float4(0.0);

    sum += textures[1].Sample(float2(texCoord.x - 4.0 / (SHARPNESS * 128.0), texCoord.y)) * 0.05;
    sum += textures[1].Sample(float2(texCoord.x - 3.0 / (SHARPNESS * 128.0), texCoord.y)) * 0.09;
    sum += textures[1].Sample(float2(texCoord.x - 2.0 / (SHARPNESS * 128.0), texCoord.y)) * 0.12;
    sum += textures[1].Sample(float2(texCoord.x - 1.0 / (SHARPNESS * 128.0), texCoord.y)) * 0.15;
    sum += textures[1].Sample(float2(texCoord.x, texCoord.y)) * 0.16;
    sum += textures[1].Sample(float2(texCoord.x + 1.0 / (SHARPNESS * 128.0), texCoord.y)) * 0.15;
    sum += textures[1].Sample(float2(texCoord.x + 2.0 / (SHARPNESS * 128.0), texCoord.y)) * 0.12;
    sum += textures[1].Sample(float2(texCoord.x + 3.0 / (SHARPNESS * 128.0), texCoord.y)) * 0.09;
    sum += textures[1].Sample(float2(texCoord.x + 4.0 / (SHARPNESS * 128.0), texCoord.y)) * 0.05;
    return sum;
}
```

### PR DESCRIPTION
**Pull request by csyonghe**
The combined texture sampler lowering pass didn't handle the case that a global parameter is an array of combined samplers, and thus result in future passes to crash.

This PR implements the missing case.

Closes #8852.
Closes #7246.

### CODE REVIEW

File: source/slang/slang-ir-lower-combined-texture-sampler.cpp [hunk 1]
```diff
@@ -112,65 +148,70 @@ void lowerCombinedTextureSamplers(
...
+
     // Lower combined texture sampler type into a struct type.
     for (auto globalInst : module->getGlobalInsts())
     {
-        auto textureType = as<IRTextureTypeBase>(globalInst);
-        if (!textureType || getIntVal(textureType->getIsCombinedInst()) == 0)
+        if (isCombinedTextureSamplerType(globalInst))
+            hasCombinedSampler = true;
+        auto globalParam = as<IRGlobalParam>(globalInst);
+        if (!globalParam)
```
Comment (aidanfnv) [inline source/slang/slang-ir-lower-combined-texture-sampler.cpp:175]: These checks are too restrictive. I found that in https://github.com/shader-slang/slang/pull/7939, I needed to also process `globalVar`s, but in a different manner, and also other `globalInst`s in yet a different manner.
See the check at https://github.com/shader-slang/slang/pull/7939/files#diff-430fe9ed0017c2c2a664e3ec75a0dc4e4848b93a320c67920b03e74d29742cb7R170
If I remove the `else if (globalVar)` and `else` from that PR, I get the same test failures that you have now.

**Comment by csyonghe** [comment]
I am not convinced we need to handle globalvars though, as there should never be such insts that has a combined sampler type.

My PR should be passing all tests, including the one you added in #7939.

File: source/slang/slang-ir-lower-combined-texture-sampler.cpp (hunk 1 above)
Comment (aidanfnv) [reply source/slang/slang-ir-lower-combined-texture-sampler.cpp:175]: > same test failures

I double-checked this, and while the same tests fail, the actual failures were different, so this comment can be disregarded

**Comment by aidanfnv** [comment]
Strange, I am not quite sure why the globalVar/globalInst checking in https://github.com/shader-slang/slang/pull/7939 cleared my test failures then.

**Review by aidanfnv — APPROVED** [review]
Looks good to me.
