### PR TITLE
Fix NVRTC silent failures when CUDA/OptiX headers are missing

### LINKED ISSUE #7037: [Optix][CUDA] NVRTC compiler backend fails to locate `cuda_fp16.h` and just returns SLANG_FAIL
Slang only looks for `cuda_fp16.h` in `/usr/include` (see `_findCUDAIncludePath`), but Ubuntu puts CUDA headers into `/usr/local/cuda-x[.x]`. The search should probably be expanded to more generically be able to search for potential locations (there might be different ones for other OSes) and then pick the most recent one.

More importantly, Slang shouldn't just return a `SLANG_FAIL` error but also return some diagnostics to inform users of the failure. Now, there is no way around stepping through code in the debugger to figure out why the backend compiler fails.

### PR DESCRIPTION
**Pull request by szihs**
Fix #7037

When cuda_fp16.h or optix.h headers cannot be located, NVRTC compilation would fail silently with no diagnostic message, leaving users with only a generic SLANG_FAIL error code.

This change:
- Threads IArtifactDiagnostics through _maybeAddHalfSupport() and _maybeAddOptixSupport() to enable error reporting
- Creates artifact and diagnostics early in compile() so errors from any stage can be reported
- Adds descriptive error messages when headers are not found, guiding users to install CUDA Toolkit or OptiX SDK
- Follows existing downstream compiler pattern: compile() returns SLANG_OK with diagnostics, caller checks via passthroughDownstreamDiagnostics()

Error messages now displayed:
- "Failed to locate CUDA headers (cuda_fp16.h) required for half/float16 support. Please install CUDA Toolkit or set CUDA_PATH environment variable."
- "Failed to locate OptiX headers (optix.h) required for OptiX ray tracing support. Please install OptiX SDK."

### CODE REVIEW

**Comment by mkeshavaNV** [comment]
Seems good, did you confirm that this does not let slang go forward to downstream compiler when the header is found?

File: source/compiler-core/slang-nvrtc-compiler.cpp [hunk 1]
```diff
@@ -1061,7 +1088,12 @@ SlangResult NVRTCDownstreamCompiler::compile(
         cmdLine.addArg(asString(include));
     }
 
-    SLANG_RETURN_ON_FAIL(_maybeAddHalfSupport(options, cmdLine));
+    if (SLANG_FAILED(_maybeAddHalfSupport(options, cmdLine, diagnostics)))
+    {
+        diagnostics->setResult(SLANG_FAIL);
+        *outArtifact = artifact.detach();
+        return SLANG_OK;
```
Comment (jkwak-work) [inline source/compiler-core/slang-nvrtc-compiler.cpp]: Before this PR, it was returning the failing return value from `_maybeAddHalfSupport()`.
Shouldn't we keep the same behavior rather than returning SLANG_OK?

Comment (szihs) [reply source/compiler-core/slang-nvrtc-compiler.cpp]: We should return SLANG_OK.

https://github.com/shader-slang/slang/blob/4e4aad5a0493defde1e0ef29f27e5d663c1182cd/source/slang/slang-code-gen.cpp#L1014-L1020

If downstream::compile() would return SLANG_FAIL it will return immediately without calling passthroughDownstreamDiagnostics() to extract the failure - thus silently failing. (Exactly the issue we are fixing)

**Comment by szihs** [comment]
> Seems good, did you confirm that this does not let slang go forward to downstream compiler when the header is found?

Yes, as mentioned in the note above 

Error messages now displayed:

"Failed to locate CUDA headers (cuda_fp16.h) required for half/float16 support. Please install CUDA Toolkit or set CUDA_PATH environment variable."
"Failed to locate OptiX headers (optix.h) required for OptiX ray tracing support. Please install OptiX SDK."

**Comment by szihs** [comment]
ping @mkeshavaNV / @jkwak-work for review

File: source/compiler-core/slang-nvrtc-compiler.cpp (hunk 1 above)
Comment (jkwak-work) [reply source/compiler-core/slang-nvrtc-compiler.cpp]: That explanation doesn't make sense to me.
The problem looks to be on how the macro `SLANG_RETURN_ON_FAIL` is used.
With the current implementation, the compilation failure will be always silently ignored.

Shouldn't it be more like the following?
```
    auto downstreamStartTime = std::chrono::high_resolution_clock::now();
    compiler->compile(options, artifact.writeRef()); // <== HERE WITHOUT `SLANG_RETURN_ON_FAIL`.
    auto downstreamElapsedTime =
        (std::chrono::high_resolution_clock::now() - downstreamStartTime).count() * 0.000000001;
    getSession()->addDownstreamCompileTime(downstreamElapsedTime);

    SLANG_RETURN_ON_FAIL(passthroughDownstreamDiagnostics(getSink(), compiler, artifact));
```

File: source/compiler-core/slang-nvrtc-compiler.cpp [hunk 2]
```diff
@@ -914,7 +921,14 @@ SlangResult NVRTCDownstreamCompiler::_maybeAddHalfSupport(
     }
 
     String includePath;
-    SLANG_RETURN_ON_FAIL(_getCUDAIncludePath(includePath));
+    if (SLANG_FAILED(_getCUDAIncludePath(includePath)))
+    {
+        String msg = "Failed to locate CUDA headers (cuda_fp16.h) required for half/float16 "
+                     "support. Please install CUDA Toolkit or set CUDA_PATH environment variable.";
+        diagnostics->setRaw(SliceUtil::asCharSlice(msg));
+        diagnostics->requireErrorDiagnostic();
```
Comment (jkwak-work) [inline source/compiler-core/slang-nvrtc-compiler.cpp:929]: We should prefer to use the other diagnose function, because it can avoid forming a string message at the runtime and it can print an error message id that can help the users to look for additional helps on the internet.

I am talking about something like this,
```
getSink()->diagnose(SourceLoc(), Diagnostics::cannotFindCUDAHeaders);
```

Comment (szihs) [reply source/compiler-core/slang-nvrtc-compiler.cpp:929]: We cannot - DownstreamCompiler is lower level code which doesn't have access to getSink()

File: source/compiler-core/slang-nvrtc-compiler.cpp (hunk 1 above)
Comment (szihs) [reply source/compiler-core/slang-nvrtc-compiler.cpp]: I don't think that approach is good either. 
Downstream compilers communicate errors via diagnostics attached to the artifact, not via return values.  

If we remove `SLANG_RETURN_ON_FAIL` - it would mean we don't care if we return SLANG_FAIL at all anyway.

**Comment by szihs** [comment]
@jkwak-work - I don't think the changes are required. Let me know if you still feel otherwise.

File: source/compiler-core/slang-nvrtc-compiler.cpp (hunk 1 above)
Comment (jkwak-work) [reply source/compiler-core/slang-nvrtc-compiler.cpp]: Then don't ignore the return value.
I didn't meant that you should ignore the return value from the function `compile()`.
I was only making a point that the problem is on the calling place.

Comment (szihs) [reply source/compiler-core/slang-nvrtc-compiler.cpp]: updated.
