### PR TITLE
Fix issue on reinterpret of resource type

### LINKED ISSUE #10126: [neural.slang] Compile crash when reinterpret the storage buffer.
# Issue Description
In CUDA/Cpp targets, we should be able to reinterpret the storage buffer.
However, we generate the invalid code first, and crash later.

# Reproducer Code
```
RWStructuredBuffer<half> handle;
RWStructuredBuffer<half> outputBuffer;
uniform int inputVal;

[numthreads(1, 1, 1)]
[shader("compute")]
void computeMain(uint3 dispatchThreadID: SV_DispatchThreadID)
{
    half2 h2 = bit_cast<half2>(inputVal);

    RWStructuredBuffer<half2> vecBuffer = reinterpret<RWStructuredBuffer<half2>>(handle);
    __atomic_reduce_add(vecBuffer[0], h2);

    outputBuffer[0] = vecBuffer[0].x;
    outputBuffer[1] = vecBuffer[0].y;
}
```

# Expected Behavior
This code should compile and generated code should be valid.

# Actual Behavior
First, we generate invalid code.
`RWStructuredBuffer` takes 16 bytes on Cuda/Cpp targets, however we only pack it into unit2.

Second, after fix this issue, we hit the issue in processing with bitCast inst. Because we shouldn't handle the bitCast of resource types.

# Environment
 - Slang Version (release version number or commit hash)
 - OS
 - GPU/Driver version, if the bug is a runtime result error.
 - Any related environment variables.

### PR DESCRIPTION
**Pull request by kaizhangNV**
Close https://github.com/shader-slang/slang/issues/10126.

This PR address two issues:

- correctly handle the packing of resource handles: we previously hardcode the size of the handles, however the size of resource handle could be varying with targets.

- Skip processing bitcast of storage buffer in processingBitCast call. After the pass of lowering the reinterpret, we could insert bitCast insts, and we will need to skip the processing of the bit cast of resource handles because we couldn't handle that.

### CODE REVIEW

File: source/slang/slang-ir-any-value-marshalling.cpp [hunk 1]
```diff
@@ -942,28 +950,37 @@ struct AnyValueMarshallingContext
...
+                        anyValInfo->fieldKeys[fieldOffset + (uint32_t)i]);
+                    components.add(builder->emitLoad(srcAddr));
+                }
+                auto uintNVal =
+                    builder->emitMakeVector(uintNType, (UInt)numUints, components.getBuffer());
+                auto combinedBits = builder->emitBitCast(dataType, uintNVal);
                 builder->emitStore(concreteVar, combinedBits);
-                advanceOffset(8);
             }
+            advanceOffset((uint32_t)size);
```
Comment (jkwak-work) [inline source/slang/slang-ir-any-value-marshalling.cpp]: The previous implementation had `advanceOffset(8)` inside of the `if` condition.
But the new implementation moved it out of `if` condition.

This is inconsistent to how the new implementation does in the line 603.
I think this should change to
```
 if (fieldOffset + numUints - 1 < static_cast<uint32_t>(anyValInfo->fieldKeys.getCount()))
{
  ...
  advanceOffset((uint32_t)size);
}
```

**Review by jkwak-work — DISMISSED** [review]
Looks good to me but I have a concern on one line.

**Comment by jkwak-work** [comment]
@aidanfnv for visibility.

File: source/slang/slang-ir-any-value-marshalling.cpp (hunk 1 above)
Comment (kaizhangNV) [reply source/slang/slang-ir-any-value-marshalling.cpp]: You are right, this is some mistake by cursor.

**Review by jkwak-work — APPROVED** [review]
Looks good to me
