### PR TITLE
Print SPIRV validation error message

### LINKED ISSUE #4692: Address compiler warnings
**Problem description**
With recent changes on our cmake build system, I start to see new warnings from the visual studio compiler.
We should not have theses warning.

**Repro step**
It was reproduced with a following commit id,
```
commit 7488b15d21ab3d72b2598da80712c00d368518bd (HEAD -> fix/spirv_validation_texture_16_bit_types, upstream/master, origin/master, origin/HEAD, master, fix/resolve_compiler_warnings_with_vs)
Date:   Fri Jul 19 03:06:38 2024 -0400
```

The build command is following,
```
cmake.exe --preset vs2019
cmake.exe --build --preset release
```

The following warning messages are observed.
Note that they weren't printed a few days ago.
```
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\GenericCodeGen.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\GenericCodeGen.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\GenericCodeGen.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\OGLCompilersDLL\OGLCompiler.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\OSDependent\Windows\OSDependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\MachineIndependent.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\SPIRV-Tools-static.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\SPIRV-Tools-static.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\SPIRV-Tools-static.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\SPIRV-Tools-static.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\SPIRV-Tools-static.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\SPIRV-Tools-static.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\opt\SPIRV-Tools-opt.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\opt\SPIRV-Tools-opt.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\opt\SPIRV-Tools-opt.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\opt\SPIRV-Tools-opt.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\opt\SPIRV-Tools-opt.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\spirv-tools\source\opt\SPIRV-Tools-opt.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\SPIRV\SPIRV.vcxproj]
cl : command line warning D9025: overriding '/W1' with '/w' [D:\sbf\git\slang\jkwak\build\external\glslang\glslang\glslang.vcxproj]
cl : command line warning D9025: overriding '/W3' with '/w' [D:\sbf\git\slang\jkwak\build\external\miniz\miniz.vcxproj]
cl : command line warning D9025: overriding '/W3' with '/w' [D:\sbf\git\slang\jkwak\build\external\miniz\miniz.vcxproj]
cl : command line warning D9025: overriding '/W3' with '/w' [D:\sbf\git\slang\jkwak\build\external\miniz\miniz.vcxproj]
cl : command line warning D9025: overriding '/W3' with '/w' [D:\sbf\git\slang\jkwak\build\external\miniz\miniz.vcxproj]
cl : command line warning D9025: overriding '/W3' with '/w' [D:\sbf\git\slang\jkwak\build\external\miniz\miniz.vcxproj]
```

### LINKED ISSUE #4696: SPIRV validation error message is no longer printed
**Problem description**
With a recent change, PR #4642,  to our SPIRV validation logic, the validation error message is no longer printed.

**Goal**
We should have the detailed error message back when the SPIRV validation failed.

**Repro**
The following command printed a details of what is the problem from the SPIRV validation.
```
$ slangc.exe tests/metal/texture.slang -target spirv
error: line 70656: [VUID-StandaloneSpirv-OpTypeImage-04656] Expected Sampled Type to be a 32-bit int, 64-bit int or 32-bit float scalar type for Vulkan environment
  %9148 = OpTypeImage %short 1D 2 0 0 1 Rgba16i

(0): internal error 99999: Validation of generated SPIR-V failed.
```
It now prints only the last line without the details of what is wrong.
```
$ slangc.exe tests/metal/texture.slang -target spirv
(0): internal error 99999: Validation of generated SPIR-V failed.
```

### PR DESCRIPTION
**Pull request by jkwak-work**
Closes #4696

This is a quick fix for the issue that SPIR-V validation error message is not printed. A more proper way is to return the error messages to the application and let the application handle it.

### CODE REVIEW

File: source/slang-glslang/slang-glslang.cpp [hunk 1]
```diff
@@ -145,6 +145,28 @@ struct SPIRVOptimizationDiagnostic
     std::string message;
 };
 
+// TODO: the actual printing should happen on the application side.
```
Comment (csyonghe) [inline source/slang-glslang/slang-glslang.cpp:148]: We should extend the `DownstreamCompiler::validate` interface to return a IBlob for the diagnostics.

**Review by csyonghe — APPROVED** [review]

File: source/slang-glslang/slang-glslang.cpp (hunk 1 above)
Comment (jkwak-work) [reply source/slang-glslang/slang-glslang.cpp:148]: Right. I was little bit reluctant to implement it with IBlob due to the complexity it may come with.
Alternatively, we can take a call-back function, which can avoid the memory allocation and IBlob.

This printing is only for slang developers and printing the message directly from slang-glslang will be fine as a quick fix.
I will merge the change as it for now.
