### PR TITLE
Propagate @SpecConst rate type for global constants derived from specialization constants

### LINKED ISSUE #10373: Slang Internal Error when setting a global constant based on specialization constant value with a ternary operator
# Issue Description
Picking a global constant based on a specialization constant with a ternary operator triggers a Slang internal error when compiling to SPIR-V. This is a very similar problem to #10356.

# Reproducer Code
```
[vk::specialization_constant] const uint FOO1 = 0;
[vk::specialization_constant] const uint FOO2 = 0;

static const uint value = FOO2 == 0 ? 0 : FOO1 / FOO2;

[shader("compute")]
[numthreads(64, 1, 1)]
void main(uint tid : SV_GroupIndex) {
	printf("%d\n", value);
}
```
Compiled with `shader.slang -stage compute -target spirv -entry main -o shader.spirv`

# Expected Behavior
This pattern works in GLSL, so it should compile successfully.

# Actual Behavior
Internal error:
```
error[E99999]: Slang compilation aborted due to an exception of N5Slang13InternalErrorE unimplemented: Unhandled global inst in spirv-emit:
[nameHint(%1)]
let  %value	: %2	= select(%3, %4, %5)

For assistance, file an issue on GitHub (https://github.com/shader-slang/slang/issues) or join the Slang Discord (https://khr.io/slangdiscord)
```

# Environment
 - Slang compiled from commit d6a3e4dcb57614713aaddeb867e9e34c1127ad02
 - Fedora 43

### PR DESCRIPTION
**Pull request by aidanfnv**
Fixes #10373 

When a global constant is initialized from an expression involving specialization constants (e.g. `FOO2 == 0 ? 0 : FOO1 / FOO2`), the lowering produces intermediate IR instructions (`cmpEQ`, `div`, `select`) at global scope without the `@SpecConst` rate type qualifier. Since the SPIR-V emitter's `emitGlobalInst` identifies spec-const-derived instructions via `isSpecConstRateType`, these untagged instructions fell through to the unhandled-instruction error.

This is distinct from #10356 (fixed in #10361), where the `select` instruction *did* have the rate qualifier but lacked an opcode mapping. Here the rate qualifier is absent because the lowering path for regular global initializer expressions (`emitCallToDeclRef`) does not propagate it, unlike the `IntVal` path (`visitFuncCallIntVal`) used for array sizes.

The semantic checker's first attempt at folding the initializer happens in `SemanticsDeclHeaderVisitor::checkVarDeclCommon`, but this runs during the header checking pass before the init expression has been through `visitSelectExpr`/`visitInvokeExpr`, so operator `DeclRef`s aren't resolved and the fold fails. The second attempt happens in `_validateCircularVarDefinition` during the body checking pass (after `CheckTerm` has fully type-checked the expression), but it used `ConstantFoldingKind::LinkTime`, which cannot represent spec-constant operands symbolically and also fails.

This changes `_validateCircularVarDefinition` to use `ConstantFoldingKind::SpecializationConstant`, allowing the fold to produce `DeclRefIntVal` for spec-constant references and `FuncCallIntVal` for operations on them. It then updates `lowerConstantDeclCommon` to check for `FuncCallIntVal` on `decl->val` and lower it via `lowerSimpleVal` (routing through `visitFuncCallIntVal`) instead of `lowerRValueExpr(initExpr)`, producing constexpr IR ops with the `@SpecConst` rate type.

### CODE REVIEW

File: source/slang/slang-emit-spirv.cpp [hunk 1]
```diff
@@ -2025,6 +2025,55 @@ struct SPIRVEmitContext : public SourceEmitterBase, public SPIRVEmitSharedContex
...
+    {
+        // Already tagged with the spec-const rate qualifier.
+        if (isSpecConstRateType(inst->getFullType()))
+        {
+            isSpecConstFound = true;
+            return true;
+        }
+
+        // Literal constants are valid operands of OpSpecConstantOp.
+        if (as<IRConstant>(inst))
```
[the remark this answers is not in the document]
Comment (aidanfnv) [reply source/slang/slang-emit-spirv.cpp]: If a bare `IRStringLit` or `IRPtrLit` reaches the default case, the function returns true, but `isSpecConstFound` stays false, so the caller's `&& isSpecConstFound` gate prevents it from being routed to emitSpecializationConstantOp, but your suggestion is nice from a defensive programming perspective.

File: tests/spirv/spec-constant-select-global-const.slang [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+// Test that a ternary/select on specialization constants used as a global
+// constant value compiles successfully to SPIR-V using OpSpecConstantOp.
+// Regression test for https://github.com/shader-slang/slang/issues/10373
+
+// CHECK-DAG: %[[FOO2:[0-9A-Za-z_]+]] = OpSpecConstant %uint 0
+// CHECK-DAG: %[[FOO1:[0-9A-Za-z_]+]] = OpSpecConstant %uint 0
+// CHECK-DAG: OpSpecConstantOp %bool IEqual %[[FOO2]]
+// CHECK-DAG: OpSpecConstantOp %uint UDiv %[[FOO1]] %[[FOO2]]
+// CHECK-DAG: OpSpecConstantOp %uint Select
```
[the remark this answers is not in the document]
Comment (aidanfnv) [reply tests/spirv/spec-constant-select-global-const.slang]: Fixed

**Comment by aidanfnv** [comment]
Overhauled the change to move the fix upstream into lowering-to-IR.

File: source/slang/slang-lower-to-ir.cpp [hunk 3]
```diff
@@ -929,8 +929,24 @@ LoweredValInfo emitCallToDeclRef(
             SLANG_ASSERT(argCount == 2);
             return LoweredValInfo::simple(builder->emitGetOffsetPtr(args[0], args[1]));
         default:
-            return LoweredValInfo::simple(
-                builder->emitIntrinsicInst(type, intrinsicOp, argCount, args));
+            {
+                // At global scope, if any operand is spec-const-rate qualified,
```
Comment (csyonghe) [inline source/slang/slang-lower-to-ir.cpp]: I am curious why this is not needed for other operators (e.g. +/-), since they should all be handled by ValLoweringVisitor::visitFuncCallIntVal.

However your change here seem to suggest that lowering of ?: expr did not go through this path. We should figure that out and see what makes ?: expr lowered through a different path (through emitCallToDeclRef instead of visitFuncCallIntVal).

Comment (aidanfnv) [reply source/slang/slang-lower-to-ir.cpp]: `visitFuncCallIntVal` handles expressions that the semantic checker has folded into `IntVal` nodes, but `static const` initializers are lowered as regular `Expr` nodes through `lowerRValueExpr` and `emitCallToDeclRef`, so `visitFuncCallIntVal` is not reached.

This isn't specific to `?:`. I found that all operators on spec constants in `static const` initializers go through `emitCallToDeclRef`. I verified by compiling `static const uint add_val = FOO1 + FOO2; static const uint mul_val = FOO1 * FOO2;` etc. The IR shows regular `add`, `mul`, `div`, `cmpEQ`, `select` ops, not constexpr variants.

Comment (aidanfnv) [reply source/slang/slang-lower-to-ir.cpp]: I think that is because the semantic checker folds `static const` initializers using `tryConstantFoldExpr` with `ConstantFoldingKind::LinkTime`, and not with `ConstantFoldingKind::SpecializationConstant`.

Comment (csyonghe) [reply source/slang/slang-lower-to-ir.cpp]: It seems that `static const int a = FOO1+FOO2;` compiled without errors?

I wonder what happens if we simply try `tryConstantFoldExpr` to `ConstantFoldingKind::SpecializationConstant`?

Comment (aidanfnv) [reply source/slang/slang-lower-to-ir.cpp]: > You: I wonder what happens if we simply try tryConstantFoldExpr to ConstantFoldingKind::SpecializationConstant?

Changing the `tryConstantFoldExpr` call in the header checking pass (where `static const` initializers get folded) to use `ConstantFoldingKind::SpecializationConstant` doesn't work because that runs before the init expression has been semantically checked. At that point, the ternary operator's `SelectExpr` node hasn't been through `visitSelectExpr` yet, so its `functionExpr` doesn't have a resolved `DeclRef`, so `getDeclRef` returns null and the fold fails.

So instead, I changed the `tryConstantFoldDeclRef` call in `_validateCircularVarDefinition` to use `ConstantFoldingKind::SpecializationConstant`, and this call is during the body checking pass, after `CheckTerm` has already type-checked the init expression. At that point the operator `DeclRefs` are fully resolved and the fold succeeds, producing a `FuncCallIntVal` that captures the spec-const semantics.

> Me: visitFuncCallIntVal handles expressions that the semantic checker has folded into IntVal nodes, but static const initializers are lowered as regular Expr nodes through lowerRValueExpr and emitCallToDeclRef, so visitFuncCallIntVal is not reached.
This isn't specific to ?:. I found that all operators on spec constants in static const initializers go through emitCallToDeclRef

To solve this, the second part of my fix is to check `as<FuncCallIntVal>(decl->val)` and, if true, use `lowerSimpleVal(decl->val)`, which routes through `visitFuncCallIntVal`, and that way the `@SpecConst` gets propagated.
