### PR TITLE
Fix crash in calcCodePointCount when resolving source locations (#10616)

### LINKED ISSUE #10616: Crash in `Slang::UTF8Util::calcCodePointCount(const Slang::UnownedStringSlice &)`
# Issue Description

We have observed spurious crashes in slang-rhi tests for some time now. The test that crashes in slang is `texture-view-load-ro-single.d3d12`. It's worth mentioning that this test compiles a lot of shaders.

Full stack trace:
```
[Inline Frame] slang-compiler.dll!Slang::UTF8Util::calcCodePointCount(const Slang::UnownedStringSlice &) Line 199 (d:\a\slang\slang\source\core\slang-char-encode.cpp:199)
slang-compiler.dll!Slang::SourceFile::calcColumnIndex(int lineIndex, int offset, int) Line 595 (d:\a\slang\slang\source\compiler-core\slang-source-loc.cpp:595)
slang-compiler.dll!Slang::SourceView::getHandleLoc(Slang::SourceLoc loc, Slang::SourceLocType type) Line 388 (d:\a\slang\slang\source\compiler-core\slang-source-loc.cpp:388)
slang-compiler.dll!Slang::SourceView::getHumaneLoc(Slang::SourceLoc loc, Slang::SourceLocType type) Line 411 (d:\a\slang\slang\source\compiler-core\slang-source-loc.cpp:411)
[Inline Frame] slang-compiler.dll!Slang::SourceManager::getHumaneLoc(Slang::SourceLoc) Line 1013 (d:\a\slang\slang\source\compiler-core\slang-source-loc.cpp:1013)
slang-compiler.dll!Slang::SourceWriter::advanceToSourceLocation(const Slang::SourceLoc & sourceLocation) Line 344 (d:\a\slang\slang\source\slang\slang-emit-source-writer.cpp:344)
slang-compiler.dll!Slang::CLikeSourceEmitter::emitGlobalInstImpl(Slang::IRInst * inst) Line 5057 (d:\a\slang\slang\source\slang\slang-emit-c-like.cpp:5057)
[Inline Frame] slang-compiler.dll!Slang::CLikeSourceEmitter::emitGlobalInst(Slang::IRInst *) Line 5021 (d:\a\slang\slang\source\slang\slang-emit-c-like.cpp:5021)
slang-compiler.dll!Slang::CLikeSourceEmitter::executeEmitActions(const Slang::List<Slang::CLikeSourceEmitter::EmitAction,Slang::StandardAllocator> & actions) Line 5415 (d:\a\slang\slang\source\slang\slang-emit-c-like.cpp:5415)
slang-compiler.dll!Slang::CLikeSourceEmitter::emitModuleImpl(Slang::IRModule * module, Slang::DiagnosticSink * sink) Line 5434 (d:\a\slang\slang\source\slang\slang-emit-c-like.cpp:5434)
[Inline Frame] slang-compiler.dll!Slang::CLikeSourceEmitter::emitModule(Slang::IRModule *) Line 515 (d:\a\slang\slang\source\slang\slang-emit-c-like.h:515)
slang-compiler.dll!Slang::CodeGenContext::emitEntryPointsSourceFromIR(Slang::ComPtr<Slang::IArtifact> & outArtifact) Line 2239 (d:\a\slang\slang\source\slang\slang-emit.cpp:2239)
slang-compiler.dll!Slang::CodeGenContext::emitEntryPointsSource(Slang::ComPtr<Slang::IArtifact> & outArtifact) Line 166 (d:\a\slang\slang\source\slang\slang-code-gen.cpp:166)
slang-compiler.dll!Slang::CodeGenContext::emitWithDownstreamForEntryPoints(Slang::ComPtr<Slang::IArtifact> & outArtifact) Line 531 (d:\a\slang\slang\source\slang\slang-code-gen.cpp:531)
slang-compiler.dll!Slang::CodeGenContext::_emitEntryPoints(Slang::ComPtr<Slang::IArtifact> & outArtifact) Line 1151 (d:\a\slang\slang\source\slang\slang-code-gen.cpp:1151)
slang-compiler.dll!Slang::CodeGenContext::emitEntryPoints(Slang::ComPtr<Slang::IArtifact> & outArtifact) Line 1231 (d:\a\slang\slang\source\slang\slang-code-gen.cpp:1231)
slang-compiler.dll!Slang::TargetProgram::_createEntryPointResult(__int64 entryPointIndex, Slang::DiagnosticSink * sink, Slang::EndToEndCompileRequest * endToEndReq) Line 72 (d:\a\slang\slang\source\slang\slang-target-program.cpp:72)
slang-compiler.dll!Slang::TargetProgram::getOrCreateEntryPointResult(__int64 entryPointIndex, Slang::DiagnosticSink * sink) Line 117 (d:\a\slang\slang\source\slang\slang-target-program.cpp:117)
slang-compiler.dll!Slang::ComponentType::getEntryPointCode(__int64 entryPointIndex, __int64 targetIndex, ISlangBlob * * outCode, ISlangBlob * * outDiagnostics) Line 258 (d:\a\slang\slang\source\slang\slang-linkable.cpp:258)
slang-rhi-tests.exe!rhi::Device::getEntryPointCodeFromShaderCache(rhi::ShaderProgram * program, slang::IComponentType * componentType, const char * entryPointName, unsigned int entryPointIndex, unsigned int targetIndex, ISlangBlob * * outCode, ISlangBlob * * outDiagnostics) Line 413 (c:\src\slang-rhi\src\device.cpp:413)
slang-rhi-tests.exe!rhi::ShaderProgram::compileShaders::__l2::<lambda_1>::operator()(slang::EntryPointReflection * entryPointInfo, slang::IComponentType * entryPointComponent, unsigned int entryPointIndex) Line 123 (c:\src\slang-rhi\src\shader.cpp:123)
slang-rhi-tests.exe!rhi::ShaderProgram::compileShaders(rhi::Device * device) Line 151 (c:\src\slang-rhi\src\shader.cpp:151)
slang-rhi-tests.exe!rhi::Device::createComputePipeline(const rhi::ComputePipelineDesc & desc, rhi::IComputePipeline * * outPipeline) Line 716 (c:\src\slang-rhi\src\device.cpp:716)
slang-rhi-tests.exe!rhi::debug::DebugDevice::createComputePipeline(const rhi::ComputePipelineDesc & desc, rhi::IComputePipeline * * outPipeline) Line 1046 (c:\src\slang-rhi\src\debug-layer\debug-device.cpp:1046)
slang-rhi-tests.exe!TextureViewTest::getReadPipeline(TextureViewType textureViewType, rhi::TextureType textureType, rhi::Format format, ReadMethod readMethod) Line 753 (c:\src\slang-rhi\tests\test-texture-view.cpp:753)
slang-rhi-tests.exe!TextureViewTest::readTexelsDevice(TextureViewType textureViewType, rhi::ITextureView * textureView, std::span<TexelData,-1> texels, ReadMethod readMethod) Line 767 (c:\src\slang-rhi\tests\test-texture-view.cpp:767)
slang-rhi-tests.exe!GPU_TEST_ANONYMOUS_47::__l2::<lambda_1>::operator()(rhi::testing::TextureTestContext * c) Line 1191 (c:\src\slang-rhi\tests\test-texture-view.cpp:1191)
slang-rhi-tests.exe!rhi::testing::runTextureTest::__l2::<lambda_1>::operator()(const rhi::testing::TextureTestVariant & variant) Line 562 (c:\src\slang-rhi\tests\texture-test.h:562)
slang-rhi-tests.exe!std::invoke<`rhi::testing::runTextureTest<`GPU_TEST_ANONYMOUS_47'::`2'::<lambda_1>>'::`2'::<lambda_1> &,rhi::testing::TextureTestVariant const &>(rhi::testing::runTextureTest::__l2::<lambda_1> & _Obj, const rhi::testing::TextureTestVariant & _Arg1) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::runTextureTest<`GPU_TEST_ANONYMOUS_47'::`2'::<lambda_1>>'::`2'::<lambda_1>,void,rhi::testing::TextureTestVariant const &>::_Do_call(const rhi::testing::TextureTestVariant & <_Args_0>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,rhi::testing::TextureTestVariant const &>::operator()(const rhi::testing::TextureTestVariant & <_Args_0>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 768 (c:\src\slang-rhi\tests\texture-test.cpp:768)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::applyTextureSize(int state, rhi::testing::TextureTestVariant variant) Line 1292 (c:\src\slang-rhi\tests\texture-test.cpp:1292)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::addVariants::__l2::<lambda_3>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 393 (c:\src\slang-rhi\tests\texture-test.h:393)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::addVariants<enum rhi::testing::TTShape,enum rhi::testing::TTArray,enum rhi::testing::TTMip,enum rhi::testing::TTMS,enum rhi::testing::TTPowerOf2,enum rhi::testing::TTFmtCompressed,enum rhi::testing::TTFmtDepth,enum rhi::TextureUsage>'::`2'::<lambda_3> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::addVariants::__l2::<lambda_3> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::addVariants<enum rhi::testing::TTShape,enum rhi::testing::TTArray,enum rhi::testing::TTMip,enum rhi::testing::TTMS,enum rhi::testing::TTPowerOf2,enum rhi::testing::TTFmtCompressed,enum rhi::testing::TTFmtDepth,enum rhi::TextureUsage>'::`2'::<lambda_3>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::filterFormat(int state, rhi::testing::TextureTestVariant variant) Line 1239 (c:\src\slang-rhi\tests\texture-test.cpp:1239)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::addVariants::__l2::<lambda_2>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 385 (c:\src\slang-rhi\tests\texture-test.h:385)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::addVariants<enum rhi::testing::TTShape,enum rhi::testing::TTArray,enum rhi::testing::TTMip,enum rhi::testing::TTMS,enum rhi::testing::TTPowerOf2,enum rhi::testing::TTFmtCompressed,enum rhi::testing::TTFmtDepth,enum rhi::TextureUsage>'::`2'::<lambda_2> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::addVariants::__l2::<lambda_2> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::addVariants<enum rhi::testing::TTShape,enum rhi::testing::TTArray,enum rhi::testing::TTMip,enum rhi::testing::TTMS,enum rhi::testing::TTPowerOf2,enum rhi::testing::TTFmtCompressed,enum rhi::testing::TTFmtDepth,enum rhi::TextureUsage>'::`2'::<lambda_2>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::postProcessVariant(int state, rhi::testing::TextureTestVariant variant) Line 1176 (c:\src\slang-rhi\tests\texture-test.cpp:1176)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::addVariants::__l2::<lambda_1>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 377 (c:\src\slang-rhi\tests\texture-test.h:377)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::addVariants<enum rhi::testing::TTShape,enum rhi::testing::TTArray,enum rhi::testing::TTMip,enum rhi::testing::TTMS,enum rhi::testing::TTPowerOf2,enum rhi::testing::TTFmtCompressed,enum rhi::testing::TTFmtDepth,enum rhi::TextureUsage>'::`2'::<lambda_1> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::addVariants::__l2::<lambda_1> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::addVariants<enum rhi::testing::TTShape,enum rhi::testing::TTArray,enum rhi::testing::TTMip,enum rhi::testing::TTMS,enum rhi::testing::TTPowerOf2,enum rhi::testing::TTFmtCompressed,enum rhi::testing::TTFmtDepth,enum rhi::TextureUsage>'::`2'::<lambda_1>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 1030 (c:\src\slang-rhi\tests\texture-test.cpp:1030)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 985 (c:\src\slang-rhi\tests\texture-test.cpp:985)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 1007 (c:\src\slang-rhi\tests\texture-test.cpp:1007)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 1018 (c:\src\slang-rhi\tests\texture-test.cpp:1018)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 940 (c:\src\slang-rhi\tests\texture-test.cpp:940)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 898 (c:\src\slang-rhi\tests\texture-test.cpp:898)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 919 (c:\src\slang-rhi\tests\texture-test.cpp:919)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1>::operator()(int state, rhi::testing::TextureTestVariant variant) Line 844 (c:\src\slang-rhi\tests\texture-test.cpp:844)
slang-rhi-tests.exe!std::invoke<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1> &,int,rhi::testing::TextureTestVariant>(rhi::testing::TextureTestOptions::processVariantArg::__l2::<lambda_1> & _Obj, int && _Arg1, rhi::testing::TextureTestVariant && <_Args2_0>) Line 1680 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\type_traits:1680)
slang-rhi-tests.exe!std::_Func_impl_no_alloc<`rhi::testing::TextureTestOptions::processVariantArg'::`2'::<lambda_1>,void,int,rhi::testing::TextureTestVariant>::_Do_call(int && <_Args_0>, rhi::testing::TextureTestVariant && <_Args_1>) Line 880 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:880)
slang-rhi-tests.exe!std::_Func_class<void,int,rhi::testing::TextureTestVariant>::operator()(int <_Args_0>, rhi::testing::TextureTestVariant <_Args_1>) Line 926 (c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.44.35207\include\functional:926)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::next(int nextIndex, rhi::testing::TextureTestVariant variant) Line 760 (c:\src\slang-rhi\tests\texture-test.cpp:760)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::executeGeneratorList(int listIdx) Line 751 (c:\src\slang-rhi\tests\texture-test.cpp:751)
slang-rhi-tests.exe!rhi::testing::TextureTestOptions::run(std::function<void __cdecl(rhi::testing::TextureTestVariant const &)> func) Line 727 (c:\src\slang-rhi\tests\texture-test.cpp:727)
slang-rhi-tests.exe!rhi::testing::runTextureTest<`GPU_TEST_ANONYMOUS_47'::`2'::<lambda_1>>(rhi::testing::TextureTestOptions & options, GPU_TEST_ANONYMOUS_47::__l2::<lambda_1> && func) Line 542 (c:\src\slang-rhi\tests\texture-test.h:542)
slang-rhi-tests.exe!GPU_TEST_ANONYMOUS_47(rhi::testing::GpuTestContext * ctx, Slang::ComPtr<rhi::IDevice> device) Line 1150 (c:\src\slang-rhi\tests\test-texture-view.cpp:1150)
slang-rhi-tests.exe!rhi::testing::gpuTestTrampoline() Line 1006 (c:\src\slang-rhi\tests\testing.cpp:1006)
slang-rhi-tests.exe!doctest::Context::run() Line 7007 (c:\src\slang-rhi\external\doctest\doctest.h:7007)
slang-rhi-tests.exe!main(int argc, const char * * argv) Line 98 (c:\src\slang-rhi\tests\main.cpp:98)
slang-rhi-tests.exe!invoke_main() Line 79 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79)
slang-rhi-tests.exe!__scrt_common_main_seh() Line 288 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
slang-rhi-tests.exe!__scrt_common_main() Line 331 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331)
slang-rhi-tests.exe!mainCRTStartup(void * __formal) Line 17 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17)
kernel32.dll!00007ffbe62ce8d7() (Unknown Source:0)
ntdll.dll!00007ffbe743c34c() (Unknown Source:0)
```

# Reproducer Code
I can reproduce this crash locally by running `slang-rhi-tests.exe -tc=*.d3d12 -verbose`. It doesn't always crash, but happens from time to time. It seems important to run the full test suite (i.e. `*.d3d12`) and not just the crashing test case.

# Expected Behavior
No crash.

# Actual Behavior
Crash.

# Environment
 - Slang Version 2026.4.1 (but happened on previous releases as well)
 - Windows

### PR DESCRIPTION
**Pull request by NV-xiaoyongs**
Fixes #10616

Fix crash in `UTF8Util::calcCodePointCount` by correcting the `m_contentSize` invariant after BOM/encoding decoding in `setContents()`.

## Root Cause

`SourceFile::setContents(ISlangBlob*)` decodes BOM and non-UTF-8 encodings into a smaller decoded buffer, but previously did not update `m_contentSize` to reflect the decoded size. This caused `getContentSize()` to return the raw file size, which `getOffsetRangeAtLineIndex()` used to compute the last line's end offset — producing a range extending past the actual content buffer. In Release builds (where `SLANG_ASSERT` is compiled out), this led to an out-of-bounds read in `calcCodePointCount`.

## Fix

Update `m_contentSize = decodedContentSize` after BOM/encoding processing in `setContents()`, so `getContentSize()` always reflects the actual decoded content length.

## Test Plan

- Added `sourceFileBomContentSize` unit test that creates source files with UTF-8 BOM and UTF-16 LE BOM content, verifies `getContentSize() == getContent().getLength()`, and exercises the crash path (`calcColumnIndex` on last line).
- Test deterministically fails without the fix, passes with it.
- Verified locally on Windows: 0/5 crash rate with fix vs 1/5 on master (see PR comments).
- 240/240 smoke tests pass.

### CODE REVIEW

**Comment by skallweitNV** [comment]
@NV-xiaoyongs LGTM but the true test would be to reproduce the crash in slang-rhi before this fix and make sure it doesn't crash with the fix applied. Did you verify that?

**Comment by NV-xiaoyongs** [comment]
> @NV-xiaoyongs LGTM but the true test would be to reproduce the crash in slang-rhi before this fix and make sure it doesn't crash with the fix applied. Did you verify that?

Yes, verified locally on Windows (Release build, NVIDIA RTX A1000 6GB, MSVC 19.50):

Without fix (master): texture-view-load-ro-single.d3d12 crashes with SIGSEGV in 1 out of 5 serial runs of slang-rhi-tests -tc="*.d3d12", confirming the intermittent crash.

With fix (cherry-picked onto master): 0 crashes in 5 serial runs, all 230 D3D12 tests pass every time.

File: source/compiler-core/slang-source-loc.cpp [hunk 1]
```diff
@@ -520,10 +520,14 @@ UnownedStringSlice SourceFile::getLineAtIndex(Index lineIndex)
     if (range.isValid() && hasContent())
     {
         const UnownedStringSlice content = getContent();
-        SLANG_ASSERT(range.end <= uint32_t(content.getLength()));
+        const uint32_t contentLen = uint32_t(content.getLength());
+        SLANG_ASSERT(range.end <= contentLen);
+
+        const uint32_t clampedStart = (range.start <= contentLen) ? range.start : contentLen;
+        const uint32_t clampedEnd = (range.end <= contentLen) ? range.end : contentLen;
```
Comment (jhelferty-nv) [inline source/compiler-core/slang-source-loc.cpp]: If we were going to do this (which I don't think we should), I'd suggest using `Math::max` and `Math::min` instead.

Is this actually still needed with the `m_contentSize` change below? If it doesn't look like it, then instead of clamping and potentially returning garbage, I'd suggest generating/contributing to a warning diagnostic while `return UnownedStringSlice();` from here. This really feels like if we get into this situation, we shouldn't be completely ignoring it; the user really should know that something went quite wrong.

File: source/compiler-core/slang-source-loc.cpp [hunk 2]
```diff
@@ -650,6 +659,11 @@ void SourceFile::setContents(ISlangBlob* blob)
     char const* decodedContentEnd = decodedContentBegin + decodedContentSize;
 
     m_content = UnownedStringSlice(decodedContentBegin, decodedContentEnd);
+
+    // Update m_contentSize to the decoded size so that getContentSize() always reflects the
+    // actual content length. For UTF-8 without BOM this is a no-op; for BOM or non-UTF-8 files,
+    // the decoded size may differ from the raw file size.
+    m_contentSize = decodedContentSize;
```
[the remark this answers is not in the document]
Comment (jhelferty-nv) [reply source/compiler-core/slang-source-loc.cpp:657]: It feels like this change here should fix the problem on its own. Do we really still need the other stuff earlier in the patch?

File: source/compiler-core/slang-source-loc.cpp [hunk 3]
```diff
@@ -590,7 +594,12 @@ int SourceFile::calcColumnIndex(int lineIndex, int offset, int tabSize)
 
     const auto line = getLineAtIndex(lineIndex);
 
-    const auto head = line.head(colOffset);
+    // Clamp colOffset to [0, line.getLength()] to prevent out-of-bounds access when
+    // the offset exceeds the line (e.g., due to stale source locations or size mismatches).
+    const int clampedColOffset =
+        (colOffset < 0) ? 0 : ((colOffset > line.getLength()) ? int(line.getLength()) : colOffset);
```
Comment (jhelferty-nv) [inline source/compiler-core/slang-source-loc.cpp]: Similar to above, is this still needed with the `m_contentSize` fix? If we have legit issues showing up here still, that's still pretty serious and shouldn't be papered over.

Comment (NV-xiaoyongs) [reply source/compiler-core/slang-source-loc.cpp]: >>  "do we still need the other stuff?"
You're right — this is the root fix and should handle it on its own. I've removed the defensive clamping in getLineAtIndex and calcColumnIndex.
>> calcColumnIndex clamping
Agreed — removed. With the m_contentSize fix, colOffset should stay within line bounds. The existing SLANG_ASSERT in head() will catch any future issues in Debug.

File: source/compiler-core/slang-source-loc.cpp (hunk 1 above)
Comment (NV-xiaoyongs) [reply source/compiler-core/slang-source-loc.cpp]: Good point. Removed the clamping — the m_contentSize fix is the root cause, and with it corrected, getOffsetRangeAtLineIndex will return correct ranges. The existing SLANG_ASSERT already catches violations in Debug builds. If something else produces out-of-bounds ranges in the future, that should surface as a Debug assert rather than being silently papered over.
