### PR TITLE
Fix false positives from _CrtDumpMemoryLeaks in MSVC Debug

### LINKED ISSUE #10904: Slang (debug) does not build with latest MSVC on Windows for versions v2026.5 or later
I'm using the latest version of Visual Studio build tools (17.14.30) on Windows. I can build releases v2026.4.2 or earlier, but staring with v2026.5 and later, debug builds from source fail. I've seen this error before and it was corrected once previously. It seems it's back. The build error is listed below:

Building Custom Rule C:/SDKBuild/build-X64-1.4.349.0/slangd/tools/CMakeLists.txt
  main.cpp
  slang-bootstrap.vcxproj -> C:\SDKBuild\build-X64-1.4.349.0\slangd\build\generators\Debug\bin\slang-bootstrap.exe
  Generating slang-core-module-generated.h, ../slang-glsl-module/slang-glsl-module-generated.h
  Compiling core module on debug build, this can take a while.
  Compiling core module took 23.00 seconds.
  Detected memory leaks!
  Dumping objects ->
  {17106561} normal block at 0x000001D9B291D7C0, 32 bytes long.
   Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  {17106560} normal block at 0x000001D9B2911110, 16 bytes long.
   Data: <  "F            > B8 ED 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  {17106559} normal block at 0x000001D9B2911340, 16 bytes long.
   Data: <  "F            > 98 ED 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  {650} normal block at 0x000001D9B2917800, 49 bytes long.
   Data: <   E            > 08 B1 FB 45 F8 7F 00 00 01 00 00 00 00 00 00 00
  {649} normal block at 0x000001D9B291DCA0, 32 bytes long.
   Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  {648} normal block at 0x000001D9B291A060, 16 bytes long.
   Data: <P "F            > 50 ED 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  {647} normal block at 0x000001D9B291A600, 16 bytes long.
   Data: <0 "F            > 30 ED 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  {646} normal block at 0x000001D9B291DEE0, 32 bytes long.
   Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  {645} normal block at 0x000001D9B291A010, 16 bytes long.
   Data: <  "F            > 00 ED 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  {644} normal block at 0x000001D9B291A5B0, 16 bytes long.
   Data: <  "F            > E0 EC 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  {643} normal block at 0x000001D9B291D1C0, 32 bytes long.
   Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  {642} normal block at 0x000001D9B291A560, 16 bytes long.
   Data: <  "F            > A8 EC 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  {641} normal block at 0x000001D9B291AF60, 16 bytes long.
   Data: <  "F            > 88 EC 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  {640} normal block at 0x000001D9B291D160, 32 bytes long.
   Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  {639} normal block at 0x000001D9B291A4C0, 16 bytes long.
   Data: <X "F            > 58 EC 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  {638} normal block at 0x000001D9B291AEC0, 16 bytes long.
   Data: <8 "F            > 38 EC 22 46 F8 7F 00 00 00 00 00 00 00 00 00 00
  Object dump complete.
  Assertion failed: !memleakDetected, file C:\SDKBuild\build-X64-1.4.349.0\slangd\source\slangc\main.cpp, line 169
  abort() has been called

### PR DESCRIPTION
**Pull request by jkwak-work**
Tear down the ReplayContext singleton in slang_shutdown() so its state is freed before the CRT memory dump runs, instead of only resetting handlers on a function-local static that is never destroyed.

For unknown SLANG_TAG_VERSION, format the shared-library timestamp with snprintf into a static char buffer instead of a heap-allocated String, and keep the same PRIu64 formatting as elsewhere in the codebase.

Fixes #10904

### CODE REVIEW

File: source/slang-record-replay/replay-context.cpp [hunk 1]
```diff
@@ -124,21 +124,20 @@ DataMismatchException::DataMismatchException(size_t offset, size_t size)
...
-// can observe construction from other threads without racing against a
-// concurrent get() call. Guarded by s_contextMutex to match the thread-safety
-// contract documented on get().
+// Singleton pointer and its mutex. Using heap allocation instead of a
+// function-local static so that destroySingleton() can fully release the
+// instance (including its STL container internals) before _CrtDumpMemoryLeaks()
+// runs in wmain(), preventing false leak reports in MSVC Debug builds when
+// CMAKE_MSVC_RUNTIME_LIBRARY is the default MultiThreadedDebugDLL (/MDd).
 static std::mutex s_contextMutex;
 static ReplayContext* s_contextInstance = nullptr;
```
Comment (jkwak-work) [inline source/slang-record-replay/replay-context.cpp:133]: @ccummingsNV , @aidanfnv , would it make more sense to have `thread_local` for this variable without mutex?

**Review by kaizhangNV — DISMISSED** [review]

File: source/slang-record-replay/replay-context.cpp (hunk 1 above)
Comment (aidanfnv) [reply source/slang-record-replay/replay-context.cpp:133]: The idea is that every thread shares the same context so that we can serialize the recording, so I do not think it would not make much sense to have that be thread_local.

**Review by aidanfnv — COMMENTED** [review]
Looks good to me. Thanks!

**Review by aidanfnv — APPROVED** [review]
