### PR TITLE
Fix IR lowering for generic interface types.

### LINKED ISSUE #4749: TypeConformance with generics does not work
So when having an interface which is templated, it is possible now to correctly set the type conformance with strings of the interface and implementation struct + the implementing generic type "TestInterface\<float>" "TestInterfaceImpl\<float>". Sadly this still results in an 

```error 50100: No type conformances are found for interface 'TestInterface'. Code generation for current target requires at least one implementation type present in the linkage.```
error

Shortened code:
```cpp
public interface TestInterface<Real> {
    Real sample();
}

struct TestInterfaceImpl<Real> : TestInterface<Real> {
    Real sample() {
        return x;
    }
    Real x;
}

StructuredBuffer<TestInterface<float>> data;
```

### PR DESCRIPTION
**Pull request by csyonghe**
Closes #4749.

The issue being fixed here is that when we lower a generic interface to IR, the function types aren't lowered from proper DeclRef with default substitute info, so they end up being direct `IRGeneric` insts, instead of a `specialize(IRGeneric, ...)` inst. This leads to incorrect interface types after specialization pass. The fix is simply lower the function types using a declref.

### CODE REVIEW

File: tools/slang-test/slang-test-main.cpp [hunk 1]
```diff
@@ -4617,8 +4617,8 @@ SlangResult innerMain(int argc, char** argv)
 int main(int argc, char** argv)
 {
     const SlangResult res = innerMain(argc, argv);
-
     slang::shutdown();
+    Slang::RttiInfo::deallocateAll();
```
Comment (jkwak-work) [inline tools/slang-test/slang-test-main.cpp:4621]: We may need a document for how to properly shut everything down and deallocate cleanly.
Many user applications will want to shutdown properly to check the memory leaks of their own applications.

**Review by jkwak-work — APPROVED** [review]
Looks good to me.

**Comment by jkwak-work** [comment]
I wonder if this can fix #3804 as well

File: tools/slang-test/slang-test-main.cpp (hunk 1 above)
Comment (csyonghe) [reply tools/slang-test/slang-test-main.cpp:4621]: This is only needed in slang-test-main because slang-test uses the RTTI functionality directly through static linking, so there is a different instance of slang::RTTIInfo that needs to be cleaned up separately. Normal users of slang.dll shouldn't need to do this.

**Comment by csyonghe** [comment]
> I wonder if this can fix #3804 as well

Not quite, that one requires a more fundamental change to our IR rules.
