### PR TITLE
fix bug in shared memory pointer

### LINKED ISSUE #9110: [neural.slang] Invalid pointer operation for shared memory
# Issue Description
Slang generate invalid pointer offset instruction for Workgroup pointer.

# Reproducer Code
```
uniform int* outputBuffer;
groupshared uint4 shared[2];

void foo(Ptr<uint4, Access::ReadWrite, AddressSpace::GroupShared> ptr)
{
    ptr[0] = uint4(1, 2, 3, 4);
    ptr[1] = uint4(5, 6, 7, 8);
}

[numthreads(1, 1, 1)]
void computeMain(uint3 group_thread_id: SV_GroupThreadID)
{
    shared[0] = uint4(0, 0, 0, 0);
    shared[1] = uint4(0, 0, 0, 0);

    foo(__getAddress(shared[0]));

    outputBuffer[0] = shared[0].x;
    outputBuffer[1] = shared[0].y;
    outputBuffer[2] = shared[0].z;
    outputBuffer[3] = shared[0].w;

    outputBuffer[4] = shared[1].x;
    outputBuffer[5] = shared[1].y;
    outputBuffer[6] = shared[1].z;
    outputBuffer[7] = shared[1].w;
}
```

# Expected Behavior
The code will compile and execute.

# Actual Behavior
Vulkan validation error is reported as we will generate invalid instruction `OpPtrAccessChain` where the `base` and `result` have different storage class.

# Environment
 - Slang Version: ToT
 - OS: Any

# Additional context

### PR DESCRIPTION
**Pull request by kaizhangNV**
Close #9110.

Fix the issue that we could generate invalid spirv code for shared memory.
Slang supports using shared memory as a function parameter, however if there is pointer offset operation inside the function, it will generate invalid code.
e.g.
```
void foo(Ptr<....., AddressSpace::GroupShared> ptr)
{
    ptr[2] = xxx;
    or xxx = ptr[2];          // theses code will generate invalid code
}
```

The reason is that, our currently logic is to convert the pointer of shared memory into a `Function` storage pointer, and pass it to a function as the spirv restriction that the function call require the pointer operand as a memory object. 
This will bring a problem that for pointer offset operation like OpPtrAccessChain, it will violate the rule because the storage class of base pointer and result pointer type of this instruction is the different (base is `Function` while result is `Workgroup`). 

This conversion logic is added in the spirv legalization pass. However, this restriction is removed when using Variable pointer capability and when the pointer is `Workgroup` storage class. So we can skip this conversion when the pointer has `GroupShared` address space.

### CODE REVIEW

File: source/slang/slang-ir-spirv-legalize.cpp [hunk 1]
```diff
@@ -877,7 +877,8 @@ struct SPIRVLegalizationContext : public SourceEmitterBase
         // >     declaration, or
         // >     - a pointer to an element in an array that is a memory object
         // >       declaration, where the element type is OpTypeSampler or OpTypeImage.
-        //
+        // >   However, this restriction is removed for Workgroup and StorageBuffer if
+        //     VariablePointers or VariablePointersStorageBuffer is declared.
```
Comment (jkwak-work) [inline source/slang/slang-ir-spirv-legalize.cpp]: I don't think this is a right way to add the information.
The current comment uses `>` as a mean to say it is a quote from the spec document word-by-word.

I suggest a format like the following,


// However, this restriction is removed for Workgroup and StorageBuffer if
// VariablePointers or VariablePointersStorageBuffer is declared.
// > If the VariablePointers or VariablePointersStorageBuffer [capability](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Capability) is declared, (...)
// > For pointer operands to [OpFunctionCall](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpFunctionCall), the [memory object declaration](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#MemoryObjectDeclaration)-restriction is removed for the following [storage classes](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Storage_Class):
// >   - StorageBuffer
// >   - Workgroup

Comment (kaizhangNV) [reply source/slang/slang-ir-spirv-legalize.cpp]: done

**Review by expipiplus1 — APPROVED** [review]
