### PR TITLE
Fix Metal DescriptorHandle as_type cast in dynamic dispatch

### LINKED ISSUE #10477: [Metal] DescriptorHandle in dynamic dispatch emits invalid as_type casts
## Issue Description

When a `DescriptorHandle<T>` field is used in an interface implementation that goes through dynamic dispatch, the Metal backend emits `as_type<uint2>(ptr)` and `as_type<float device*>(uint2(...))` in the AnyValue pack/unpack functions. Metal does not allow `as_type` casts between pointer and non-pointer types, so the generated shader fails to compile.

## Reproducer Code

```hlsl
interface ISource
{
    float get(int i);
}

struct BufSource : ISource
{
    StructuredBuffer<float>.Handle h;
    float get(int i) { return h[i]; }
}

struct ConstSource : ISource
{
    float v;
    float get(int i) { return v; }
}

ISource make(int kind, StructuredBuffer<float>.Handle h)
{
    if (kind == 0)
    {
        BufSource s;
        s.h = h;
        return s;
    }
    ConstSource c;
    c.v = 1.0;
    return c;
}

uniform StructuredBuffer<float>.Handle buf;
RWStructuredBuffer<float> output;

[numthreads(1,1,1)]
void computeMain()
{
    ISource src = make(0, buf);
    output[0] = src.get(0);
}
```

**Command:**
```bash
slangc repro.slang -target metal -entry computeMain -stage compute
```

## Expected Behavior

The generated Metal shader should compile successfully, using a valid mechanism to store descriptor handles into the AnyValue uint32 fields.

## Actual Behavior

The generated Metal code contains illegal casts:

```metal
uint2 _S5 = as_type<uint2>(_S3->h_0);                                     // pack
(&_S7)->h_0 = as_type<float device*>(uint2(_S6->field0_0, _S6->field1_0)); // unpack
```

Metal's `as_type` does not support casting between pointer and non-pointer types:

```
error: as_type cast from 'device float *' to 'uint2' is not allowed
error: as_type cast from 'uint2' to 'device float *' is not allowed
```

## Test Plan

Once fixed, re-enable the Metal backend in the DescriptorHandle dynamic dispatch tests by adding `-mtl -compute -shaderobj -output-using-type` test lines to:
- `tests/language-feature/dynamic-dispatch/layout-descriptor-handle-dispatch.slang`
- `tests/language-feature/dynamic-dispatch/layout-descriptor-handle-multi.slang`
- `tests/language-feature/dynamic-dispatch/layout-descriptor-handle-array.slang`

### PR DESCRIPTION
**Pull request by jvepsalainen-nv**
## Summary

Fixes #10477

- On Metal, `DescriptorHandle<T>` is emitted as a pointer type (e.g., `device float*`), but the AnyValue pack/unpack code used `emitBitCast` which becomes `as_type<>` in Metal — invalid for pointer↔non-pointer casts
- For Metal targets, convert through `uint64` using `CastDescriptorHandleToUInt64`/`CastUInt64ToDescriptorHandle` IR ops with C-style casts `(ulong)(ptr)` / `(ptrType)(ulong_val)` in the Metal emitter, then split/combine via standard integer shift/truncate operations
- Re-enables Metal test lines in existing `layout-descriptor-handle-{dispatch,multi,array}.slang` tests

### Changes
- `source/slang/slang-ir-any-value-marshalling.cpp`: Metal-specific path in bindless `marshalDescriptorHandle` that avoids bitcast between pointer and non-pointer types
- `source/slang/slang-emit-metal.cpp`: Override `CastDescriptorHandleToUInt64`/`CastUInt64ToDescriptorHandle` (and UInt2 variants) to emit proper pointer↔integer C-style casts
- `tests/metal/descriptor-handle-dynamic-dispatch.slang`: New compile-only regression test verifying the Metal output uses `(ulong)` casts instead of `as_type`

## Test plan

- [x] New `tests/metal/descriptor-handle-dynamic-dispatch.slang` compile test (filecheck on Metal output)
- [x] Existing `layout-descriptor-handle-dispatch.slang` CPU test passes
- [x] Existing `layout-descriptor-handle-multi.slang` CPU test passes
- [x] Existing `layout-descriptor-handle-array.slang` CPU test passes
- [x] CI: Metal GPU tests for re-enabled `-mtl` test lines

### CODE REVIEW

File: source/slang/slang-ir-any-value-marshalling.cpp [hunk 1]
```diff
@@ -666,18 +666,53 @@ struct AnyValueMarshallingContext
...
+                            builder->getUInt64Type(),
+                            kIROp_CastDescriptorHandleToUInt64,
+                            1,
+                            &srcVal);
+                        auto lowBits = builder->emitCast(builder->getUIntType(), uint64Val);
+                        auto highBits = builder->emitShr(
+                            builder->getUInt64Type(),
+                            uint64Val,
+                            builder->getIntValue(builder->getIntType(), 32));
+                        highBits = builder->emitCast(builder->getUIntType(), highBits);
```
Comment (skiminki-nv) [inline source/slang/slang-ir-any-value-marshalling.cpp:684]: This looks dubious for performance.

uint64_t is supported since Metal 2.2. The minimum metal version Slang supports is 2.3

Comment (jvepsalainen-nv) [reply source/slang/slang-ir-any-value-marshalling.cpp:684]: The split into two uint32 fields is required by the AnyValue layout — all fields are uint32, so any 8-byte value must be decomposed. This is functionally the same as the non-Metal path which does `bitcast(handle → uint2)` + `extractElement` — just using `(ulong)(ptr)` + shift/truncate instead, since `as_type<>` can't cast pointers on Metal.

The shift+truncate should optimize to equivalent code on the Metal compiler backend. Do you see a specific concern beyond the integer decomposition?

Comment (skiminki-nv) [reply source/slang/slang-ir-any-value-marshalling.cpp:684]: I suppose I got distracted by this deleted comment:

> // Use uint2 instead of uint64 to avoid Int64 capability requirement

The whole dynamic dispatch mechanism in general is somewhat dubious for performance. In Metal, what we should really do is to use tagged `union`s, instead of manually serializing the data. The same applies to CUDA and SPIR-V (to some degree at least).

**Review by skiminki-nv — APPROVED** [review]
LGTM
