### PR TITLE
Fix WGSL parameter block binding.

### LINKED ISSUE #5222: slang-RHI/WebGPU: Binding missing from bind group layout
This issue was split from https://github.com/shader-slang/slang/issues/5172.

Affected tests under `tests/compute` (currently disabled):
- Category 1: `Binding doesn't exist in...`
   - column-major
   - constant-buffer-memory-packing
   - func-cbuffer-param
   - parameter-block
   - non-square-column-major
- Category 2: `Number of entries X did not match the expected number of entries Y...`
   - kernel-context-threading
   - matrix-layout (.hlsl)
   - non-square-row-major
   - row-major

Tasks:
- Investigate and fix the issue(s)
- Try to enable the tests listed above

### PR DESCRIPTION
**Pull request by csyonghe**
Closes #5222.

### CODE REVIEW

File: source/slang/slang-emit-wgsl.cpp [hunk 1]
```diff
@@ -87,9 +87,23 @@ void WGSLSourceEmitter::emitParameterGroupImpl(
     auto varLayout = getVarLayout(varDecl);
     SLANG_RELEASE_ASSERT(varLayout);
 
-    for (auto attr : varLayout->getOffsetAttrs())
+    EmitVarChain blockChain(varLayout);
```
Comment (expipiplus1) [inline source/slang/slang-emit-wgsl.cpp:90]: we're finally web3

**Review by expipiplus1 — DISMISSED** [review]

File: source/slang/slang-emit-wgsl.cpp (hunk 1 above)
Comment (aleino-nv) [reply source/slang/slang-emit-wgsl.cpp:90]: > we're finally web3

Speaking of block chains...

Comment (csyonghe) [reply source/slang/slang-emit-wgsl.cpp:90]: I am not accountable for this. The code and naming is copied from the glsl implementation. I am curious who did this.
