### PR TITLE
Fixes `ValLoweringVisitor::visitNamedExpressionType` issue 

### LINKED ISSUE #559: Slang trying to lower generic constraint decl to IR
The following test case causes Slang to crash:
```
//TEST(compute):COMPARE_COMPUTE_EX:-slang -compute
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out

interface IIntegrator
{
    associatedtype ResultType;
    ResultType calc(ResultType prev);
    ResultType getInit();
}

interface ILightCollection
{
    T.ResultType integrate<T:IIntegrator>(T.ResultType prev, T integrator);
}

interface I
{
    float r();
};

struct Collection : ILightCollection
{
    T.ResultType integrate<T:IIntegrator>(T.ResultType prev, T integrator)
    {
        return integrator.calc(integrator.getInit());
    }
};
struct Integrator<U:I> : IIntegrator
{
    typedef float ResultType;
    U obj;
    ResultType calc(ResultType prev)
    {
        return prev + obj.r();
    }
    ResultType getInit() { return 0.0; }
};


struct Impl : I
{
    float r() {return 1.0;}    
};


RWStructuredBuffer<int> outputBuffer;
[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    Impl impl;
    Integrator<Impl> integrator;
    Collection c;
    int val = c.integrate(integrator.getInit(), integrator);
    outputBuffer[dispatchThreadID.x] = val;
}
```

The compiler crashes when trying to generate IR code for `Collection.integrate`.
When lowering the `c.integrate` call in `computeMain`, it will first try to lower the return type, which is `T.ResultType` with subst {T->Integrator<Impl>}. This will result a dispatch into `ValLoweringVisitor::visitNamedExpressionType()`, whose implementation is calling `emitDeclRef()` on a declRef to the typedef statement. When doing that, it is trying to lower the generic type substitution argument (T->Integrator<Impl>), which triggers the crash as `DeclLoweringVisitor::visitGenericTypeConstraintDecl` only handles cases where the generic type constraint is a child of associatedtype or a `GlobalGenericParamDecl`.

My fix is to change the implementation of `Slang::ValLoweringVisitor::visitNamedExpressionType()` in lower-to-ir.cpp to following:
```
    IRType* visitNamedExpressionType(NamedExpressionType* type)
    {
        return (IRType*)getSimpleVal(context, dispatchType(type->GetCanonicalType()));
    }
```
However, I am not sure that this is the right fix.

### PR DESCRIPTION
**Pull request by csyonghe**
This fixes #559.

### CODE REVIEW

File: source/slang/lower-to-ir.cpp [hunk 1]
```diff
@@ -1058,9 +1058,7 @@ struct ValLoweringVisitor : ValVisitor<ValLoweringVisitor, LoweredValInfo, Lower
 
     IRType* visitNamedExpressionType(NamedExpressionType* type)
     {
-        return (IRType*) getSimpleVal(context,
-            emitDeclRef(context, type->declRef,
-                context->irBuilder->getTypeKind()));
+        return (IRType*)getSimpleVal(context, dispatchType(type->GetCanonicalType()));
```
Comment (tfoleyNV) [inline source/slang/lower-to-ir.cpp]: I think this could just be `lowerType(context, type->GetCanonicalType())`, which might be cleaner so that we have fewer places directly invoking `dispatchType()`.
