### PR TITLE
Fix SPIR-V emit crash from void-typed debug variables in cleanUpVoidType

### LINKED ISSUE #10060: Zero-length array variables have IR unable to be lowered to SPIR-V debug info
# Issue Description

Functions with zero-length array variables are generating IR that is unable to be lowered to the SPIR-V DebugValue instruction correctly:
```
(0): error 99999: Slang compilation aborted due to an exception of N5Slang13InternalErrorE: unimplemented: Unhandled global inst in spirv-emit:
let  %1    : %2    = void_constant
```

# Reproducer Code
```
void f(int[0] droppedArg)
{
    int[0] droppedLocal = {};
    int kept = 1;
}

[shader("compute")]
[numthreads(1, 1, 1)]
void computeMain()
{
    f({});
}
```
`slangc.exe -target spirv-asm -g2 -O0`

# Expected Behavior
Successful compilation, with no debug info for `droppedArg` or `droppedLocal`

# Actual Behavior
Compiler error:
```
(0): error 99999: Slang compilation aborted due to an exception of N5Slang13InternalErrorE: unimplemented: Unhandled global inst in spirv-emit:
let  %1    : %2    = void_constant
```

# Environment
 - Slang v2026.2.2

### PR DESCRIPTION
**Pull request by pdeayton-nv**
* The cleanUpVoidType IR pass was generating DebugValues equal to void_constant, which is not lowerable to a SPIR-V DebugValue, causing an 'Unknown global inst in spirv-emit' compilation error.
* Add processing of DebugVars and DebugValues to the cleanUpVoidType pass, removing any with a type of VoidType
* Remap DebugVar arg indices when function parameters are modified, so the indices map correctly to IRFunc parameter indices.
* Add test case covering void type function arguments and local variables
* Add test case covering functions with modified argument indices after void type removal

Slang repro:
void f(int[0] droppedArg)
{
    int[0] droppedLocal = {};
    int kept = 1;
}

IR after cleanUpVoidType (before):
func %f : Func(Void)
{
    let %droppedArg   : Ptr(Void) = DebugVar(...)
    DebugValue(%droppedArg, void_constant)
    let %droppedLocal : Ptr(Void) = DebugVar(...)
    DebugValue(%droppedLocal, %10)
    let %kept         : Ptr(Int)  = DebugVar(...)
    DebugValue(%kept, 1 : Int)
}
... Unhandled global inst in spirv-emit: ... void_constant

IR after cleanUpVoidType (after):
func %f : Func(Void)
{
    let %kept : Ptr(Int) = DebugVar(...)
    DebugValue(%kept, 1 : Int)
}

Fixes #10060

### CODE REVIEW

File: source/slang/slang-ir-cleanup-void.cpp [hunk 1]
```diff
@@ -69,14 +73,25 @@ struct CleanUpVoidContext
...
                     if (param->getDataType()->getOp() == kIROp_VoidType)
                     {
                         paramsToRemove.add(param);
+                        argIndexRemap.add(-1); // We can remove the IRDebugVar
+                    }
+                    else
+                    {
+                        argIndexRemap.add(nextKeptArgIndex);
+                        nextKeptArgIndex++;
                     }
```
Comment (jkwak-work) [inline source/slang/slang-ir-cleanup-void.cpp]: Feel free to ignore this comment because my suggestion is just for cosmetic.
I think it would be easier to read if it is written as following:
```
bool needToRemove = (param->getDataType()->getOp() == kIROp_VoidType);
argIndexRemap.add( needToRemove ? -1 : nextKeptArgIndex);

if (needToRemove)
{
  paramsToRemove.add(param);
}
else
{
  nextKeptArgIndex++;
}
```

File: source/slang/slang-ir-cleanup-void.cpp [hunk 2]
```diff
@@ -69,14 +73,25 @@ struct CleanUpVoidContext
             break;
         case kIROp_Func:
             {
-                // Remove void parameter.
+                // Remove void parameters.
+                // To keep the ArgIndex operand of the IRDebugVars
+                // corresponding to the function parameters correct, we build a
+                // map to update the IRDebugVar argument indices later.
                 List<IRParam*> paramsToRemove;
+                List<Index> argIndexRemap; // Indexed by old ArgIndex, with value of new ArgIndex
```
Comment (jkwak-work) [inline source/slang/slang-ir-cleanup-void.cpp]: I am wondering if we can call `reserve()` for the List instances, which often turns out to be a performance problem if we don't call it.

File: source/slang/slang-ir-cleanup-void.cpp [hunk 3]
```diff
@@ -87,6 +102,109 @@ struct CleanUpVoidContext
...
+                    }
+                }
+
+                // Detect any VoidType DebugVars, e.g. from locally declared
+                // variables
+                auto debugVarType = debugVar->getDataType();
+                if (auto ptrType = as<IRPtrTypeBase>(debugVarType))
+                {
+                    debugVarType = ptrType->getValueType();
+                }
```
Comment (jkwak-work) [inline source/slang/slang-ir-cleanup-void.cpp]: I wonder if we need to loop in case the type is pointer-of-pointer-of-pointer-and-so-on??

File: source/slang/slang-ir-cleanup-void.cpp [hunk 4]
```diff
@@ -87,6 +102,109 @@ struct CleanUpVoidContext
...
+                {
+                    removeDebugVar = true;
+                }
+
+                // Remove the VoidType DebugVar and any DebugValue users of the DebugVar
+                if (removeDebugVar)
+                {
+                    List<IRInst*> debugValueUsersToRemove;
+                    bool hasNonDebugValueUsers =
+                        false; // Keep the DebugVar if there are non-DebugValue users
```
Comment (jkwak-work) [inline source/slang/slang-ir-cleanup-void.cpp]: It is a bit confusing with double-negative.
Can we rename it to `mayHaveDebugValueUsers = true;`?

File: source/slang/slang-ir-cleanup-void.cpp [hunk 5]
```diff
@@ -174,13 +292,21 @@ struct CleanUpVoidContext
             workList.removeLast();
             workListSet.remove(inst);
 
+            if (inst != module->getModuleInst() && !inst->getParent())
+                continue;
```
Comment (jkwak-work) [inline source/slang/slang-ir-cleanup-void.cpp]: I don't think we should need this check.
If needed, I think they shouldn't be in the workList in the first place; in other words, we should check right before calling `addToWorkList()` rather than check it after calling it.

File: tests/spirv/debug-var-void-argument.slang [hunk 6]
```diff
@@ -0,0 +1,32 @@
+//TEST:SIMPLE(filecheck=CHECK): -target spirv-asm -g2 -O0
+//
+// When a zero-length array function argument is legalized to Void and removed
+// from the function signature, debug variable metadata for the remaining
+// arguments must be remapped to the correct argument indices.
+
+void f(int[0] dropped, int kept)
```
Comment (jkwak-work) [inline tests/spirv/debug-var-void-argument.slang]: I am wondering if we can add a test like the following; but I am not sure if it is actually relevant to this PR:
```
struct MyStruct
{
  Conditional<float3, false> m_color;
}

void f(MyStruct data)
{ ... }
```

File: source/slang/slang-ir-cleanup-void.cpp (hunk 1 above)
Comment (pdeayton-nv) [reply source/slang/slang-ir-cleanup-void.cpp]: Updated to use that snippet

File: source/slang/slang-ir-cleanup-void.cpp (hunk 2 above)
Comment (pdeayton-nv) [reply source/slang/slang-ir-cleanup-void.cpp]: Good idea, updated to call `reserve()`

File: source/slang/slang-ir-cleanup-void.cpp (hunk 3 above)
Comment (pdeayton-nv) [reply source/slang/slang-ir-cleanup-void.cpp]: Updated to loop

File: source/slang/slang-ir-cleanup-void.cpp (hunk 5 above)
Comment (pdeayton-nv) [reply source/slang/slang-ir-cleanup-void.cpp]: Reworked a little to remove that check and use an InstHashSet to add all the instructions to remove

File: tests/spirv/debug-var-void-argument.slang (hunk 6 above)
Comment (pdeayton-nv) [reply tests/spirv/debug-var-void-argument.slang]: Yes, it's relevant since MyStruct becomes a void-type. Added as another argument to f()

File: source/slang/slang-ir-cleanup-void.cpp [hunk 7]
```diff
@@ -181,6 +298,11 @@ struct CleanUpVoidContext
                 addToWorkList(child);
             }
         }
+
+        for (auto inst : m_instsToRemove.getHashSet())
+        {
+            inst->removeAndDeallocate();
+        }
```
[the remark this answers is not in the document]
Comment (pdeayton-nv) [reply source/slang/slang-ir-cleanup-void.cpp:305]: removeAndDeallocate() does not free memory, it only detaches/clears links

File: tools/slang-test/test-context.cpp [hunk 8]
```diff
@@ -220,6 +246,8 @@ SlangResult TestContext::_createJSONRPCConnection(RefPtr<JSONRPCConnection>& out
     SLANG_RETURN_ON_FAIL(
         rpcConnection->init(connection, JSONRPCConnection::CallStyle::Default, process));
 
+    m_jsonRpcErrorStreams[slangTestThreadIndex] = readErrStream;
```
Comment (jkwak-work) [inline tools/slang-test/test-context.cpp]: It is interesting that we were not using `readErrStream` instance at all.
I wonder if we lost some of related implementation during refactoring-s.

File: tools/slang-test/test-context.cpp [hunk 9]
```diff
@@ -274,6 +304,98 @@ Slang::JSONRPCConnection* TestContext::getOrCreateJSONRPCConnection()
...
+    }
+    else
+    {
+        out << "rpc-transport: null\n";
+    }
+
+    auto process = m_jsonRpcProcesses[slangTestThreadIndex];
+    if (process)
+    {
+        const bool isTerminated = process->isTerminated();
```
Comment (jkwak-work) [inline tools/slang-test/test-context.cpp]: It looks like you can use `JSONRPCConnection::isActive()` for this purpose.
You can probably do the following:
```
if (rpcConnection->isActive())
```
But it seems like the function was utilized in the above lines already.

I am not sure why it uses a separate `m_jsonRpcProcesses`, when you can just use `rpcConnection` that is already available.

File: tools/slang-test/test-context.h [hunk 10]
```diff
@@ -204,6 +207,8 @@ class TestContext
     };
 
     Slang::List<Slang::RefPtr<Slang::JSONRPCConnection>> m_jsonRpcConnections;
+    Slang::List<Slang::RefPtr<Slang::BufferedReadStream>> m_jsonRpcErrorStreams;
+    Slang::List<Slang::RefPtr<Slang::Process>> m_jsonRpcProcesses;
```
Comment (jkwak-work) [inline tools/slang-test/test-context.h]: The `process` value is already stored inside of m_jsonRpcConeections`.
It seems like `m_jsonRpcProcesses` is unnecessary duplication.

File: tests/neural/outerproduct-accumulate-test.slang
Comment (jkwak-work) [inline tests/neural/outerproduct-accumulate-test.slang:1]: This test was failing in CI.
The change looks like same as before.
It is unclear what is different/changed.

File: tests/neural/outerproduct-accumulate-test.slang [hunk 11]
```diff
@@ -1,15 +1,25 @@
...
+// TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=BUFFER):-vk -compute -shaderobj -xslang -experimental-feature -output-using-type -emit-spirv-directly -xslang -DTEST_HALF=0 -xslang -DTEST_SIZE=64
 
-// TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=BUFFER):-cuda -compute -shaderobj -output-using-type -xslang -experimental-feature -xslang -DTEST_HALF=0
-// TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=BUFFER):-cuda -compute -shaderobj -output-using-type -xslang -experimental-feature -xslang -DTEST_HALF=1
+// TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=BUFFER):-cuda -compute -shaderobj -output-using-type -xslang -experimental-feature -xslang -DTEST_HALF=0 -xslang -DTEST_SIZE=8
+// TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=BUFFER):-cuda -compute -shaderobj -output-using-type -xslang -experimental-feature -xslang -DTEST_HALF=0 -xslang -DTEST_SIZE=16
+// TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=BUFFER):-cuda -compute -shaderobj -output-using-type -xslang -experimental-feature -xslang -DTEST_HALF=0 -xslang -DTEST_SIZE=32
```
Comment (jkwak-work) [inline tests/neural/outerproduct-accumulate-test.slang]: There is a little different syntax for multiple arguments.
It looks like some like: `-Xslang... -Xdxc -Vd -X.`
In this case, it can be simplified with:
> // TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=BUFFER):-cuda -compute -shaderobj -output-using-type -Xslang... -experimental-feature -DTEST_HALF=0 -DTEST_SIZE=32 -X.

**Review by jkwak-work — DISMISSED** [review]
Looks good to me.
