### PR TITLE
Fix the issue that produce long mangled name

### LINKED ISSUE #9211: Very long mangled name generation for code generation
We generated crazy long mangled name in code generation. The mangled name could be in more 100 Million length. The severely impact the compilation performance.

The code I used to reproduce this issue is
`tests/neural/mma-helper-test-aligned-single-warp.slang`
which is not checked in yet.

But I've not yet check the root cause. I only noticed that the long name is generated when we heavily use type traits, for example

```
struct SomeGeneric<int T1, int T2, int T3, ...>
{
     static const int a = T1;
     static const int b = T2;
     static const int c = T3;
...
     static const int d = op(a, b, c);
}
```

So far, I don't have a minimal reproduce shader code yet, so self-assign this task that I can take a look later as this is not a blocking issue now.

### PR DESCRIPTION
**Pull request by kaizhangNV**
Close #9211.

We use the SHA1 to combine all the arguments's linkage mangled name as the final name for the specialized linkage mangle name.

Previously, it was always appending everything together, so it could be explode the name length very fast.

### CODE REVIEW

File: source/slang/slang-ir-clone.cpp [hunk 1]
```diff
@@ -138,23 +138,28 @@ static void specializeLinkageDecoration(IRInst* target, IRSpecialize* oldInst, I
...
                 {
                     // getTypeNameHint may produce a name with characters that can't
                     // be part of an identifier, so we need to filter it afterward.
-                    StringBuilder tmp;
-                    getTypeNameHint(tmp, arg);
-                    emitNameForLinkage(sb, tmp.getUnownedSlice());
+                    StringBuilder typeNameHint;
+                    StringBuilder linkageName;
+                    getTypeNameHint(typeNameHint, arg);
+                    emitNameForLinkage(linkageName, typeNameHint.getUnownedSlice());
```
Comment (csyonghe) [inline source/slang/slang-ir-clone.cpp]: `emitNameForLinkage` is no longer needed because we no longer care if there are any "illegal" characters in the name.

I think it goes without saying that a better approach is to write a separate function to get a digest from `arg` without going through `getTypeNameHint`, but I can live with it for now.

Comment (kaizhangNV) [reply source/slang/slang-ir-clone.cpp]: I can't say which one is better solution.

digest directly from arg will take append `sizeof(IRInst) == 112` bytes data, while `getTypeNameHint` seems need less data?

Comment (kaizhangNV) [reply source/slang/slang-ir-clone.cpp]: But I removed `emitNameForLinkage` in the latest version.

**Review by csyonghe — APPROVED** [review]

File: source/slang/slang-ir-clone.cpp (hunk 1 above)
Comment (csyonghe) [reply source/slang/slang-ir-clone.cpp]: oh, we can't just hash the raw data of that IRInst, we actually need to traverse through the instruction graph in a similar way to getTypeNameHint so we never hash pointer values, which are not stable across runs. Use getTypeNameHint is fine for now.
