### PR TITLE
Use symbol alias instead of wrapper synthesis to implement link-time types.

### LINKED ISSUE #8554: `export struct` not working when the interface has methods with generic types
I have the following minimal example:
```
interface ILodSampler{}
interface IMaterialInstance{}

interface IMaterial
{
    associatedtype MaterialInstance : IMaterialInstance;
    MaterialInstance setup<TLodSampler : ILodSampler>();
}

struct ConcreteInstance : IMaterialInstance 
{
    float f;
}

struct ConcreteMaterial : IMaterial
{
    typealias MaterialInstance = ConcreteInstance;
    MaterialInstance setup<TLodSampler : ILodSampler>()
    {
        return {4};
    }
}

export struct Material : IMaterial = ConcreteMaterial;
```
playground: https://shader-slang.org/slang-playground/?target=SPIRV&code=eJydkrFOwzAQhnc_xY0wJEaCKQWkEpZKhaUMMBr7Qi0lduS7NERV3x27aaEiFQOe4jt__30nRUqYA9mmrRForQwGaH1gNFAF38CauaVCyr7v87HNfsi1b-TGYi9fTb16pFzImNLx2ocCzOBUYxlTbWk1OsICyhIe3rLnMlvN4Tq_-o7VARXbDcbAxjvKffiQ9QiRfB8ypzNSMhLSIJocnRDWMYZKaYTF0puVSuZhuzutP6n4aVW9cMTKaYzdc22xFRCPIvLaxprhoUX4DUMxDZztwclLQu7a25cfrcT-3O4vLmciqhCHTjOU3sX1Gf8aBAfHqvaKoTqHH5FT_EClfVRtFU1V7ybj_73TnhsHphMzu-Bge7MbE3fJGT_TTwUH9XPKJ0bH0kx8Adfm4yI

And the compiler complains on the last line, that `type 'Material' does not provide required interface member 'setup'(38100)`

If I just delete `<TLodSampler : ILodSampler>` from the code, playground: https://shader-slang.org/slang-playground/?target=SPIRV&code=eJx9kjFPwzAQhXf_ihthSIwEUyqGEpZKhaULjId9oZYSO_JdGqKq_x2naVFFqt5kvefv3bNkrWEJ7Jq2JuAtWorQhihkoYqhga1Iy4XWfd_nky1hyE1o9M5Rrz9svXnlXOmU0sk2xALs4LFxQqO2doY8UwFlCS-f2XuZbZbwmD_8xZpIKG5HKbAJnvMQv3U9Qay_hsybjFEnQlsim5NXynmhWKEhWK2D3eDYPO4Pl_obpqPDeuVZ0BtK7jVb7RWkQeZgXNKsDC3BfxiKeeDiCM5uMknX3t0vVNrHEjsjUAaf3ih0Kw1ORao6oEB1DT8jl_iJGktj7ZDnfZ5n628XP5pT6jgJ7KKH_dNhwg5jMfoZvwec-l3rdbH2LC3UL7gK0DQ
things work as expected.

### PR DESCRIPTION
**Pull request by csyonghe**
This change achieves link-time type resolution with a different mechanism.

For `extern struct Foo : IFoo = FooImpl;`,
instead of synthesizing a wrapper type `Foo` that has a `FooImpl inner` field and dispatches all interface method calls to `inner.method()`, this PR completely removes this synthesis step, and instead just lower such `extern`/`export` types as `IRSymbolAlias` instructions that is just a reference to the type being wrapped.

Then we extend the linker logic to clone the referenced symbol instead of the SymbolAlias insts itself during linking.

By doing so, we greatly simply the logic need to support link-time types, and achieves higher robustness by not having to deal with many AST synthesis scenarios.

Closes #8554.

### CODE REVIEW

File: source/slang/slang-ast-decl.h [hunk 1]
```diff
@@ -386,8 +386,16 @@ class AggTypeDecl : public AggTypeDeclBase
     FIDDLE(...)
     FIDDLE() TypeTag typeTags = TypeTag::None;
 
-    // Used if this type declaration is a wrapper, i.e. struct FooWrapper:IFoo = Foo;
-    TypeExp wrappedType;
+    // When user defines a agg type in the syntax of
+    // `struct FooAlias : IFoo = Foo;`
+    // The user is defining a link-time type alias. In contrast
+    // to an ordinary typealias, a link-time alias is not folded in
+    // the front-end, and rsolved during linking.
```
Comment (kaizhangNV) [inline source/slang/slang-ast-decl.h]: nit: 
       a agg type => an agg type
       rsolved => resolved.

File: source/slang/slang-check-decl.cpp [hunk 2]
```diff
@@ -8056,6 +7650,32 @@ bool SemanticsVisitor::checkConformance(
             // code to work.
             return true;
         }
+
+        // If sub type is a link-time-resolved wrapper type (e.g. `extern struct Foo : IFoo =
+        // FooImpl;`), fill in `inheritanceDecl->witnessVal` with a Witness val that shows `FooImpl
+        // : IFoo`.
+        auto aggTypeDecl = as<AggTypeDecl>(declRef.getDecl());
+
+        if (aggTypeDecl && aggTypeDecl->aliasedType)
```
Comment (kaizhangNV) [inline source/slang/slang-check-decl.cpp:7625]: As my other comment on this `if (aggTypeDecl->aliasedType)`

we should have a bool operator override for `TypeExpr`, now if (aggTypeDecl->aliasedType) will implicitly call the type conversion operator which I don't think it's a recommended way to do that.

File: source/slang/slang-lower-to-ir.cpp [hunk 3]
```diff
@@ -9738,6 +9770,35 @@ struct DeclLoweringVisitor : DeclVisitor<DeclLoweringVisitor, LoweredValInfo>
         // Emit any generics that should wrap the actual type.
         auto outerGeneric = emitOuterGenerics(subContext, decl, decl);
 
+        if (decl->aliasedType)
```
Comment (kaizhangNV) [inline source/slang/slang-lower-to-ir.cpp:9773]: I don't think this is a very recommended way to check `decl->aliasedType.type != nullptr`.
I think We should add a bool operator override for TypeExpr.

File: source/slang/slang-check-decl.cpp [hunk 4]
```diff
@@ -6130,212 +6023,17 @@ bool SemanticsVisitor::trySynthesizePropertyRequirementWitness(
...
-    }
-
-    context->parentDecl->addMember(synPropertyDecl);
-    witnessTable->add(
-        requiredMemberDeclRef.getDecl(),
-        RequirementWitness(makeDeclRef(synPropertyDecl)));
-    return true;
-}
-
 bool SemanticsVisitor::trySynthesizeAssociatedTypeRequirementWitness(
```
Comment (kaizhangNV) [inline source/slang/slang-check-decl.cpp]: why can't we just delete those functions if they just return `false`?

File: source/slang/slang-check-expr.cpp [hunk 5]
```diff
@@ -290,6 +290,13 @@ void addSiblingScopeForContainerDecl(ASTBuilder* builder, Scope* destScope, Cont
     destScope->nextSibling = subScope;
 }
 
+ContainerDecl* isStaticScopeDecl(Decl* decl)
+{
+    if (as<NamespaceDeclBase>(decl) || as<FileDecl>(decl))
```
Comment (kaizhangNV) [inline source/slang/slang-check-expr.cpp:295]: Are you missing `ModuleDecl`?

File: source/slang/slang-ir-link.cpp [hunk 6]
```diff
@@ -1411,7 +1411,10 @@ IRInst* cloneInst(
             builder,
             cast<IRGlobalGenericParam>(originalInst),
             originalValues);
-
+    case kIROp_SymbolAlias:
+        // If we encounter a symbol alias, we want to clone
+        // the value it refers to instead of the alias itself.
+        return context->maybeCloneValue(cast<IRSymbolAlias>(originalInst)->getOperand(0));
```
Comment (kaizhangNV) [inline source/slang/slang-ir-link.cpp:1417]: I can imagine this works well at post-link phase, however, what could happen if any accidental call of this cloneInst at ir-lowering phase? At that time, the operand(0) is not visible yet.

File: source/slang/slang-lower-to-ir.cpp [hunk 7]
```diff
@@ -9738,6 +9770,35 @@ struct DeclLoweringVisitor : DeclVisitor<DeclLoweringVisitor, LoweredValInfo>
...
+                {
+                    alias = finishOuterGenerics(subBuilder, loweredType, outerGeneric);
+                }
+                else
+                {
+                    alias = subBuilder->emitSymbolAlias(loweredType);
+                }
+                addLinkageDecoration(subContext, alias, decl);
+
+                // Enumerate all witnesses and lower IRSymbolAlias for them as well.
```
Comment (kaizhangNV) [inline source/slang/slang-lower-to-ir.cpp:9791]: What are the following logic doing?
Is it possible that a link-time type alias decl has inheritanceDecl?

File: source/slang/slang-parameter-binding.cpp [hunk 8]
```diff
@@ -2205,386 +2205,413 @@ static RefPtr<TypeLayout> processEntryPointVaryingParameter(
         varLayout->flags |= VarLayoutFlag::HasSemantic;
     }
 
-    // Scalar and vector types are treated as outputs directly
-    if (auto basicType = as<BasicExpressionType>(type))
+    // We use a lambda here to process the parameter based on `type`.
```
Comment (kaizhangNV) [inline source/slang/slang-parameter-binding.cpp:2208]: Is the change in this file related to the goal of this PR?

File: source/slang/slang-check-expr.cpp (hunk 5 above)
Comment (csyonghe) [reply source/slang/slang-check-expr.cpp:295]: ModuleDecl inherits from  NamespaceDeclBase

File: source/slang/slang-ir-link.cpp (hunk 6 above)
Comment (csyonghe) [reply source/slang/slang-ir-link.cpp:1417]: cloneIR calls outside this file will never hit this line. This is overridden logic that is triggered only during linking.

File: source/slang/slang-parameter-binding.cpp (hunk 8 above)
Comment (csyonghe) [reply source/slang/slang-parameter-binding.cpp:2208]: yes, this PR also adds tests to verify that reflection works correctly, and as a result, it discovered bugs in reflection that also needs to be fixed.

File: source/slang/slang-lower-to-ir.cpp (hunk 7 above)
Comment (csyonghe) [reply source/slang/slang-lower-to-ir.cpp:9791]: Yes, it is possible.
`export struct Foo : IFoo = FooImpl`
has an `InheritanceDecl` for `IFoo` conformance, and an `aliasedType` that is `FooImpl`.

Comment (csyonghe) [reply source/slang/slang-lower-to-ir.cpp:9791]: Basically, for such `Foo`, we need to make sure:
1. We emit an `IRSymbolAlias` for the type itself, that is `%Foo = alias(%FooImpl)`.
2. We emit an alias for all the conformances,  that is `%Foo_is_IFoo = alias(%FooImpl_is_IFoo)`.

File: source/slang/slang-check-decl.cpp (hunk 4 above)
Comment (csyonghe) [reply source/slang/slang-check-decl.cpp]: sure, deleted. I kept the functions originally thinking one day we may need to add back some synthesis logic, but also fine to just clean them up.

File: source/slang/slang-lower-to-ir.cpp (hunk 3 above)
Comment (csyonghe) [reply source/slang/slang-lower-to-ir.cpp:9773]: added `explicit operator bool` to `TypeExp`.

File: source/slang/slang-ast-decl.h (hunk 1 above)
Comment (csyonghe) [reply source/slang/slang-ast-decl.h]: fixed, thanks!

File: source/slang/slang-lower-to-ir.cpp (hunk 7 above)
Comment (kaizhangNV) [reply source/slang/slang-lower-to-ir.cpp:9791]: I see, thanks.

**Review by kaizhangNV — APPROVED** [review]
LGTM
