### PR TITLE
Fix crash when using `sizeof()` in `static const` definition compiled to binary module

### LINKED ISSUE #10445: v2026.4 regression: using of sizeof() operator in static const definition leads to compiler crash
# Issue Description
After updating slangc from 2026.3.1 to 2026.4 the code with sizeof() in static const defintion doesn't compile anymore.

# Reproducer Code
**test.slang:**
```
typedef uint MsgTy;
static const uint msgLen = sizeof(MsgTy);
```
**old behavior:**
```
> slangc.exe -v
2026.3.1
> slangc.exe test.slang -o test.slang-module -lang slang -std 2026
# builds successfully
```
**new behavior:**
```
> slangc.exe -v
2026.4
> slangc.exe test.slang -o test.slang-module -lang slang -std 2026
# test.slang-module is not produced, returned exit code 1
```

### PR DESCRIPTION
**Pull request by aidanfnv**
Fixes #10445

`tryConstantFoldExpr` is called from `checkVarDeclCommon` during header checking, before the `SemanticsExprVisitor` has visited the init expression. For `SizeOfLikeExpr` nodes, the `sizedType` member is set during expression visiting (`visitSizeOfLikeExpr`), so it is still null at this point. `tryConstantFoldExpr` dereferences it unconditionally via `sizedType->substitute(...)`, creating a `SizeOfIntVal` with a null type-argument operand.

When compiling to a binary module (`-o .slang-module`), the serialization path calls `Val::resolve()` on every `Val` node in the AST. Before #9981, `getCurrentASTBuilder()` returned null outside compilation scopes, so `Val::resolve()` took an early-return path and never touched the broken node's operands. After #9981 set the session's root AST builder in `Session::init()`, `getCurrentASTBuilder()` is always non-null, so `resolve()` falls through to `SizeOfIntVal::_resolveImplOverride()` which dereferences the null operand via `getValArg()->resolve()`, causing a segfault.

This fix adds a null check for `sizedType` in `tryConstantFoldExpr`'s `SizeOfLikeExpr` branch. When `sizedType` is null (because we're in the header-checking phase before `visitSizeOfLikeExpr` has run), it calls `CheckTerm` on the expression to run expression visiting and populate `sizedType`, then proceeds with folding normally.

### CODE REVIEW

**Review by jkwak-work — DISMISSED** [review]
Looks good to me

**Comment by aidanfnv** [comment]
Yong suggested I get a stack trace to understand why sizedType is null here to begin with, and the result I got using the test file, gdb, and a Cursor agent, is: 
```
#0  tryConstantFoldExpr(SubstExpr<Expr>, LinkTime, nullptr)     slang-check-expr.cpp:2399
#1  checkVarDeclCommon(varDecl=0x555558ff60d0)                  slang-check-decl.cpp:2259
#2  visitVarDecl(varDecl)                                       slang-check-decl.cpp:344
#3  DeclVisitor<SemanticsDeclHeaderVisitor>::_dispatchImpl       slang-visitor.h.fiddle:3495
#4–6  (visitor dispatch boilerplate)
#7  _dispatchDeclCheckingVisitor(decl, SignatureChecked)         slang-check-decl.cpp:12255
#8  ensureDecl(decl, ReadyForReference)                         slang-check-decl.cpp:1566
#9  ensureAllDeclsRec(decl, ReadyForReference)                  slang-check-decl.cpp:1609
#10 ensureAllDeclsRec(moduleDecl, ReadyForReference)            slang-check-decl.cpp:1632
#11 checkModule(moduleDecl)                                     slang-check-decl.cpp:4287
#12 checkTranslationUnit                                        slang-check.cpp:193
#13 checkAllTranslationUnits                                    slang-compile-request.cpp:431
#14 executeActionsInner                                         slang-compile-request.cpp:522
#15–17 EndToEndCompileRequest::compile                          slang-end-to-end-request.cpp
#18 spCompile                                                   slang-api.cpp:756
#19 _compile(slangc main)                                       main.cpp:46
```

So we are trying to constant-fold the init expr of static const variables during the `SignatureChecked` declaration checking (frame #7), but `sizedType` is only set later by `visitSizeOfLikeExpr`, which runs during the expression checking. So at this point, we have a `SizeOfExpr` node with value pointing to the `MsgTy` `VarExpr`, but `sizedType` is still its default `nullptr` because `visitSizeOfLikeExpr` has not yet been called on it.

**Comment by aidanfnv** [comment]
I replaced the null guard with running `CheckTerm` on the `SizeOfLikeExpr` in `checkVarDeclCommon`, to handle it like we do unsized arrays. That way we can get `sizedType` early before running `tryConstantFoldExpr` on the `SizeOfLikeExpr`.

File: source/slang/slang-check-decl.cpp [hunk 1]
```diff
@@ -2257,6 +2282,17 @@ void SemanticsDeclHeaderVisitor::checkVarDeclCommon(VarDeclBase* varDecl)
                 (as<NamespaceDeclBase>(parentDecl) || as<FileDecl>(parentDecl) ||
                  varDecl->findModifier<HLSLStaticModifier>()))
             {
+                if (_containsSizeOfLikeExpr(varDecl->initExpr))
```
Comment (csyonghe) [inline source/slang/slang-check-decl.cpp]: don't check for sizeof with `_containsSizeOfLikeExpr`. Instead, call `CheckTerm` in `SemanticsVisitor::tryConstantFoldExpr` (inside the `if (auto sizeOfLikeExpr = expr.as<SizeOfLikeExpr>())` branch), if `sizeOfLikeExpr.getExpr()->sizedType` is null.

Comment (aidanfnv) [reply source/slang/slang-check-decl.cpp]: Fixed, I moved it to right before the null check (but kept the null check just in case)
