### PR TITLE
Fix SPIR-V emit crash for tess factors

### LINKED ISSUE #9496: Conversion of float4 to float[4] not being handled.
# Issue Description
Slang doesn't handle the conversion from float4, to float[4], for builtins such as: `SV_TessFactor`, `SV_InsideTessFactor`, resulting in an error on compile.

# Reproducer Code
Slang code:
```
[vk::push_constant] float tesselationValue;

struct PerVertex {
    float4 position : SV_Position;
};

StructuredBuffer<PerVertex> inBuffer;

// Hull shader requires multiple attributes and a separate patch constant function
[shader("hull")]
[domain("quad")]
[partitioning("fractional_odd")]
[outputtopology("triangle_cw")]
[outputcontrolpoints(16)]
[patchconstantfunc("PatchConstantFunction")]
float4 main(InputPatch<PerVertex, 4> patch, uint invocationID : SV_OutputControlPointID) {
    return inBuffer[invocationID].position;
}

// Separate function for tessellation factors
struct PatchTessFactors {
    float4 tessFactor : SV_TessFactor;
    float2 insideTessFactor : SV_InsideTessFactor;
};

PatchTessFactors PatchConstantFunction(InputPatch<PerVertex, 4> patch) {
    // Set tessellation levels
    PatchTessFactors tessFactors;

    tessFactors.insideTessFactor = float2(tesselationValue, tesselationValue);
    tessFactors.tessFactor = float4(
        tesselationValue, tesselationValue, tesselationValue, tesselationValue
    );
    return tessFactors;
}
```

slangc invocation:
`slangc -target spirv-asm tesc.slang -entry main -stage hull`

# Expected Behavior
Code should compile successfully.

# Actual Behavior
Code does not compile successfully, and instead gives the following error:
```
(0): error 99999: Slang compilation aborted due to an exception of N5Slang13InternalErrorE: unimplemented: Unhandled local inst in spirv-emit:
let  %1 : %2    = BuiltinCast(%3)
```

# Environment
 - Slang Versions: 2025.23.2, 2025.24.2.
 - OS: KDENeon Linux-6.14.0-37-generic-x86_64.

# Additional context
The official docs [here](https://docs.shader-slang.org/en/latest/coming-from-glsl.html) have float4 also (the Hull Shader section).

### PR DESCRIPTION
**Pull request by NV-xiaoyongs**
fixes #9496 

Fix SPIR-V emit crash for tess factors using vector types: Implement kIROp_BuiltinCast lowering in slang-emit-spirv for vector from/to array reshapes (e.g. float4/float2 tess factors)
Add a regression test covering SV_TessFactor/SV_InsideTessFactor on hull shaders.

### CODE REVIEW

File: source/slang/slang-emit-spirv.cpp [hunk 1]
```diff
@@ -4199,6 +4199,9 @@ struct SPIRVEmitContext : public SourceEmitterBase, public SPIRVEmitSharedContex
         case kIROp_CastIntToPtr:
             result = emitCastIntToPtr(parent, inst);
             break;
+        case kIROp_BuiltinCast:
```
Comment (kaizhangNV) [inline source/slang/slang-emit-spirv.cpp]: I think we need to handle this at IR level instead of spirv.
If we compile the original shader to hlsl, the error will be still there.

Comment (NV-xiaoyongs) [reply source/slang/slang-emit-spirv.cpp]: done
